/**
 *
 * @file DEVICE_RegisterDefines_GROUP12.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP12_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP12_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP12_IER_R_X3_BIT ((uint16_t) 0U)

#define DEVICE_GROUP12_IER_X3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_X3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_X3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_X3_MASK (DEVICE_GROUP12_IER_X3_MASK<< DEVICE_GROUP12_IER_R_X3_BIT)
#define DEVICE_GROUP12_IER_R_X3_DIS (DEVICE_GROUP12_IER_X3_DIS << DEVICE_GROUP12_IER_R_X3_BIT)
#define DEVICE_GROUP12_IER_R_X3_ENA (DEVICE_GROUP12_IER_X3_ENA << DEVICE_GROUP12_IER_R_X3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED56_BIT ((uint16_t) 1U)

#define DEVICE_GROUP12_IER_RESERVED56_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED56_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED56_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED56_MASK (DEVICE_GROUP12_IER_RESERVED56_MASK<< DEVICE_GROUP12_IER_R_RESERVED56_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED56_DIS (DEVICE_GROUP12_IER_RESERVED56_DIS << DEVICE_GROUP12_IER_R_RESERVED56_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED56_ENA (DEVICE_GROUP12_IER_RESERVED56_ENA << DEVICE_GROUP12_IER_R_RESERVED56_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED57_BIT ((uint16_t) 2U)

#define DEVICE_GROUP12_IER_RESERVED57_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED57_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED57_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED57_MASK (DEVICE_GROUP12_IER_RESERVED57_MASK<< DEVICE_GROUP12_IER_R_RESERVED57_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED57_DIS (DEVICE_GROUP12_IER_RESERVED57_DIS << DEVICE_GROUP12_IER_R_RESERVED57_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED57_ENA (DEVICE_GROUP12_IER_RESERVED57_ENA << DEVICE_GROUP12_IER_R_RESERVED57_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED58_BIT ((uint16_t) 3U)

#define DEVICE_GROUP12_IER_RESERVED58_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED58_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED58_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED58_MASK (DEVICE_GROUP12_IER_RESERVED58_MASK<< DEVICE_GROUP12_IER_R_RESERVED58_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED58_DIS (DEVICE_GROUP12_IER_RESERVED58_DIS << DEVICE_GROUP12_IER_R_RESERVED58_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED58_ENA (DEVICE_GROUP12_IER_RESERVED58_ENA << DEVICE_GROUP12_IER_R_RESERVED58_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED59_BIT ((uint16_t) 4U)

#define DEVICE_GROUP12_IER_RESERVED59_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED59_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED59_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED59_MASK (DEVICE_GROUP12_IER_RESERVED59_MASK<< DEVICE_GROUP12_IER_R_RESERVED59_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED59_DIS (DEVICE_GROUP12_IER_RESERVED59_DIS << DEVICE_GROUP12_IER_R_RESERVED59_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED59_ENA (DEVICE_GROUP12_IER_RESERVED59_ENA << DEVICE_GROUP12_IER_R_RESERVED59_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED60_BIT ((uint16_t) 5U)

#define DEVICE_GROUP12_IER_RESERVED60_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED60_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED60_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED60_MASK (DEVICE_GROUP12_IER_RESERVED60_MASK<< DEVICE_GROUP12_IER_R_RESERVED60_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED60_DIS (DEVICE_GROUP12_IER_RESERVED60_DIS << DEVICE_GROUP12_IER_R_RESERVED60_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED60_ENA (DEVICE_GROUP12_IER_RESERVED60_ENA << DEVICE_GROUP12_IER_R_RESERVED60_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED61_BIT ((uint16_t) 6U)

#define DEVICE_GROUP12_IER_RESERVED61_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED61_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED61_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED61_MASK (DEVICE_GROUP12_IER_RESERVED61_MASK<< DEVICE_GROUP12_IER_R_RESERVED61_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED61_DIS (DEVICE_GROUP12_IER_RESERVED61_DIS << DEVICE_GROUP12_IER_R_RESERVED61_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED61_ENA (DEVICE_GROUP12_IER_RESERVED61_ENA << DEVICE_GROUP12_IER_R_RESERVED61_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IER_R_RESERVED62_BIT ((uint16_t) 7U)

#define DEVICE_GROUP12_IER_RESERVED62_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IER_RESERVED62_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IER_RESERVED62_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IER_R_RESERVED62_MASK (DEVICE_GROUP12_IER_RESERVED62_MASK<< DEVICE_GROUP12_IER_R_RESERVED62_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED62_DIS (DEVICE_GROUP12_IER_RESERVED62_DIS << DEVICE_GROUP12_IER_R_RESERVED62_BIT)
#define DEVICE_GROUP12_IER_R_RESERVED62_ENA (DEVICE_GROUP12_IER_RESERVED62_ENA << DEVICE_GROUP12_IER_R_RESERVED62_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP12_IFR_R_X3_BIT ((uint16_t) 0U)

#define DEVICE_GROUP12_IFR_X3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_X3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_X3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_X3_MASK (DEVICE_GROUP12_IFR_X3_MASK<< DEVICE_GROUP12_IFR_R_X3_BIT)
#define DEVICE_GROUP12_IFR_R_X3_DIS (DEVICE_GROUP12_IFR_X3_DIS << DEVICE_GROUP12_IFR_R_X3_BIT)
#define DEVICE_GROUP12_IFR_R_X3_ENA (DEVICE_GROUP12_IFR_X3_ENA << DEVICE_GROUP12_IFR_R_X3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED56_BIT ((uint16_t) 1U)

#define DEVICE_GROUP12_IFR_RESERVED56_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED56_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED56_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED56_MASK (DEVICE_GROUP12_IFR_RESERVED56_MASK<< DEVICE_GROUP12_IFR_R_RESERVED56_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED56_DIS (DEVICE_GROUP12_IFR_RESERVED56_DIS << DEVICE_GROUP12_IFR_R_RESERVED56_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED56_ENA (DEVICE_GROUP12_IFR_RESERVED56_ENA << DEVICE_GROUP12_IFR_R_RESERVED56_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED57_BIT ((uint16_t) 2U)

#define DEVICE_GROUP12_IFR_RESERVED57_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED57_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED57_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED57_MASK (DEVICE_GROUP12_IFR_RESERVED57_MASK<< DEVICE_GROUP12_IFR_R_RESERVED57_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED57_DIS (DEVICE_GROUP12_IFR_RESERVED57_DIS << DEVICE_GROUP12_IFR_R_RESERVED57_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED57_ENA (DEVICE_GROUP12_IFR_RESERVED57_ENA << DEVICE_GROUP12_IFR_R_RESERVED57_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED58_BIT ((uint16_t) 3U)

#define DEVICE_GROUP12_IFR_RESERVED58_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED58_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED58_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED58_MASK (DEVICE_GROUP12_IFR_RESERVED58_MASK<< DEVICE_GROUP12_IFR_R_RESERVED58_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED58_DIS (DEVICE_GROUP12_IFR_RESERVED58_DIS << DEVICE_GROUP12_IFR_R_RESERVED58_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED58_ENA (DEVICE_GROUP12_IFR_RESERVED58_ENA << DEVICE_GROUP12_IFR_R_RESERVED58_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED59_BIT ((uint16_t) 4U)

#define DEVICE_GROUP12_IFR_RESERVED59_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED59_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED59_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED59_MASK (DEVICE_GROUP12_IFR_RESERVED59_MASK<< DEVICE_GROUP12_IFR_R_RESERVED59_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED59_DIS (DEVICE_GROUP12_IFR_RESERVED59_DIS << DEVICE_GROUP12_IFR_R_RESERVED59_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED59_ENA (DEVICE_GROUP12_IFR_RESERVED59_ENA << DEVICE_GROUP12_IFR_R_RESERVED59_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED60_BIT ((uint16_t) 5U)

#define DEVICE_GROUP12_IFR_RESERVED60_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED60_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED60_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED60_MASK (DEVICE_GROUP12_IFR_RESERVED60_MASK<< DEVICE_GROUP12_IFR_R_RESERVED60_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED60_DIS (DEVICE_GROUP12_IFR_RESERVED60_DIS << DEVICE_GROUP12_IFR_R_RESERVED60_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED60_ENA (DEVICE_GROUP12_IFR_RESERVED60_ENA << DEVICE_GROUP12_IFR_R_RESERVED60_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED61_BIT ((uint16_t) 6U)

#define DEVICE_GROUP12_IFR_RESERVED61_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED61_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED61_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED61_MASK (DEVICE_GROUP12_IFR_RESERVED61_MASK<< DEVICE_GROUP12_IFR_R_RESERVED61_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED61_DIS (DEVICE_GROUP12_IFR_RESERVED61_DIS << DEVICE_GROUP12_IFR_R_RESERVED61_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED61_ENA (DEVICE_GROUP12_IFR_RESERVED61_ENA << DEVICE_GROUP12_IFR_R_RESERVED61_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP12_IFR_R_RESERVED62_BIT ((uint16_t) 7U)

#define DEVICE_GROUP12_IFR_RESERVED62_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP12_IFR_RESERVED62_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP12_IFR_RESERVED62_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP12_IFR_R_RESERVED62_MASK (DEVICE_GROUP12_IFR_RESERVED62_MASK<< DEVICE_GROUP12_IFR_R_RESERVED62_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED62_DIS (DEVICE_GROUP12_IFR_RESERVED62_DIS << DEVICE_GROUP12_IFR_R_RESERVED62_BIT)
#define DEVICE_GROUP12_IFR_R_RESERVED62_ENA (DEVICE_GROUP12_IFR_RESERVED62_ENA << DEVICE_GROUP12_IFR_R_RESERVED62_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP12_H_ */
