/**
 *
 * @file DEVICE_RegisterDefines_GROUP3.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP3_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP3_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP3_IER_R_EPWM1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP3_IER_EPWM1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_EPWM1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_EPWM1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_EPWM1_MASK (DEVICE_GROUP3_IER_EPWM1_MASK<< DEVICE_GROUP3_IER_R_EPWM1_BIT)
#define DEVICE_GROUP3_IER_R_EPWM1_DIS (DEVICE_GROUP3_IER_EPWM1_DIS << DEVICE_GROUP3_IER_R_EPWM1_BIT)
#define DEVICE_GROUP3_IER_R_EPWM1_ENA (DEVICE_GROUP3_IER_EPWM1_ENA << DEVICE_GROUP3_IER_R_EPWM1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_EPWM2_BIT ((uint16_t) 1U)

#define DEVICE_GROUP3_IER_EPWM2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_EPWM2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_EPWM2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_EPWM2_MASK (DEVICE_GROUP3_IER_EPWM2_MASK<< DEVICE_GROUP3_IER_R_EPWM2_BIT)
#define DEVICE_GROUP3_IER_R_EPWM2_DIS (DEVICE_GROUP3_IER_EPWM2_DIS << DEVICE_GROUP3_IER_R_EPWM2_BIT)
#define DEVICE_GROUP3_IER_R_EPWM2_ENA (DEVICE_GROUP3_IER_EPWM2_ENA << DEVICE_GROUP3_IER_R_EPWM2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_EPWM3_BIT ((uint16_t) 2U)

#define DEVICE_GROUP3_IER_EPWM3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_EPWM3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_EPWM3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_EPWM3_MASK (DEVICE_GROUP3_IER_EPWM3_MASK<< DEVICE_GROUP3_IER_R_EPWM3_BIT)
#define DEVICE_GROUP3_IER_R_EPWM3_DIS (DEVICE_GROUP3_IER_EPWM3_DIS << DEVICE_GROUP3_IER_R_EPWM3_BIT)
#define DEVICE_GROUP3_IER_R_EPWM3_ENA (DEVICE_GROUP3_IER_EPWM3_ENA << DEVICE_GROUP3_IER_R_EPWM3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_EPWM4_BIT ((uint16_t) 3U)

#define DEVICE_GROUP3_IER_EPWM4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_EPWM4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_EPWM4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_EPWM4_MASK (DEVICE_GROUP3_IER_EPWM4_MASK<< DEVICE_GROUP3_IER_R_EPWM4_BIT)
#define DEVICE_GROUP3_IER_R_EPWM4_DIS (DEVICE_GROUP3_IER_EPWM4_DIS << DEVICE_GROUP3_IER_R_EPWM4_BIT)
#define DEVICE_GROUP3_IER_R_EPWM4_ENA (DEVICE_GROUP3_IER_EPWM4_ENA << DEVICE_GROUP3_IER_R_EPWM4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_RESERVED6_BIT ((uint16_t) 4U)

#define DEVICE_GROUP3_IER_RESERVED6_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_RESERVED6_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_RESERVED6_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_RESERVED6_MASK (DEVICE_GROUP3_IER_RESERVED6_MASK<< DEVICE_GROUP3_IER_R_RESERVED6_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED6_DIS (DEVICE_GROUP3_IER_RESERVED6_DIS << DEVICE_GROUP3_IER_R_RESERVED6_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED6_ENA (DEVICE_GROUP3_IER_RESERVED6_ENA << DEVICE_GROUP3_IER_R_RESERVED6_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_RESERVED7_BIT ((uint16_t) 5U)

#define DEVICE_GROUP3_IER_RESERVED7_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_RESERVED7_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_RESERVED7_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_RESERVED7_MASK (DEVICE_GROUP3_IER_RESERVED7_MASK<< DEVICE_GROUP3_IER_R_RESERVED7_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED7_DIS (DEVICE_GROUP3_IER_RESERVED7_DIS << DEVICE_GROUP3_IER_R_RESERVED7_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED7_ENA (DEVICE_GROUP3_IER_RESERVED7_ENA << DEVICE_GROUP3_IER_R_RESERVED7_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_RESERVED8_BIT ((uint16_t) 6U)

#define DEVICE_GROUP3_IER_RESERVED8_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_RESERVED8_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_RESERVED8_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_RESERVED8_MASK (DEVICE_GROUP3_IER_RESERVED8_MASK<< DEVICE_GROUP3_IER_R_RESERVED8_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED8_DIS (DEVICE_GROUP3_IER_RESERVED8_DIS << DEVICE_GROUP3_IER_R_RESERVED8_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED8_ENA (DEVICE_GROUP3_IER_RESERVED8_ENA << DEVICE_GROUP3_IER_R_RESERVED8_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IER_R_RESERVED9_BIT ((uint16_t) 7U)

#define DEVICE_GROUP3_IER_RESERVED9_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IER_RESERVED9_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IER_RESERVED9_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IER_R_RESERVED9_MASK (DEVICE_GROUP3_IER_RESERVED9_MASK<< DEVICE_GROUP3_IER_R_RESERVED9_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED9_DIS (DEVICE_GROUP3_IER_RESERVED9_DIS << DEVICE_GROUP3_IER_R_RESERVED9_BIT)
#define DEVICE_GROUP3_IER_R_RESERVED9_ENA (DEVICE_GROUP3_IER_RESERVED9_ENA << DEVICE_GROUP3_IER_R_RESERVED9_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP3_IFR_R_EPWM1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP3_IFR_EPWM1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_EPWM1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_EPWM1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_EPWM1_MASK (DEVICE_GROUP3_IFR_EPWM1_MASK<< DEVICE_GROUP3_IFR_R_EPWM1_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM1_DIS (DEVICE_GROUP3_IFR_EPWM1_DIS << DEVICE_GROUP3_IFR_R_EPWM1_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM1_ENA (DEVICE_GROUP3_IFR_EPWM1_ENA << DEVICE_GROUP3_IFR_R_EPWM1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_EPWM2_BIT ((uint16_t) 1U)

#define DEVICE_GROUP3_IFR_EPWM2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_EPWM2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_EPWM2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_EPWM2_MASK (DEVICE_GROUP3_IFR_EPWM2_MASK<< DEVICE_GROUP3_IFR_R_EPWM2_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM2_DIS (DEVICE_GROUP3_IFR_EPWM2_DIS << DEVICE_GROUP3_IFR_R_EPWM2_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM2_ENA (DEVICE_GROUP3_IFR_EPWM2_ENA << DEVICE_GROUP3_IFR_R_EPWM2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_EPWM3_BIT ((uint16_t) 2U)

#define DEVICE_GROUP3_IFR_EPWM3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_EPWM3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_EPWM3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_EPWM3_MASK (DEVICE_GROUP3_IFR_EPWM3_MASK<< DEVICE_GROUP3_IFR_R_EPWM3_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM3_DIS (DEVICE_GROUP3_IFR_EPWM3_DIS << DEVICE_GROUP3_IFR_R_EPWM3_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM3_ENA (DEVICE_GROUP3_IFR_EPWM3_ENA << DEVICE_GROUP3_IFR_R_EPWM3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_EPWM4_BIT ((uint16_t) 3U)

#define DEVICE_GROUP3_IFR_EPWM4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_EPWM4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_EPWM4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_EPWM4_MASK (DEVICE_GROUP3_IFR_EPWM4_MASK<< DEVICE_GROUP3_IFR_R_EPWM4_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM4_DIS (DEVICE_GROUP3_IFR_EPWM4_DIS << DEVICE_GROUP3_IFR_R_EPWM4_BIT)
#define DEVICE_GROUP3_IFR_R_EPWM4_ENA (DEVICE_GROUP3_IFR_EPWM4_ENA << DEVICE_GROUP3_IFR_R_EPWM4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_RESERVED6_BIT ((uint16_t) 4U)

#define DEVICE_GROUP3_IFR_RESERVED6_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_RESERVED6_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_RESERVED6_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_RESERVED6_MASK (DEVICE_GROUP3_IFR_RESERVED6_MASK<< DEVICE_GROUP3_IFR_R_RESERVED6_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED6_DIS (DEVICE_GROUP3_IFR_RESERVED6_DIS << DEVICE_GROUP3_IFR_R_RESERVED6_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED6_ENA (DEVICE_GROUP3_IFR_RESERVED6_ENA << DEVICE_GROUP3_IFR_R_RESERVED6_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_RESERVED7_BIT ((uint16_t) 5U)

#define DEVICE_GROUP3_IFR_RESERVED7_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_RESERVED7_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_RESERVED7_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_RESERVED7_MASK (DEVICE_GROUP3_IFR_RESERVED7_MASK<< DEVICE_GROUP3_IFR_R_RESERVED7_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED7_DIS (DEVICE_GROUP3_IFR_RESERVED7_DIS << DEVICE_GROUP3_IFR_R_RESERVED7_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED7_ENA (DEVICE_GROUP3_IFR_RESERVED7_ENA << DEVICE_GROUP3_IFR_R_RESERVED7_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_RESERVED8_BIT ((uint16_t) 6U)

#define DEVICE_GROUP3_IFR_RESERVED8_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_RESERVED8_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_RESERVED8_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_RESERVED8_MASK (DEVICE_GROUP3_IFR_RESERVED8_MASK<< DEVICE_GROUP3_IFR_R_RESERVED8_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED8_DIS (DEVICE_GROUP3_IFR_RESERVED8_DIS << DEVICE_GROUP3_IFR_R_RESERVED8_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED8_ENA (DEVICE_GROUP3_IFR_RESERVED8_ENA << DEVICE_GROUP3_IFR_R_RESERVED8_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP3_IFR_R_RESERVED9_BIT ((uint16_t) 7U)

#define DEVICE_GROUP3_IFR_RESERVED9_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP3_IFR_RESERVED9_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP3_IFR_RESERVED9_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP3_IFR_R_RESERVED9_MASK (DEVICE_GROUP3_IFR_RESERVED9_MASK<< DEVICE_GROUP3_IFR_R_RESERVED9_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED9_DIS (DEVICE_GROUP3_IFR_RESERVED9_DIS << DEVICE_GROUP3_IFR_R_RESERVED9_BIT)
#define DEVICE_GROUP3_IFR_R_RESERVED9_ENA (DEVICE_GROUP3_IFR_RESERVED9_ENA << DEVICE_GROUP3_IFR_R_RESERVED9_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP3_H_ */
