/**
 *
 * @file DEVICE_RegisterDefines_GROUP2.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP2_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP2_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP2_IER_R_EPWM1_TZ_BIT ((uint16_t) 0U)

#define DEVICE_GROUP2_IER_EPWM1_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_EPWM1_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_EPWM1_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_EPWM1_TZ_MASK (DEVICE_GROUP2_IER_EPWM1_TZ_MASK<< DEVICE_GROUP2_IER_R_EPWM1_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM1_TZ_DIS (DEVICE_GROUP2_IER_EPWM1_TZ_DIS << DEVICE_GROUP2_IER_R_EPWM1_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM1_TZ_ENA (DEVICE_GROUP2_IER_EPWM1_TZ_ENA << DEVICE_GROUP2_IER_R_EPWM1_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_EPWM2_TZ_BIT ((uint16_t) 1U)

#define DEVICE_GROUP2_IER_EPWM2_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_EPWM2_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_EPWM2_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_EPWM2_TZ_MASK (DEVICE_GROUP2_IER_EPWM2_TZ_MASK<< DEVICE_GROUP2_IER_R_EPWM2_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM2_TZ_DIS (DEVICE_GROUP2_IER_EPWM2_TZ_DIS << DEVICE_GROUP2_IER_R_EPWM2_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM2_TZ_ENA (DEVICE_GROUP2_IER_EPWM2_TZ_ENA << DEVICE_GROUP2_IER_R_EPWM2_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_EPWM3_TZ_BIT ((uint16_t) 2U)

#define DEVICE_GROUP2_IER_EPWM3_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_EPWM3_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_EPWM3_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_EPWM3_TZ_MASK (DEVICE_GROUP2_IER_EPWM3_TZ_MASK<< DEVICE_GROUP2_IER_R_EPWM3_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM3_TZ_DIS (DEVICE_GROUP2_IER_EPWM3_TZ_DIS << DEVICE_GROUP2_IER_R_EPWM3_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM3_TZ_ENA (DEVICE_GROUP2_IER_EPWM3_TZ_ENA << DEVICE_GROUP2_IER_R_EPWM3_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_EPWM4_TZ_BIT ((uint16_t) 3U)

#define DEVICE_GROUP2_IER_EPWM4_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_EPWM4_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_EPWM4_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_EPWM4_TZ_MASK (DEVICE_GROUP2_IER_EPWM4_TZ_MASK<< DEVICE_GROUP2_IER_R_EPWM4_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM4_TZ_DIS (DEVICE_GROUP2_IER_EPWM4_TZ_DIS << DEVICE_GROUP2_IER_R_EPWM4_TZ_BIT)
#define DEVICE_GROUP2_IER_R_EPWM4_TZ_ENA (DEVICE_GROUP2_IER_EPWM4_TZ_ENA << DEVICE_GROUP2_IER_R_EPWM4_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_RESERVED2_BIT ((uint16_t) 4U)

#define DEVICE_GROUP2_IER_RESERVED2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_RESERVED2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_RESERVED2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_RESERVED2_MASK (DEVICE_GROUP2_IER_RESERVED2_MASK<< DEVICE_GROUP2_IER_R_RESERVED2_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED2_DIS (DEVICE_GROUP2_IER_RESERVED2_DIS << DEVICE_GROUP2_IER_R_RESERVED2_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED2_ENA (DEVICE_GROUP2_IER_RESERVED2_ENA << DEVICE_GROUP2_IER_R_RESERVED2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_RESERVED3_BIT ((uint16_t) 5U)

#define DEVICE_GROUP2_IER_RESERVED3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_RESERVED3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_RESERVED3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_RESERVED3_MASK (DEVICE_GROUP2_IER_RESERVED3_MASK<< DEVICE_GROUP2_IER_R_RESERVED3_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED3_DIS (DEVICE_GROUP2_IER_RESERVED3_DIS << DEVICE_GROUP2_IER_R_RESERVED3_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED3_ENA (DEVICE_GROUP2_IER_RESERVED3_ENA << DEVICE_GROUP2_IER_R_RESERVED3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_RESERVED4_BIT ((uint16_t) 6U)

#define DEVICE_GROUP2_IER_RESERVED4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_RESERVED4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_RESERVED4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_RESERVED4_MASK (DEVICE_GROUP2_IER_RESERVED4_MASK<< DEVICE_GROUP2_IER_R_RESERVED4_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED4_DIS (DEVICE_GROUP2_IER_RESERVED4_DIS << DEVICE_GROUP2_IER_R_RESERVED4_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED4_ENA (DEVICE_GROUP2_IER_RESERVED4_ENA << DEVICE_GROUP2_IER_R_RESERVED4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IER_R_RESERVED5_BIT ((uint16_t) 7U)

#define DEVICE_GROUP2_IER_RESERVED5_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IER_RESERVED5_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IER_RESERVED5_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IER_R_RESERVED5_MASK (DEVICE_GROUP2_IER_RESERVED5_MASK<< DEVICE_GROUP2_IER_R_RESERVED5_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED5_DIS (DEVICE_GROUP2_IER_RESERVED5_DIS << DEVICE_GROUP2_IER_R_RESERVED5_BIT)
#define DEVICE_GROUP2_IER_R_RESERVED5_ENA (DEVICE_GROUP2_IER_RESERVED5_ENA << DEVICE_GROUP2_IER_R_RESERVED5_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP2_IFR_R_EPWM1_TZ_BIT ((uint16_t) 0U)

#define DEVICE_GROUP2_IFR_EPWM1_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_EPWM1_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_EPWM1_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_EPWM1_TZ_MASK (DEVICE_GROUP2_IFR_EPWM1_TZ_MASK<< DEVICE_GROUP2_IFR_R_EPWM1_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM1_TZ_DIS (DEVICE_GROUP2_IFR_EPWM1_TZ_DIS << DEVICE_GROUP2_IFR_R_EPWM1_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM1_TZ_ENA (DEVICE_GROUP2_IFR_EPWM1_TZ_ENA << DEVICE_GROUP2_IFR_R_EPWM1_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_EPWM2_TZ_BIT ((uint16_t) 1U)

#define DEVICE_GROUP2_IFR_EPWM2_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_EPWM2_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_EPWM2_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_EPWM2_TZ_MASK (DEVICE_GROUP2_IFR_EPWM2_TZ_MASK<< DEVICE_GROUP2_IFR_R_EPWM2_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM2_TZ_DIS (DEVICE_GROUP2_IFR_EPWM2_TZ_DIS << DEVICE_GROUP2_IFR_R_EPWM2_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM2_TZ_ENA (DEVICE_GROUP2_IFR_EPWM2_TZ_ENA << DEVICE_GROUP2_IFR_R_EPWM2_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_EPWM3_TZ_BIT ((uint16_t) 2U)

#define DEVICE_GROUP2_IFR_EPWM3_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_EPWM3_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_EPWM3_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_EPWM3_TZ_MASK (DEVICE_GROUP2_IFR_EPWM3_TZ_MASK<< DEVICE_GROUP2_IFR_R_EPWM3_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM3_TZ_DIS (DEVICE_GROUP2_IFR_EPWM3_TZ_DIS << DEVICE_GROUP2_IFR_R_EPWM3_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM3_TZ_ENA (DEVICE_GROUP2_IFR_EPWM3_TZ_ENA << DEVICE_GROUP2_IFR_R_EPWM3_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_EPWM4_TZ_BIT ((uint16_t) 3U)

#define DEVICE_GROUP2_IFR_EPWM4_TZ_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_EPWM4_TZ_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_EPWM4_TZ_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_EPWM4_TZ_MASK (DEVICE_GROUP2_IFR_EPWM4_TZ_MASK<< DEVICE_GROUP2_IFR_R_EPWM4_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM4_TZ_DIS (DEVICE_GROUP2_IFR_EPWM4_TZ_DIS << DEVICE_GROUP2_IFR_R_EPWM4_TZ_BIT)
#define DEVICE_GROUP2_IFR_R_EPWM4_TZ_ENA (DEVICE_GROUP2_IFR_EPWM4_TZ_ENA << DEVICE_GROUP2_IFR_R_EPWM4_TZ_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_RESERVED2_BIT ((uint16_t) 4U)

#define DEVICE_GROUP2_IFR_RESERVED2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_RESERVED2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_RESERVED2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_RESERVED2_MASK (DEVICE_GROUP2_IFR_RESERVED2_MASK<< DEVICE_GROUP2_IFR_R_RESERVED2_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED2_DIS (DEVICE_GROUP2_IFR_RESERVED2_DIS << DEVICE_GROUP2_IFR_R_RESERVED2_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED2_ENA (DEVICE_GROUP2_IFR_RESERVED2_ENA << DEVICE_GROUP2_IFR_R_RESERVED2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_RESERVED3_BIT ((uint16_t) 5U)

#define DEVICE_GROUP2_IFR_RESERVED3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_RESERVED3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_RESERVED3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_RESERVED3_MASK (DEVICE_GROUP2_IFR_RESERVED3_MASK<< DEVICE_GROUP2_IFR_R_RESERVED3_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED3_DIS (DEVICE_GROUP2_IFR_RESERVED3_DIS << DEVICE_GROUP2_IFR_R_RESERVED3_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED3_ENA (DEVICE_GROUP2_IFR_RESERVED3_ENA << DEVICE_GROUP2_IFR_R_RESERVED3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_RESERVED4_BIT ((uint16_t) 6U)

#define DEVICE_GROUP2_IFR_RESERVED4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_RESERVED4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_RESERVED4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_RESERVED4_MASK (DEVICE_GROUP2_IFR_RESERVED4_MASK<< DEVICE_GROUP2_IFR_R_RESERVED4_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED4_DIS (DEVICE_GROUP2_IFR_RESERVED4_DIS << DEVICE_GROUP2_IFR_R_RESERVED4_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED4_ENA (DEVICE_GROUP2_IFR_RESERVED4_ENA << DEVICE_GROUP2_IFR_R_RESERVED4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP2_IFR_R_RESERVED5_BIT ((uint16_t) 7U)

#define DEVICE_GROUP2_IFR_RESERVED5_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP2_IFR_RESERVED5_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP2_IFR_RESERVED5_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP2_IFR_R_RESERVED5_MASK (DEVICE_GROUP2_IFR_RESERVED5_MASK<< DEVICE_GROUP2_IFR_R_RESERVED5_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED5_DIS (DEVICE_GROUP2_IFR_RESERVED5_DIS << DEVICE_GROUP2_IFR_R_RESERVED5_BIT)
#define DEVICE_GROUP2_IFR_R_RESERVED5_ENA (DEVICE_GROUP2_IFR_RESERVED5_ENA << DEVICE_GROUP2_IFR_R_RESERVED5_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP2_H_ */
