/**
 *
 * @file DEVICE_RegisterDefines_GROUP11.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP11_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP11_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP11_IER_R_SW3_BIT ((uint16_t) 0U)

#define DEVICE_GROUP11_IER_SW3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_SW3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_SW3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_SW3_MASK (DEVICE_GROUP11_IER_SW3_MASK<< DEVICE_GROUP11_IER_R_SW3_BIT)
#define DEVICE_GROUP11_IER_R_SW3_DIS (DEVICE_GROUP11_IER_SW3_DIS << DEVICE_GROUP11_IER_R_SW3_BIT)
#define DEVICE_GROUP11_IER_R_SW3_ENA (DEVICE_GROUP11_IER_SW3_ENA << DEVICE_GROUP11_IER_R_SW3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED49_BIT ((uint16_t) 1U)

#define DEVICE_GROUP11_IER_RESERVED49_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED49_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED49_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED49_MASK (DEVICE_GROUP11_IER_RESERVED49_MASK<< DEVICE_GROUP11_IER_R_RESERVED49_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED49_DIS (DEVICE_GROUP11_IER_RESERVED49_DIS << DEVICE_GROUP11_IER_R_RESERVED49_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED49_ENA (DEVICE_GROUP11_IER_RESERVED49_ENA << DEVICE_GROUP11_IER_R_RESERVED49_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED50_BIT ((uint16_t) 2U)

#define DEVICE_GROUP11_IER_RESERVED50_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED50_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED50_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED50_MASK (DEVICE_GROUP11_IER_RESERVED50_MASK<< DEVICE_GROUP11_IER_R_RESERVED50_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED50_DIS (DEVICE_GROUP11_IER_RESERVED50_DIS << DEVICE_GROUP11_IER_R_RESERVED50_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED50_ENA (DEVICE_GROUP11_IER_RESERVED50_ENA << DEVICE_GROUP11_IER_R_RESERVED50_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED51_BIT ((uint16_t) 3U)

#define DEVICE_GROUP11_IER_RESERVED51_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED51_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED51_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED51_MASK (DEVICE_GROUP11_IER_RESERVED51_MASK<< DEVICE_GROUP11_IER_R_RESERVED51_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED51_DIS (DEVICE_GROUP11_IER_RESERVED51_DIS << DEVICE_GROUP11_IER_R_RESERVED51_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED51_ENA (DEVICE_GROUP11_IER_RESERVED51_ENA << DEVICE_GROUP11_IER_R_RESERVED51_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED52_BIT ((uint16_t) 4U)

#define DEVICE_GROUP11_IER_RESERVED52_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED52_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED52_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED52_MASK (DEVICE_GROUP11_IER_RESERVED52_MASK<< DEVICE_GROUP11_IER_R_RESERVED52_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED52_DIS (DEVICE_GROUP11_IER_RESERVED52_DIS << DEVICE_GROUP11_IER_R_RESERVED52_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED52_ENA (DEVICE_GROUP11_IER_RESERVED52_ENA << DEVICE_GROUP11_IER_R_RESERVED52_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED53_BIT ((uint16_t) 5U)

#define DEVICE_GROUP11_IER_RESERVED53_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED53_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED53_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED53_MASK (DEVICE_GROUP11_IER_RESERVED53_MASK<< DEVICE_GROUP11_IER_R_RESERVED53_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED53_DIS (DEVICE_GROUP11_IER_RESERVED53_DIS << DEVICE_GROUP11_IER_R_RESERVED53_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED53_ENA (DEVICE_GROUP11_IER_RESERVED53_ENA << DEVICE_GROUP11_IER_R_RESERVED53_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED54_BIT ((uint16_t) 6U)

#define DEVICE_GROUP11_IER_RESERVED54_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED54_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED54_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED54_MASK (DEVICE_GROUP11_IER_RESERVED54_MASK<< DEVICE_GROUP11_IER_R_RESERVED54_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED54_DIS (DEVICE_GROUP11_IER_RESERVED54_DIS << DEVICE_GROUP11_IER_R_RESERVED54_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED54_ENA (DEVICE_GROUP11_IER_RESERVED54_ENA << DEVICE_GROUP11_IER_R_RESERVED54_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IER_R_RESERVED55_BIT ((uint16_t) 7U)

#define DEVICE_GROUP11_IER_RESERVED55_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IER_RESERVED55_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IER_RESERVED55_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IER_R_RESERVED55_MASK (DEVICE_GROUP11_IER_RESERVED55_MASK<< DEVICE_GROUP11_IER_R_RESERVED55_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED55_DIS (DEVICE_GROUP11_IER_RESERVED55_DIS << DEVICE_GROUP11_IER_R_RESERVED55_BIT)
#define DEVICE_GROUP11_IER_R_RESERVED55_ENA (DEVICE_GROUP11_IER_RESERVED55_ENA << DEVICE_GROUP11_IER_R_RESERVED55_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP11_IFR_R_SW3_BIT ((uint16_t) 0U)

#define DEVICE_GROUP11_IFR_SW3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_SW3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_SW3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_SW3_MASK (DEVICE_GROUP11_IFR_SW3_MASK<< DEVICE_GROUP11_IFR_R_SW3_BIT)
#define DEVICE_GROUP11_IFR_R_SW3_DIS (DEVICE_GROUP11_IFR_SW3_DIS << DEVICE_GROUP11_IFR_R_SW3_BIT)
#define DEVICE_GROUP11_IFR_R_SW3_ENA (DEVICE_GROUP11_IFR_SW3_ENA << DEVICE_GROUP11_IFR_R_SW3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED49_BIT ((uint16_t) 1U)

#define DEVICE_GROUP11_IFR_RESERVED49_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED49_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED49_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED49_MASK (DEVICE_GROUP11_IFR_RESERVED49_MASK<< DEVICE_GROUP11_IFR_R_RESERVED49_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED49_DIS (DEVICE_GROUP11_IFR_RESERVED49_DIS << DEVICE_GROUP11_IFR_R_RESERVED49_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED49_ENA (DEVICE_GROUP11_IFR_RESERVED49_ENA << DEVICE_GROUP11_IFR_R_RESERVED49_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED50_BIT ((uint16_t) 2U)

#define DEVICE_GROUP11_IFR_RESERVED50_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED50_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED50_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED50_MASK (DEVICE_GROUP11_IFR_RESERVED50_MASK<< DEVICE_GROUP11_IFR_R_RESERVED50_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED50_DIS (DEVICE_GROUP11_IFR_RESERVED50_DIS << DEVICE_GROUP11_IFR_R_RESERVED50_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED50_ENA (DEVICE_GROUP11_IFR_RESERVED50_ENA << DEVICE_GROUP11_IFR_R_RESERVED50_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED51_BIT ((uint16_t) 3U)

#define DEVICE_GROUP11_IFR_RESERVED51_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED51_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED51_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED51_MASK (DEVICE_GROUP11_IFR_RESERVED51_MASK<< DEVICE_GROUP11_IFR_R_RESERVED51_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED51_DIS (DEVICE_GROUP11_IFR_RESERVED51_DIS << DEVICE_GROUP11_IFR_R_RESERVED51_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED51_ENA (DEVICE_GROUP11_IFR_RESERVED51_ENA << DEVICE_GROUP11_IFR_R_RESERVED51_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED52_BIT ((uint16_t) 4U)

#define DEVICE_GROUP11_IFR_RESERVED52_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED52_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED52_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED52_MASK (DEVICE_GROUP11_IFR_RESERVED52_MASK<< DEVICE_GROUP11_IFR_R_RESERVED52_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED52_DIS (DEVICE_GROUP11_IFR_RESERVED52_DIS << DEVICE_GROUP11_IFR_R_RESERVED52_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED52_ENA (DEVICE_GROUP11_IFR_RESERVED52_ENA << DEVICE_GROUP11_IFR_R_RESERVED52_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED53_BIT ((uint16_t) 5U)

#define DEVICE_GROUP11_IFR_RESERVED53_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED53_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED53_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED53_MASK (DEVICE_GROUP11_IFR_RESERVED53_MASK<< DEVICE_GROUP11_IFR_R_RESERVED53_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED53_DIS (DEVICE_GROUP11_IFR_RESERVED53_DIS << DEVICE_GROUP11_IFR_R_RESERVED53_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED53_ENA (DEVICE_GROUP11_IFR_RESERVED53_ENA << DEVICE_GROUP11_IFR_R_RESERVED53_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED54_BIT ((uint16_t) 6U)

#define DEVICE_GROUP11_IFR_RESERVED54_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED54_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED54_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED54_MASK (DEVICE_GROUP11_IFR_RESERVED54_MASK<< DEVICE_GROUP11_IFR_R_RESERVED54_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED54_DIS (DEVICE_GROUP11_IFR_RESERVED54_DIS << DEVICE_GROUP11_IFR_R_RESERVED54_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED54_ENA (DEVICE_GROUP11_IFR_RESERVED54_ENA << DEVICE_GROUP11_IFR_R_RESERVED54_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP11_IFR_R_RESERVED55_BIT ((uint16_t) 7U)

#define DEVICE_GROUP11_IFR_RESERVED55_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP11_IFR_RESERVED55_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP11_IFR_RESERVED55_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP11_IFR_R_RESERVED55_MASK (DEVICE_GROUP11_IFR_RESERVED55_MASK<< DEVICE_GROUP11_IFR_R_RESERVED55_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED55_DIS (DEVICE_GROUP11_IFR_RESERVED55_DIS << DEVICE_GROUP11_IFR_R_RESERVED55_BIT)
#define DEVICE_GROUP11_IFR_R_RESERVED55_ENA (DEVICE_GROUP11_IFR_RESERVED55_ENA << DEVICE_GROUP11_IFR_R_RESERVED55_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP11_H_ */
