/**
 *
 * @file DEVICE_RegisterDefines_GROUP.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP_IER_R_IE1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP_IER_IE1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE1_MASK (DEVICE_GROUP_IER_IE1_MASK<< DEVICE_GROUP_IER_R_IE1_BIT)
#define DEVICE_GROUP_IER_R_IE1_DIS (DEVICE_GROUP_IER_IE1_DIS << DEVICE_GROUP_IER_R_IE1_BIT)
#define DEVICE_GROUP_IER_R_IE1_ENA (DEVICE_GROUP_IER_IE1_ENA << DEVICE_GROUP_IER_R_IE1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE2_BIT ((uint16_t) 1U)

#define DEVICE_GROUP_IER_IE2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE2_MASK (DEVICE_GROUP_IER_IE2_MASK<< DEVICE_GROUP_IER_R_IE2_BIT)
#define DEVICE_GROUP_IER_R_IE2_DIS (DEVICE_GROUP_IER_IE2_DIS << DEVICE_GROUP_IER_R_IE2_BIT)
#define DEVICE_GROUP_IER_R_IE2_ENA (DEVICE_GROUP_IER_IE2_ENA << DEVICE_GROUP_IER_R_IE2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE3_BIT ((uint16_t) 2U)

#define DEVICE_GROUP_IER_IE3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE3_MASK (DEVICE_GROUP_IER_IE3_MASK<< DEVICE_GROUP_IER_R_IE3_BIT)
#define DEVICE_GROUP_IER_R_IE3_DIS (DEVICE_GROUP_IER_IE3_DIS << DEVICE_GROUP_IER_R_IE3_BIT)
#define DEVICE_GROUP_IER_R_IE3_ENA (DEVICE_GROUP_IER_IE3_ENA << DEVICE_GROUP_IER_R_IE3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE4_BIT ((uint16_t) 3U)

#define DEVICE_GROUP_IER_IE4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE4_MASK (DEVICE_GROUP_IER_IE4_MASK<< DEVICE_GROUP_IER_R_IE4_BIT)
#define DEVICE_GROUP_IER_R_IE4_DIS (DEVICE_GROUP_IER_IE4_DIS << DEVICE_GROUP_IER_R_IE4_BIT)
#define DEVICE_GROUP_IER_R_IE4_ENA (DEVICE_GROUP_IER_IE4_ENA << DEVICE_GROUP_IER_R_IE4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE5_BIT ((uint16_t) 4U)

#define DEVICE_GROUP_IER_IE5_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE5_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE5_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE5_MASK (DEVICE_GROUP_IER_IE5_MASK<< DEVICE_GROUP_IER_R_IE5_BIT)
#define DEVICE_GROUP_IER_R_IE5_DIS (DEVICE_GROUP_IER_IE5_DIS << DEVICE_GROUP_IER_R_IE5_BIT)
#define DEVICE_GROUP_IER_R_IE5_ENA (DEVICE_GROUP_IER_IE5_ENA << DEVICE_GROUP_IER_R_IE5_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE6_BIT ((uint16_t) 5U)

#define DEVICE_GROUP_IER_IE6_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE6_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE6_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE6_MASK (DEVICE_GROUP_IER_IE6_MASK<< DEVICE_GROUP_IER_R_IE6_BIT)
#define DEVICE_GROUP_IER_R_IE6_DIS (DEVICE_GROUP_IER_IE6_DIS << DEVICE_GROUP_IER_R_IE6_BIT)
#define DEVICE_GROUP_IER_R_IE6_ENA (DEVICE_GROUP_IER_IE6_ENA << DEVICE_GROUP_IER_R_IE6_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE7_BIT ((uint16_t) 6U)

#define DEVICE_GROUP_IER_IE7_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE7_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE7_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE7_MASK (DEVICE_GROUP_IER_IE7_MASK<< DEVICE_GROUP_IER_R_IE7_BIT)
#define DEVICE_GROUP_IER_R_IE7_DIS (DEVICE_GROUP_IER_IE7_DIS << DEVICE_GROUP_IER_R_IE7_BIT)
#define DEVICE_GROUP_IER_R_IE7_ENA (DEVICE_GROUP_IER_IE7_ENA << DEVICE_GROUP_IER_R_IE7_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IER_R_IE8_BIT ((uint16_t) 7U)

#define DEVICE_GROUP_IER_IE8_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IER_IE8_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IER_IE8_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IER_R_IE8_MASK (DEVICE_GROUP_IER_IE8_MASK<< DEVICE_GROUP_IER_R_IE8_BIT)
#define DEVICE_GROUP_IER_R_IE8_DIS (DEVICE_GROUP_IER_IE8_DIS << DEVICE_GROUP_IER_R_IE8_BIT)
#define DEVICE_GROUP_IER_R_IE8_ENA (DEVICE_GROUP_IER_IE8_ENA << DEVICE_GROUP_IER_R_IE8_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP_IFR_R_IF1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP_IFR_IF1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF1_MASK (DEVICE_GROUP_IFR_IF1_MASK<< DEVICE_GROUP_IFR_R_IF1_BIT)
#define DEVICE_GROUP_IFR_R_IF1_DIS (DEVICE_GROUP_IFR_IF1_DIS << DEVICE_GROUP_IFR_R_IF1_BIT)
#define DEVICE_GROUP_IFR_R_IF1_ENA (DEVICE_GROUP_IFR_IF1_ENA << DEVICE_GROUP_IFR_R_IF1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF2_BIT ((uint16_t) 1U)

#define DEVICE_GROUP_IFR_IF2_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF2_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF2_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF2_MASK (DEVICE_GROUP_IFR_IF2_MASK<< DEVICE_GROUP_IFR_R_IF2_BIT)
#define DEVICE_GROUP_IFR_R_IF2_DIS (DEVICE_GROUP_IFR_IF2_DIS << DEVICE_GROUP_IFR_R_IF2_BIT)
#define DEVICE_GROUP_IFR_R_IF2_ENA (DEVICE_GROUP_IFR_IF2_ENA << DEVICE_GROUP_IFR_R_IF2_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF3_BIT ((uint16_t) 2U)

#define DEVICE_GROUP_IFR_IF3_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF3_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF3_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF3_MASK (DEVICE_GROUP_IFR_IF3_MASK<< DEVICE_GROUP_IFR_R_IF3_BIT)
#define DEVICE_GROUP_IFR_R_IF3_DIS (DEVICE_GROUP_IFR_IF3_DIS << DEVICE_GROUP_IFR_R_IF3_BIT)
#define DEVICE_GROUP_IFR_R_IF3_ENA (DEVICE_GROUP_IFR_IF3_ENA << DEVICE_GROUP_IFR_R_IF3_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF4_BIT ((uint16_t) 3U)

#define DEVICE_GROUP_IFR_IF4_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF4_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF4_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF4_MASK (DEVICE_GROUP_IFR_IF4_MASK<< DEVICE_GROUP_IFR_R_IF4_BIT)
#define DEVICE_GROUP_IFR_R_IF4_DIS (DEVICE_GROUP_IFR_IF4_DIS << DEVICE_GROUP_IFR_R_IF4_BIT)
#define DEVICE_GROUP_IFR_R_IF4_ENA (DEVICE_GROUP_IFR_IF4_ENA << DEVICE_GROUP_IFR_R_IF4_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF5_BIT ((uint16_t) 4U)

#define DEVICE_GROUP_IFR_IF5_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF5_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF5_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF5_MASK (DEVICE_GROUP_IFR_IF5_MASK<< DEVICE_GROUP_IFR_R_IF5_BIT)
#define DEVICE_GROUP_IFR_R_IF5_DIS (DEVICE_GROUP_IFR_IF5_DIS << DEVICE_GROUP_IFR_R_IF5_BIT)
#define DEVICE_GROUP_IFR_R_IF5_ENA (DEVICE_GROUP_IFR_IF5_ENA << DEVICE_GROUP_IFR_R_IF5_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF6_BIT ((uint16_t) 5U)

#define DEVICE_GROUP_IFR_IF6_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF6_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF6_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF6_MASK (DEVICE_GROUP_IFR_IF6_MASK<< DEVICE_GROUP_IFR_R_IF6_BIT)
#define DEVICE_GROUP_IFR_R_IF6_DIS (DEVICE_GROUP_IFR_IF6_DIS << DEVICE_GROUP_IFR_R_IF6_BIT)
#define DEVICE_GROUP_IFR_R_IF6_ENA (DEVICE_GROUP_IFR_IF6_ENA << DEVICE_GROUP_IFR_R_IF6_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF7_BIT ((uint16_t) 6U)

#define DEVICE_GROUP_IFR_IF7_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF7_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF7_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF7_MASK (DEVICE_GROUP_IFR_IF7_MASK<< DEVICE_GROUP_IFR_R_IF7_BIT)
#define DEVICE_GROUP_IFR_R_IF7_DIS (DEVICE_GROUP_IFR_IF7_DIS << DEVICE_GROUP_IFR_R_IF7_BIT)
#define DEVICE_GROUP_IFR_R_IF7_ENA (DEVICE_GROUP_IFR_IF7_ENA << DEVICE_GROUP_IFR_R_IF7_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP_IFR_R_IF8_BIT ((uint16_t) 7U)

#define DEVICE_GROUP_IFR_IF8_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP_IFR_IF8_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP_IFR_IF8_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP_IFR_R_IF8_MASK (DEVICE_GROUP_IFR_IF8_MASK<< DEVICE_GROUP_IFR_R_IF8_BIT)
#define DEVICE_GROUP_IFR_R_IF8_DIS (DEVICE_GROUP_IFR_IF8_DIS << DEVICE_GROUP_IFR_R_IF8_BIT)
#define DEVICE_GROUP_IFR_R_IF8_ENA (DEVICE_GROUP_IFR_IF8_ENA << DEVICE_GROUP_IFR_R_IF8_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP_H_ */
