/**
 *
 * @file DEVICE_RegisterDefines_GROUP5.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP5_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP5_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 DEVICEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP5_IER_R_SW1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP5_IER_SW1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_SW1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_SW1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_SW1_MASK (DEVICE_GROUP5_IER_SW1_MASK<< DEVICE_GROUP5_IER_R_SW1_BIT)
#define DEVICE_GROUP5_IER_R_SW1_DIS (DEVICE_GROUP5_IER_SW1_DIS << DEVICE_GROUP5_IER_R_SW1_BIT)
#define DEVICE_GROUP5_IER_R_SW1_ENA (DEVICE_GROUP5_IER_SW1_ENA << DEVICE_GROUP5_IER_R_SW1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED17_BIT ((uint16_t) 1U)

#define DEVICE_GROUP5_IER_RESERVED17_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED17_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED17_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED17_MASK (DEVICE_GROUP5_IER_RESERVED17_MASK<< DEVICE_GROUP5_IER_R_RESERVED17_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED17_DIS (DEVICE_GROUP5_IER_RESERVED17_DIS << DEVICE_GROUP5_IER_R_RESERVED17_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED17_ENA (DEVICE_GROUP5_IER_RESERVED17_ENA << DEVICE_GROUP5_IER_R_RESERVED17_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED18_BIT ((uint16_t) 2U)

#define DEVICE_GROUP5_IER_RESERVED18_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED18_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED18_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED18_MASK (DEVICE_GROUP5_IER_RESERVED18_MASK<< DEVICE_GROUP5_IER_R_RESERVED18_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED18_DIS (DEVICE_GROUP5_IER_RESERVED18_DIS << DEVICE_GROUP5_IER_R_RESERVED18_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED18_ENA (DEVICE_GROUP5_IER_RESERVED18_ENA << DEVICE_GROUP5_IER_R_RESERVED18_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED19_BIT ((uint16_t) 3U)

#define DEVICE_GROUP5_IER_RESERVED19_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED19_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED19_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED19_MASK (DEVICE_GROUP5_IER_RESERVED19_MASK<< DEVICE_GROUP5_IER_R_RESERVED19_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED19_DIS (DEVICE_GROUP5_IER_RESERVED19_DIS << DEVICE_GROUP5_IER_R_RESERVED19_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED19_ENA (DEVICE_GROUP5_IER_RESERVED19_ENA << DEVICE_GROUP5_IER_R_RESERVED19_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED20_BIT ((uint16_t) 4U)

#define DEVICE_GROUP5_IER_RESERVED20_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED20_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED20_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED20_MASK (DEVICE_GROUP5_IER_RESERVED20_MASK<< DEVICE_GROUP5_IER_R_RESERVED20_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED20_DIS (DEVICE_GROUP5_IER_RESERVED20_DIS << DEVICE_GROUP5_IER_R_RESERVED20_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED20_ENA (DEVICE_GROUP5_IER_RESERVED20_ENA << DEVICE_GROUP5_IER_R_RESERVED20_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED21_BIT ((uint16_t) 5U)

#define DEVICE_GROUP5_IER_RESERVED21_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED21_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED21_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED21_MASK (DEVICE_GROUP5_IER_RESERVED21_MASK<< DEVICE_GROUP5_IER_R_RESERVED21_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED21_DIS (DEVICE_GROUP5_IER_RESERVED21_DIS << DEVICE_GROUP5_IER_R_RESERVED21_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED21_ENA (DEVICE_GROUP5_IER_RESERVED21_ENA << DEVICE_GROUP5_IER_R_RESERVED21_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED22_BIT ((uint16_t) 6U)

#define DEVICE_GROUP5_IER_RESERVED22_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED22_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED22_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED22_MASK (DEVICE_GROUP5_IER_RESERVED22_MASK<< DEVICE_GROUP5_IER_R_RESERVED22_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED22_DIS (DEVICE_GROUP5_IER_RESERVED22_DIS << DEVICE_GROUP5_IER_R_RESERVED22_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED22_ENA (DEVICE_GROUP5_IER_RESERVED22_ENA << DEVICE_GROUP5_IER_R_RESERVED22_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IER_R_RESERVED23_BIT ((uint16_t) 7U)

#define DEVICE_GROUP5_IER_RESERVED23_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IER_RESERVED23_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IER_RESERVED23_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IER_R_RESERVED23_MASK (DEVICE_GROUP5_IER_RESERVED23_MASK<< DEVICE_GROUP5_IER_R_RESERVED23_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED23_DIS (DEVICE_GROUP5_IER_RESERVED23_DIS << DEVICE_GROUP5_IER_R_RESERVED23_BIT)
#define DEVICE_GROUP5_IER_R_RESERVED23_ENA (DEVICE_GROUP5_IER_RESERVED23_ENA << DEVICE_GROUP5_IER_R_RESERVED23_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 DEVICEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define DEVICE_GROUP5_IFR_R_SW1_BIT ((uint16_t) 0U)

#define DEVICE_GROUP5_IFR_SW1_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_SW1_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_SW1_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_SW1_MASK (DEVICE_GROUP5_IFR_SW1_MASK<< DEVICE_GROUP5_IFR_R_SW1_BIT)
#define DEVICE_GROUP5_IFR_R_SW1_DIS (DEVICE_GROUP5_IFR_SW1_DIS << DEVICE_GROUP5_IFR_R_SW1_BIT)
#define DEVICE_GROUP5_IFR_R_SW1_ENA (DEVICE_GROUP5_IFR_SW1_ENA << DEVICE_GROUP5_IFR_R_SW1_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED17_BIT ((uint16_t) 1U)

#define DEVICE_GROUP5_IFR_RESERVED17_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED17_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED17_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED17_MASK (DEVICE_GROUP5_IFR_RESERVED17_MASK<< DEVICE_GROUP5_IFR_R_RESERVED17_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED17_DIS (DEVICE_GROUP5_IFR_RESERVED17_DIS << DEVICE_GROUP5_IFR_R_RESERVED17_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED17_ENA (DEVICE_GROUP5_IFR_RESERVED17_ENA << DEVICE_GROUP5_IFR_R_RESERVED17_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED18_BIT ((uint16_t) 2U)

#define DEVICE_GROUP5_IFR_RESERVED18_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED18_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED18_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED18_MASK (DEVICE_GROUP5_IFR_RESERVED18_MASK<< DEVICE_GROUP5_IFR_R_RESERVED18_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED18_DIS (DEVICE_GROUP5_IFR_RESERVED18_DIS << DEVICE_GROUP5_IFR_R_RESERVED18_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED18_ENA (DEVICE_GROUP5_IFR_RESERVED18_ENA << DEVICE_GROUP5_IFR_R_RESERVED18_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED19_BIT ((uint16_t) 3U)

#define DEVICE_GROUP5_IFR_RESERVED19_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED19_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED19_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED19_MASK (DEVICE_GROUP5_IFR_RESERVED19_MASK<< DEVICE_GROUP5_IFR_R_RESERVED19_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED19_DIS (DEVICE_GROUP5_IFR_RESERVED19_DIS << DEVICE_GROUP5_IFR_R_RESERVED19_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED19_ENA (DEVICE_GROUP5_IFR_RESERVED19_ENA << DEVICE_GROUP5_IFR_R_RESERVED19_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED20_BIT ((uint16_t) 4U)

#define DEVICE_GROUP5_IFR_RESERVED20_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED20_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED20_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED20_MASK (DEVICE_GROUP5_IFR_RESERVED20_MASK<< DEVICE_GROUP5_IFR_R_RESERVED20_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED20_DIS (DEVICE_GROUP5_IFR_RESERVED20_DIS << DEVICE_GROUP5_IFR_R_RESERVED20_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED20_ENA (DEVICE_GROUP5_IFR_RESERVED20_ENA << DEVICE_GROUP5_IFR_R_RESERVED20_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED21_BIT ((uint16_t) 5U)

#define DEVICE_GROUP5_IFR_RESERVED21_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED21_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED21_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED21_MASK (DEVICE_GROUP5_IFR_RESERVED21_MASK<< DEVICE_GROUP5_IFR_R_RESERVED21_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED21_DIS (DEVICE_GROUP5_IFR_RESERVED21_DIS << DEVICE_GROUP5_IFR_R_RESERVED21_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED21_ENA (DEVICE_GROUP5_IFR_RESERVED21_ENA << DEVICE_GROUP5_IFR_R_RESERVED21_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED22_BIT ((uint16_t) 6U)

#define DEVICE_GROUP5_IFR_RESERVED22_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED22_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED22_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED22_MASK (DEVICE_GROUP5_IFR_RESERVED22_MASK<< DEVICE_GROUP5_IFR_R_RESERVED22_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED22_DIS (DEVICE_GROUP5_IFR_RESERVED22_DIS << DEVICE_GROUP5_IFR_R_RESERVED22_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED22_ENA (DEVICE_GROUP5_IFR_RESERVED22_ENA << DEVICE_GROUP5_IFR_R_RESERVED22_BIT)
/*-----------*/

/*-----------*/
#define DEVICE_GROUP5_IFR_R_RESERVED23_BIT ((uint16_t) 7U)

#define DEVICE_GROUP5_IFR_RESERVED23_MASK ((uint16_t) 0x01U)
#define DEVICE_GROUP5_IFR_RESERVED23_DIS ((uint16_t) 0x00U)
#define DEVICE_GROUP5_IFR_RESERVED23_ENA ((uint16_t) 0x01U)

#define DEVICE_GROUP5_IFR_R_RESERVED23_MASK (DEVICE_GROUP5_IFR_RESERVED23_MASK<< DEVICE_GROUP5_IFR_R_RESERVED23_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED23_DIS (DEVICE_GROUP5_IFR_RESERVED23_DIS << DEVICE_GROUP5_IFR_R_RESERVED23_BIT)
#define DEVICE_GROUP5_IFR_R_RESERVED23_ENA (DEVICE_GROUP5_IFR_RESERVED23_ENA << DEVICE_GROUP5_IFR_R_RESERVED23_BIT)
/*-----------*/

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_REGISTERDEFINES_XHEADER_DEVICE_REGISTERDEFINES_GROUP5_H_ */
