/**
 *
 * @file SYSCTL_RegisterAddress.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 27 jun. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 27 jun. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_XHEADER_SYSCTL_REGISTERADDRESS_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_XHEADER_SYSCTL_REGISTERADDRESS_H_

#define SYSCTL_BASE (0x0CE0U)
#define SYSCTL_VECTOR_BASE (0x0D00U)

#define SYSCTL_GROUP1_BASE (SYSCTL_BASE + 0x0002U)
#define SYSCTL_GROUP2_BASE (SYSCTL_BASE + 0x0004U)
#define SYSCTL_GROUP3_BASE (SYSCTL_BASE + 0x0006U)
#define SYSCTL_GROUP4_BASE (SYSCTL_BASE + 0x0008U)
#define SYSCTL_GROUP5_BASE (SYSCTL_BASE + 0x000AU)
#define SYSCTL_GROUP6_BASE (SYSCTL_BASE + 0x000CU)
#define SYSCTL_GROUP7_BASE (SYSCTL_BASE + 0x000EU)
#define SYSCTL_GROUP8_BASE (SYSCTL_BASE + 0x0010U)
#define SYSCTL_GROUP9_BASE (SYSCTL_BASE + 0x0012U)
#define SYSCTL_GROUP10_BASE (SYSCTL_BASE + 0x0014U)
#define SYSCTL_GROUP11_BASE (SYSCTL_BASE + 0x0016U)
#define SYSCTL_GROUP12_BASE (SYSCTL_BASE + 0x0018U)


#define SYSCTL_GROUP1_OFFSET (0x0002U)
#define SYSCTL_GROUP2_OFFSET (0x0004U)
#define SYSCTL_GROUP3_OFFSET (0x0006U)
#define SYSCTL_GROUP4_OFFSET (0x0008U)
#define SYSCTL_GROUP5_OFFSET (0x000AU)
#define SYSCTL_GROUP6_OFFSET (0x000CU)
#define SYSCTL_GROUP7_OFFSET (0x000EU)
#define SYSCTL_GROUP8_OFFSET (0x0010U)
#define SYSCTL_GROUP9_OFFSET (0x0012U)
#define SYSCTL_GROUP10_OFFSET (0x0014U)
#define SYSCTL_GROUP11_OFFSET (0x0016U)
#define SYSCTL_GROUP12_OFFSET (0x0018U)

#define SYSCTL_CTRL_OFFSET (0x0000U)
#define SYSCTL_ACK_OFFSET (0x0001U)

#define SYSCTL_IER_OFFSET (0x0000U)
#define SYSCTL_IFR_OFFSET (0x0001U)

#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_XHEADER_SYSCTL_REGISTERADDRESS_H_ */
