/**
 *
 * @file PIE_RegisterDefines_GROUP4.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP4_H_
#define DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP4_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 PIEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define PIE_GROUP4_IER_R_ECAP1_BIT ((uint16_t) 0U)

#define PIE_GROUP4_IER_ECAP1_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_ECAP1_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_ECAP1_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_ECAP1_MASK (PIE_GROUP4_IER_ECAP1_MASK<< PIE_GROUP4_IER_R_ECAP1_BIT)
#define PIE_GROUP4_IER_R_ECAP1_DIS (PIE_GROUP4_IER_ECAP1_DIS << PIE_GROUP4_IER_R_ECAP1_BIT)
#define PIE_GROUP4_IER_R_ECAP1_ENA (PIE_GROUP4_IER_ECAP1_ENA << PIE_GROUP4_IER_R_ECAP1_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED10_BIT ((uint16_t) 1U)

#define PIE_GROUP4_IER_RESERVED10_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED10_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED10_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED10_MASK (PIE_GROUP4_IER_RESERVED10_MASK<< PIE_GROUP4_IER_R_RESERVED10_BIT)
#define PIE_GROUP4_IER_R_RESERVED10_DIS (PIE_GROUP4_IER_RESERVED10_DIS << PIE_GROUP4_IER_R_RESERVED10_BIT)
#define PIE_GROUP4_IER_R_RESERVED10_ENA (PIE_GROUP4_IER_RESERVED10_ENA << PIE_GROUP4_IER_R_RESERVED10_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED11_BIT ((uint16_t) 2U)

#define PIE_GROUP4_IER_RESERVED11_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED11_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED11_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED11_MASK (PIE_GROUP4_IER_RESERVED11_MASK<< PIE_GROUP4_IER_R_RESERVED11_BIT)
#define PIE_GROUP4_IER_R_RESERVED11_DIS (PIE_GROUP4_IER_RESERVED11_DIS << PIE_GROUP4_IER_R_RESERVED11_BIT)
#define PIE_GROUP4_IER_R_RESERVED11_ENA (PIE_GROUP4_IER_RESERVED11_ENA << PIE_GROUP4_IER_R_RESERVED11_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED12_BIT ((uint16_t) 3U)

#define PIE_GROUP4_IER_RESERVED12_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED12_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED12_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED12_MASK (PIE_GROUP4_IER_RESERVED12_MASK<< PIE_GROUP4_IER_R_RESERVED12_BIT)
#define PIE_GROUP4_IER_R_RESERVED12_DIS (PIE_GROUP4_IER_RESERVED12_DIS << PIE_GROUP4_IER_R_RESERVED12_BIT)
#define PIE_GROUP4_IER_R_RESERVED12_ENA (PIE_GROUP4_IER_RESERVED12_ENA << PIE_GROUP4_IER_R_RESERVED12_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED13_BIT ((uint16_t) 4U)

#define PIE_GROUP4_IER_RESERVED13_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED13_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED13_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED13_MASK (PIE_GROUP4_IER_RESERVED13_MASK<< PIE_GROUP4_IER_R_RESERVED13_BIT)
#define PIE_GROUP4_IER_R_RESERVED13_DIS (PIE_GROUP4_IER_RESERVED13_DIS << PIE_GROUP4_IER_R_RESERVED13_BIT)
#define PIE_GROUP4_IER_R_RESERVED13_ENA (PIE_GROUP4_IER_RESERVED13_ENA << PIE_GROUP4_IER_R_RESERVED13_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED14_BIT ((uint16_t) 5U)

#define PIE_GROUP4_IER_RESERVED14_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED14_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED14_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED14_MASK (PIE_GROUP4_IER_RESERVED14_MASK<< PIE_GROUP4_IER_R_RESERVED14_BIT)
#define PIE_GROUP4_IER_R_RESERVED14_DIS (PIE_GROUP4_IER_RESERVED14_DIS << PIE_GROUP4_IER_R_RESERVED14_BIT)
#define PIE_GROUP4_IER_R_RESERVED14_ENA (PIE_GROUP4_IER_RESERVED14_ENA << PIE_GROUP4_IER_R_RESERVED14_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED15_BIT ((uint16_t) 6U)

#define PIE_GROUP4_IER_RESERVED15_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED15_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED15_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED15_MASK (PIE_GROUP4_IER_RESERVED15_MASK<< PIE_GROUP4_IER_R_RESERVED15_BIT)
#define PIE_GROUP4_IER_R_RESERVED15_DIS (PIE_GROUP4_IER_RESERVED15_DIS << PIE_GROUP4_IER_R_RESERVED15_BIT)
#define PIE_GROUP4_IER_R_RESERVED15_ENA (PIE_GROUP4_IER_RESERVED15_ENA << PIE_GROUP4_IER_R_RESERVED15_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IER_R_RESERVED16_BIT ((uint16_t) 7U)

#define PIE_GROUP4_IER_RESERVED16_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IER_RESERVED16_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IER_RESERVED16_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IER_R_RESERVED16_MASK (PIE_GROUP4_IER_RESERVED16_MASK<< PIE_GROUP4_IER_R_RESERVED16_BIT)
#define PIE_GROUP4_IER_R_RESERVED16_DIS (PIE_GROUP4_IER_RESERVED16_DIS << PIE_GROUP4_IER_R_RESERVED16_BIT)
#define PIE_GROUP4_IER_R_RESERVED16_ENA (PIE_GROUP4_IER_RESERVED16_ENA << PIE_GROUP4_IER_R_RESERVED16_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 PIEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define PIE_GROUP4_IFR_R_ECAP1_BIT ((uint16_t) 0U)

#define PIE_GROUP4_IFR_ECAP1_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_ECAP1_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_ECAP1_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_ECAP1_MASK (PIE_GROUP4_IFR_ECAP1_MASK<< PIE_GROUP4_IFR_R_ECAP1_BIT)
#define PIE_GROUP4_IFR_R_ECAP1_DIS (PIE_GROUP4_IFR_ECAP1_DIS << PIE_GROUP4_IFR_R_ECAP1_BIT)
#define PIE_GROUP4_IFR_R_ECAP1_ENA (PIE_GROUP4_IFR_ECAP1_ENA << PIE_GROUP4_IFR_R_ECAP1_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED10_BIT ((uint16_t) 1U)

#define PIE_GROUP4_IFR_RESERVED10_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED10_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED10_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED10_MASK (PIE_GROUP4_IFR_RESERVED10_MASK<< PIE_GROUP4_IFR_R_RESERVED10_BIT)
#define PIE_GROUP4_IFR_R_RESERVED10_DIS (PIE_GROUP4_IFR_RESERVED10_DIS << PIE_GROUP4_IFR_R_RESERVED10_BIT)
#define PIE_GROUP4_IFR_R_RESERVED10_ENA (PIE_GROUP4_IFR_RESERVED10_ENA << PIE_GROUP4_IFR_R_RESERVED10_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED11_BIT ((uint16_t) 2U)

#define PIE_GROUP4_IFR_RESERVED11_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED11_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED11_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED11_MASK (PIE_GROUP4_IFR_RESERVED11_MASK<< PIE_GROUP4_IFR_R_RESERVED11_BIT)
#define PIE_GROUP4_IFR_R_RESERVED11_DIS (PIE_GROUP4_IFR_RESERVED11_DIS << PIE_GROUP4_IFR_R_RESERVED11_BIT)
#define PIE_GROUP4_IFR_R_RESERVED11_ENA (PIE_GROUP4_IFR_RESERVED11_ENA << PIE_GROUP4_IFR_R_RESERVED11_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED12_BIT ((uint16_t) 3U)

#define PIE_GROUP4_IFR_RESERVED12_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED12_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED12_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED12_MASK (PIE_GROUP4_IFR_RESERVED12_MASK<< PIE_GROUP4_IFR_R_RESERVED12_BIT)
#define PIE_GROUP4_IFR_R_RESERVED12_DIS (PIE_GROUP4_IFR_RESERVED12_DIS << PIE_GROUP4_IFR_R_RESERVED12_BIT)
#define PIE_GROUP4_IFR_R_RESERVED12_ENA (PIE_GROUP4_IFR_RESERVED12_ENA << PIE_GROUP4_IFR_R_RESERVED12_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED13_BIT ((uint16_t) 4U)

#define PIE_GROUP4_IFR_RESERVED13_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED13_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED13_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED13_MASK (PIE_GROUP4_IFR_RESERVED13_MASK<< PIE_GROUP4_IFR_R_RESERVED13_BIT)
#define PIE_GROUP4_IFR_R_RESERVED13_DIS (PIE_GROUP4_IFR_RESERVED13_DIS << PIE_GROUP4_IFR_R_RESERVED13_BIT)
#define PIE_GROUP4_IFR_R_RESERVED13_ENA (PIE_GROUP4_IFR_RESERVED13_ENA << PIE_GROUP4_IFR_R_RESERVED13_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED14_BIT ((uint16_t) 5U)

#define PIE_GROUP4_IFR_RESERVED14_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED14_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED14_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED14_MASK (PIE_GROUP4_IFR_RESERVED14_MASK<< PIE_GROUP4_IFR_R_RESERVED14_BIT)
#define PIE_GROUP4_IFR_R_RESERVED14_DIS (PIE_GROUP4_IFR_RESERVED14_DIS << PIE_GROUP4_IFR_R_RESERVED14_BIT)
#define PIE_GROUP4_IFR_R_RESERVED14_ENA (PIE_GROUP4_IFR_RESERVED14_ENA << PIE_GROUP4_IFR_R_RESERVED14_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED15_BIT ((uint16_t) 6U)

#define PIE_GROUP4_IFR_RESERVED15_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED15_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED15_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED15_MASK (PIE_GROUP4_IFR_RESERVED15_MASK<< PIE_GROUP4_IFR_R_RESERVED15_BIT)
#define PIE_GROUP4_IFR_R_RESERVED15_DIS (PIE_GROUP4_IFR_RESERVED15_DIS << PIE_GROUP4_IFR_R_RESERVED15_BIT)
#define PIE_GROUP4_IFR_R_RESERVED15_ENA (PIE_GROUP4_IFR_RESERVED15_ENA << PIE_GROUP4_IFR_R_RESERVED15_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP4_IFR_R_RESERVED16_BIT ((uint16_t) 7U)

#define PIE_GROUP4_IFR_RESERVED16_MASK ((uint16_t) 0x01U)
#define PIE_GROUP4_IFR_RESERVED16_DIS ((uint16_t) 0x00U)
#define PIE_GROUP4_IFR_RESERVED16_ENA ((uint16_t) 0x01U)

#define PIE_GROUP4_IFR_R_RESERVED16_MASK (PIE_GROUP4_IFR_RESERVED16_MASK<< PIE_GROUP4_IFR_R_RESERVED16_BIT)
#define PIE_GROUP4_IFR_R_RESERVED16_DIS (PIE_GROUP4_IFR_RESERVED16_DIS << PIE_GROUP4_IFR_R_RESERVED16_BIT)
#define PIE_GROUP4_IFR_R_RESERVED16_ENA (PIE_GROUP4_IFR_RESERVED16_ENA << PIE_GROUP4_IFR_R_RESERVED16_BIT)
/*-----------*/

#endif /* DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP4_H_ */
