/**
 *
 * @file PIE_RegisterDefines_GROUP6.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP6_H_
#define DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP6_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 PIEIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define PIE_GROUP6_IER_R_SPIA_RX_BIT ((uint16_t) 0U)

#define PIE_GROUP6_IER_SPIA_RX_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_SPIA_RX_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_SPIA_RX_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_SPIA_RX_MASK (PIE_GROUP6_IER_SPIA_RX_MASK<< PIE_GROUP6_IER_R_SPIA_RX_BIT)
#define PIE_GROUP6_IER_R_SPIA_RX_DIS (PIE_GROUP6_IER_SPIA_RX_DIS << PIE_GROUP6_IER_R_SPIA_RX_BIT)
#define PIE_GROUP6_IER_R_SPIA_RX_ENA (PIE_GROUP6_IER_SPIA_RX_ENA << PIE_GROUP6_IER_R_SPIA_RX_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_SPIA_TX_BIT ((uint16_t) 1U)

#define PIE_GROUP6_IER_SPIA_TX_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_SPIA_TX_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_SPIA_TX_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_SPIA_TX_MASK (PIE_GROUP6_IER_SPIA_TX_MASK<< PIE_GROUP6_IER_R_SPIA_TX_BIT)
#define PIE_GROUP6_IER_R_SPIA_TX_DIS (PIE_GROUP6_IER_SPIA_TX_DIS << PIE_GROUP6_IER_R_SPIA_TX_BIT)
#define PIE_GROUP6_IER_R_SPIA_TX_ENA (PIE_GROUP6_IER_SPIA_TX_ENA << PIE_GROUP6_IER_R_SPIA_TX_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED24_BIT ((uint16_t) 2U)

#define PIE_GROUP6_IER_RESERVED24_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED24_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED24_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED24_MASK (PIE_GROUP6_IER_RESERVED24_MASK<< PIE_GROUP6_IER_R_RESERVED24_BIT)
#define PIE_GROUP6_IER_R_RESERVED24_DIS (PIE_GROUP6_IER_RESERVED24_DIS << PIE_GROUP6_IER_R_RESERVED24_BIT)
#define PIE_GROUP6_IER_R_RESERVED24_ENA (PIE_GROUP6_IER_RESERVED24_ENA << PIE_GROUP6_IER_R_RESERVED24_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED25_BIT ((uint16_t) 3U)

#define PIE_GROUP6_IER_RESERVED25_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED25_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED25_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED25_MASK (PIE_GROUP6_IER_RESERVED25_MASK<< PIE_GROUP6_IER_R_RESERVED25_BIT)
#define PIE_GROUP6_IER_R_RESERVED25_DIS (PIE_GROUP6_IER_RESERVED25_DIS << PIE_GROUP6_IER_R_RESERVED25_BIT)
#define PIE_GROUP6_IER_R_RESERVED25_ENA (PIE_GROUP6_IER_RESERVED25_ENA << PIE_GROUP6_IER_R_RESERVED25_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED26_BIT ((uint16_t) 4U)

#define PIE_GROUP6_IER_RESERVED26_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED26_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED26_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED26_MASK (PIE_GROUP6_IER_RESERVED26_MASK<< PIE_GROUP6_IER_R_RESERVED26_BIT)
#define PIE_GROUP6_IER_R_RESERVED26_DIS (PIE_GROUP6_IER_RESERVED26_DIS << PIE_GROUP6_IER_R_RESERVED26_BIT)
#define PIE_GROUP6_IER_R_RESERVED26_ENA (PIE_GROUP6_IER_RESERVED26_ENA << PIE_GROUP6_IER_R_RESERVED26_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED27_BIT ((uint16_t) 5U)

#define PIE_GROUP6_IER_RESERVED27_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED27_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED27_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED27_MASK (PIE_GROUP6_IER_RESERVED27_MASK<< PIE_GROUP6_IER_R_RESERVED27_BIT)
#define PIE_GROUP6_IER_R_RESERVED27_DIS (PIE_GROUP6_IER_RESERVED27_DIS << PIE_GROUP6_IER_R_RESERVED27_BIT)
#define PIE_GROUP6_IER_R_RESERVED27_ENA (PIE_GROUP6_IER_RESERVED27_ENA << PIE_GROUP6_IER_R_RESERVED27_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED28_BIT ((uint16_t) 6U)

#define PIE_GROUP6_IER_RESERVED28_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED28_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED28_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED28_MASK (PIE_GROUP6_IER_RESERVED28_MASK<< PIE_GROUP6_IER_R_RESERVED28_BIT)
#define PIE_GROUP6_IER_R_RESERVED28_DIS (PIE_GROUP6_IER_RESERVED28_DIS << PIE_GROUP6_IER_R_RESERVED28_BIT)
#define PIE_GROUP6_IER_R_RESERVED28_ENA (PIE_GROUP6_IER_RESERVED28_ENA << PIE_GROUP6_IER_R_RESERVED28_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IER_R_RESERVED29_BIT ((uint16_t) 7U)

#define PIE_GROUP6_IER_RESERVED29_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IER_RESERVED29_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IER_RESERVED29_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IER_R_RESERVED29_MASK (PIE_GROUP6_IER_RESERVED29_MASK<< PIE_GROUP6_IER_R_RESERVED29_BIT)
#define PIE_GROUP6_IER_R_RESERVED29_DIS (PIE_GROUP6_IER_RESERVED29_DIS << PIE_GROUP6_IER_R_RESERVED29_BIT)
#define PIE_GROUP6_IER_R_RESERVED29_ENA (PIE_GROUP6_IER_RESERVED29_ENA << PIE_GROUP6_IER_R_RESERVED29_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 PIEIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define PIE_GROUP6_IFR_R_SPIA_RX_BIT ((uint16_t) 0U)

#define PIE_GROUP6_IFR_SPIA_RX_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_SPIA_RX_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_SPIA_RX_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_SPIA_RX_MASK (PIE_GROUP6_IFR_SPIA_RX_MASK<< PIE_GROUP6_IFR_R_SPIA_RX_BIT)
#define PIE_GROUP6_IFR_R_SPIA_RX_DIS (PIE_GROUP6_IFR_SPIA_RX_DIS << PIE_GROUP6_IFR_R_SPIA_RX_BIT)
#define PIE_GROUP6_IFR_R_SPIA_RX_ENA (PIE_GROUP6_IFR_SPIA_RX_ENA << PIE_GROUP6_IFR_R_SPIA_RX_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_SPIA_TX_BIT ((uint16_t) 1U)

#define PIE_GROUP6_IFR_SPIA_TX_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_SPIA_TX_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_SPIA_TX_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_SPIA_TX_MASK (PIE_GROUP6_IFR_SPIA_TX_MASK<< PIE_GROUP6_IFR_R_SPIA_TX_BIT)
#define PIE_GROUP6_IFR_R_SPIA_TX_DIS (PIE_GROUP6_IFR_SPIA_TX_DIS << PIE_GROUP6_IFR_R_SPIA_TX_BIT)
#define PIE_GROUP6_IFR_R_SPIA_TX_ENA (PIE_GROUP6_IFR_SPIA_TX_ENA << PIE_GROUP6_IFR_R_SPIA_TX_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED24_BIT ((uint16_t) 2U)

#define PIE_GROUP6_IFR_RESERVED24_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED24_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED24_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED24_MASK (PIE_GROUP6_IFR_RESERVED24_MASK<< PIE_GROUP6_IFR_R_RESERVED24_BIT)
#define PIE_GROUP6_IFR_R_RESERVED24_DIS (PIE_GROUP6_IFR_RESERVED24_DIS << PIE_GROUP6_IFR_R_RESERVED24_BIT)
#define PIE_GROUP6_IFR_R_RESERVED24_ENA (PIE_GROUP6_IFR_RESERVED24_ENA << PIE_GROUP6_IFR_R_RESERVED24_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED25_BIT ((uint16_t) 3U)

#define PIE_GROUP6_IFR_RESERVED25_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED25_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED25_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED25_MASK (PIE_GROUP6_IFR_RESERVED25_MASK<< PIE_GROUP6_IFR_R_RESERVED25_BIT)
#define PIE_GROUP6_IFR_R_RESERVED25_DIS (PIE_GROUP6_IFR_RESERVED25_DIS << PIE_GROUP6_IFR_R_RESERVED25_BIT)
#define PIE_GROUP6_IFR_R_RESERVED25_ENA (PIE_GROUP6_IFR_RESERVED25_ENA << PIE_GROUP6_IFR_R_RESERVED25_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED26_BIT ((uint16_t) 4U)

#define PIE_GROUP6_IFR_RESERVED26_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED26_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED26_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED26_MASK (PIE_GROUP6_IFR_RESERVED26_MASK<< PIE_GROUP6_IFR_R_RESERVED26_BIT)
#define PIE_GROUP6_IFR_R_RESERVED26_DIS (PIE_GROUP6_IFR_RESERVED26_DIS << PIE_GROUP6_IFR_R_RESERVED26_BIT)
#define PIE_GROUP6_IFR_R_RESERVED26_ENA (PIE_GROUP6_IFR_RESERVED26_ENA << PIE_GROUP6_IFR_R_RESERVED26_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED27_BIT ((uint16_t) 5U)

#define PIE_GROUP6_IFR_RESERVED27_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED27_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED27_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED27_MASK (PIE_GROUP6_IFR_RESERVED27_MASK<< PIE_GROUP6_IFR_R_RESERVED27_BIT)
#define PIE_GROUP6_IFR_R_RESERVED27_DIS (PIE_GROUP6_IFR_RESERVED27_DIS << PIE_GROUP6_IFR_R_RESERVED27_BIT)
#define PIE_GROUP6_IFR_R_RESERVED27_ENA (PIE_GROUP6_IFR_RESERVED27_ENA << PIE_GROUP6_IFR_R_RESERVED27_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED28_BIT ((uint16_t) 6U)

#define PIE_GROUP6_IFR_RESERVED28_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED28_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED28_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED28_MASK (PIE_GROUP6_IFR_RESERVED28_MASK<< PIE_GROUP6_IFR_R_RESERVED28_BIT)
#define PIE_GROUP6_IFR_R_RESERVED28_DIS (PIE_GROUP6_IFR_RESERVED28_DIS << PIE_GROUP6_IFR_R_RESERVED28_BIT)
#define PIE_GROUP6_IFR_R_RESERVED28_ENA (PIE_GROUP6_IFR_RESERVED28_ENA << PIE_GROUP6_IFR_R_RESERVED28_BIT)
/*-----------*/

/*-----------*/
#define PIE_GROUP6_IFR_R_RESERVED29_BIT ((uint16_t) 7U)

#define PIE_GROUP6_IFR_RESERVED29_MASK ((uint16_t) 0x01U)
#define PIE_GROUP6_IFR_RESERVED29_DIS ((uint16_t) 0x00U)
#define PIE_GROUP6_IFR_RESERVED29_ENA ((uint16_t) 0x01U)

#define PIE_GROUP6_IFR_R_RESERVED29_MASK (PIE_GROUP6_IFR_RESERVED29_MASK<< PIE_GROUP6_IFR_R_RESERVED29_BIT)
#define PIE_GROUP6_IFR_R_RESERVED29_DIS (PIE_GROUP6_IFR_RESERVED29_DIS << PIE_GROUP6_IFR_R_RESERVED29_BIT)
#define PIE_GROUP6_IFR_R_RESERVED29_ENA (PIE_GROUP6_IFR_RESERVED29_ENA << PIE_GROUP6_IFR_R_RESERVED29_BIT)
/*-----------*/

#endif /* DRIVERLIB_PIE_PERIPHERAL_REGISTERDEFINES_XHEADER_PIE_REGISTERDEFINES_GROUP6_H_ */
