/**
 *
 * @file DEVICE_RegisterAddress.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 27 jun. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 27 jun. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_DEVICE_PERIPHERAL_XHEADER_DEVICE_REGISTERADDRESS_H_
#define DRIVERLIB_DEVICE_PERIPHERAL_XHEADER_DEVICE_REGISTERADDRESS_H_

#define DEVICE_BASE (0x0CE0U)
#define DEVICE_VECTOR_BASE (0x0D00U)

#define DEVICE_GROUP1_BASE (DEVICE_BASE + 0x0002U)
#define DEVICE_GROUP2_BASE (DEVICE_BASE + 0x0004U)
#define DEVICE_GROUP3_BASE (DEVICE_BASE + 0x0006U)
#define DEVICE_GROUP4_BASE (DEVICE_BASE + 0x0008U)
#define DEVICE_GROUP5_BASE (DEVICE_BASE + 0x000AU)
#define DEVICE_GROUP6_BASE (DEVICE_BASE + 0x000CU)
#define DEVICE_GROUP7_BASE (DEVICE_BASE + 0x000EU)
#define DEVICE_GROUP8_BASE (DEVICE_BASE + 0x0010U)
#define DEVICE_GROUP9_BASE (DEVICE_BASE + 0x0012U)
#define DEVICE_GROUP10_BASE (DEVICE_BASE + 0x0014U)
#define DEVICE_GROUP11_BASE (DEVICE_BASE + 0x0016U)
#define DEVICE_GROUP12_BASE (DEVICE_BASE + 0x0018U)


#define DEVICE_GROUP1_OFFSET (0x0002U)
#define DEVICE_GROUP2_OFFSET (0x0004U)
#define DEVICE_GROUP3_OFFSET (0x0006U)
#define DEVICE_GROUP4_OFFSET (0x0008U)
#define DEVICE_GROUP5_OFFSET (0x000AU)
#define DEVICE_GROUP6_OFFSET (0x000CU)
#define DEVICE_GROUP7_OFFSET (0x000EU)
#define DEVICE_GROUP8_OFFSET (0x0010U)
#define DEVICE_GROUP9_OFFSET (0x0012U)
#define DEVICE_GROUP10_OFFSET (0x0014U)
#define DEVICE_GROUP11_OFFSET (0x0016U)
#define DEVICE_GROUP12_OFFSET (0x0018U)

#define DEVICE_CTRL_OFFSET (0x0000U)
#define DEVICE_ACK_OFFSET (0x0001U)

#define DEVICE_IER_OFFSET (0x0000U)
#define DEVICE_IFR_OFFSET (0x0001U)

#endif /* DRIVERLIB_DEVICE_PERIPHERAL_XHEADER_DEVICE_REGISTERADDRESS_H_ */
