/**
 *
 * @file FLASH_RegisterDefines_GROUP5.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP5_H_
#define DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP5_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 FLASHIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP5_IER_R_SW1_BIT ((uint16_t) 0U)

#define FLASH_GROUP5_IER_SW1_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_SW1_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_SW1_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_SW1_MASK (FLASH_GROUP5_IER_SW1_MASK<< FLASH_GROUP5_IER_R_SW1_BIT)
#define FLASH_GROUP5_IER_R_SW1_DIS (FLASH_GROUP5_IER_SW1_DIS << FLASH_GROUP5_IER_R_SW1_BIT)
#define FLASH_GROUP5_IER_R_SW1_ENA (FLASH_GROUP5_IER_SW1_ENA << FLASH_GROUP5_IER_R_SW1_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED17_BIT ((uint16_t) 1U)

#define FLASH_GROUP5_IER_RESERVED17_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED17_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED17_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED17_MASK (FLASH_GROUP5_IER_RESERVED17_MASK<< FLASH_GROUP5_IER_R_RESERVED17_BIT)
#define FLASH_GROUP5_IER_R_RESERVED17_DIS (FLASH_GROUP5_IER_RESERVED17_DIS << FLASH_GROUP5_IER_R_RESERVED17_BIT)
#define FLASH_GROUP5_IER_R_RESERVED17_ENA (FLASH_GROUP5_IER_RESERVED17_ENA << FLASH_GROUP5_IER_R_RESERVED17_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED18_BIT ((uint16_t) 2U)

#define FLASH_GROUP5_IER_RESERVED18_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED18_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED18_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED18_MASK (FLASH_GROUP5_IER_RESERVED18_MASK<< FLASH_GROUP5_IER_R_RESERVED18_BIT)
#define FLASH_GROUP5_IER_R_RESERVED18_DIS (FLASH_GROUP5_IER_RESERVED18_DIS << FLASH_GROUP5_IER_R_RESERVED18_BIT)
#define FLASH_GROUP5_IER_R_RESERVED18_ENA (FLASH_GROUP5_IER_RESERVED18_ENA << FLASH_GROUP5_IER_R_RESERVED18_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED19_BIT ((uint16_t) 3U)

#define FLASH_GROUP5_IER_RESERVED19_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED19_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED19_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED19_MASK (FLASH_GROUP5_IER_RESERVED19_MASK<< FLASH_GROUP5_IER_R_RESERVED19_BIT)
#define FLASH_GROUP5_IER_R_RESERVED19_DIS (FLASH_GROUP5_IER_RESERVED19_DIS << FLASH_GROUP5_IER_R_RESERVED19_BIT)
#define FLASH_GROUP5_IER_R_RESERVED19_ENA (FLASH_GROUP5_IER_RESERVED19_ENA << FLASH_GROUP5_IER_R_RESERVED19_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED20_BIT ((uint16_t) 4U)

#define FLASH_GROUP5_IER_RESERVED20_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED20_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED20_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED20_MASK (FLASH_GROUP5_IER_RESERVED20_MASK<< FLASH_GROUP5_IER_R_RESERVED20_BIT)
#define FLASH_GROUP5_IER_R_RESERVED20_DIS (FLASH_GROUP5_IER_RESERVED20_DIS << FLASH_GROUP5_IER_R_RESERVED20_BIT)
#define FLASH_GROUP5_IER_R_RESERVED20_ENA (FLASH_GROUP5_IER_RESERVED20_ENA << FLASH_GROUP5_IER_R_RESERVED20_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED21_BIT ((uint16_t) 5U)

#define FLASH_GROUP5_IER_RESERVED21_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED21_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED21_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED21_MASK (FLASH_GROUP5_IER_RESERVED21_MASK<< FLASH_GROUP5_IER_R_RESERVED21_BIT)
#define FLASH_GROUP5_IER_R_RESERVED21_DIS (FLASH_GROUP5_IER_RESERVED21_DIS << FLASH_GROUP5_IER_R_RESERVED21_BIT)
#define FLASH_GROUP5_IER_R_RESERVED21_ENA (FLASH_GROUP5_IER_RESERVED21_ENA << FLASH_GROUP5_IER_R_RESERVED21_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED22_BIT ((uint16_t) 6U)

#define FLASH_GROUP5_IER_RESERVED22_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED22_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED22_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED22_MASK (FLASH_GROUP5_IER_RESERVED22_MASK<< FLASH_GROUP5_IER_R_RESERVED22_BIT)
#define FLASH_GROUP5_IER_R_RESERVED22_DIS (FLASH_GROUP5_IER_RESERVED22_DIS << FLASH_GROUP5_IER_R_RESERVED22_BIT)
#define FLASH_GROUP5_IER_R_RESERVED22_ENA (FLASH_GROUP5_IER_RESERVED22_ENA << FLASH_GROUP5_IER_R_RESERVED22_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IER_R_RESERVED23_BIT ((uint16_t) 7U)

#define FLASH_GROUP5_IER_RESERVED23_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IER_RESERVED23_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IER_RESERVED23_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IER_R_RESERVED23_MASK (FLASH_GROUP5_IER_RESERVED23_MASK<< FLASH_GROUP5_IER_R_RESERVED23_BIT)
#define FLASH_GROUP5_IER_R_RESERVED23_DIS (FLASH_GROUP5_IER_RESERVED23_DIS << FLASH_GROUP5_IER_R_RESERVED23_BIT)
#define FLASH_GROUP5_IER_R_RESERVED23_ENA (FLASH_GROUP5_IER_RESERVED23_ENA << FLASH_GROUP5_IER_R_RESERVED23_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 FLASHIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP5_IFR_R_SW1_BIT ((uint16_t) 0U)

#define FLASH_GROUP5_IFR_SW1_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_SW1_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_SW1_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_SW1_MASK (FLASH_GROUP5_IFR_SW1_MASK<< FLASH_GROUP5_IFR_R_SW1_BIT)
#define FLASH_GROUP5_IFR_R_SW1_DIS (FLASH_GROUP5_IFR_SW1_DIS << FLASH_GROUP5_IFR_R_SW1_BIT)
#define FLASH_GROUP5_IFR_R_SW1_ENA (FLASH_GROUP5_IFR_SW1_ENA << FLASH_GROUP5_IFR_R_SW1_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED17_BIT ((uint16_t) 1U)

#define FLASH_GROUP5_IFR_RESERVED17_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED17_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED17_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED17_MASK (FLASH_GROUP5_IFR_RESERVED17_MASK<< FLASH_GROUP5_IFR_R_RESERVED17_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED17_DIS (FLASH_GROUP5_IFR_RESERVED17_DIS << FLASH_GROUP5_IFR_R_RESERVED17_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED17_ENA (FLASH_GROUP5_IFR_RESERVED17_ENA << FLASH_GROUP5_IFR_R_RESERVED17_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED18_BIT ((uint16_t) 2U)

#define FLASH_GROUP5_IFR_RESERVED18_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED18_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED18_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED18_MASK (FLASH_GROUP5_IFR_RESERVED18_MASK<< FLASH_GROUP5_IFR_R_RESERVED18_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED18_DIS (FLASH_GROUP5_IFR_RESERVED18_DIS << FLASH_GROUP5_IFR_R_RESERVED18_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED18_ENA (FLASH_GROUP5_IFR_RESERVED18_ENA << FLASH_GROUP5_IFR_R_RESERVED18_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED19_BIT ((uint16_t) 3U)

#define FLASH_GROUP5_IFR_RESERVED19_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED19_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED19_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED19_MASK (FLASH_GROUP5_IFR_RESERVED19_MASK<< FLASH_GROUP5_IFR_R_RESERVED19_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED19_DIS (FLASH_GROUP5_IFR_RESERVED19_DIS << FLASH_GROUP5_IFR_R_RESERVED19_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED19_ENA (FLASH_GROUP5_IFR_RESERVED19_ENA << FLASH_GROUP5_IFR_R_RESERVED19_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED20_BIT ((uint16_t) 4U)

#define FLASH_GROUP5_IFR_RESERVED20_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED20_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED20_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED20_MASK (FLASH_GROUP5_IFR_RESERVED20_MASK<< FLASH_GROUP5_IFR_R_RESERVED20_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED20_DIS (FLASH_GROUP5_IFR_RESERVED20_DIS << FLASH_GROUP5_IFR_R_RESERVED20_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED20_ENA (FLASH_GROUP5_IFR_RESERVED20_ENA << FLASH_GROUP5_IFR_R_RESERVED20_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED21_BIT ((uint16_t) 5U)

#define FLASH_GROUP5_IFR_RESERVED21_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED21_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED21_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED21_MASK (FLASH_GROUP5_IFR_RESERVED21_MASK<< FLASH_GROUP5_IFR_R_RESERVED21_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED21_DIS (FLASH_GROUP5_IFR_RESERVED21_DIS << FLASH_GROUP5_IFR_R_RESERVED21_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED21_ENA (FLASH_GROUP5_IFR_RESERVED21_ENA << FLASH_GROUP5_IFR_R_RESERVED21_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED22_BIT ((uint16_t) 6U)

#define FLASH_GROUP5_IFR_RESERVED22_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED22_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED22_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED22_MASK (FLASH_GROUP5_IFR_RESERVED22_MASK<< FLASH_GROUP5_IFR_R_RESERVED22_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED22_DIS (FLASH_GROUP5_IFR_RESERVED22_DIS << FLASH_GROUP5_IFR_R_RESERVED22_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED22_ENA (FLASH_GROUP5_IFR_RESERVED22_ENA << FLASH_GROUP5_IFR_R_RESERVED22_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP5_IFR_R_RESERVED23_BIT ((uint16_t) 7U)

#define FLASH_GROUP5_IFR_RESERVED23_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP5_IFR_RESERVED23_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP5_IFR_RESERVED23_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP5_IFR_R_RESERVED23_MASK (FLASH_GROUP5_IFR_RESERVED23_MASK<< FLASH_GROUP5_IFR_R_RESERVED23_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED23_DIS (FLASH_GROUP5_IFR_RESERVED23_DIS << FLASH_GROUP5_IFR_R_RESERVED23_BIT)
#define FLASH_GROUP5_IFR_R_RESERVED23_ENA (FLASH_GROUP5_IFR_RESERVED23_ENA << FLASH_GROUP5_IFR_R_RESERVED23_BIT)
/*-----------*/

#endif /* DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP5_H_ */
