/**
 *
 * @file FLASH_RegisterDefines_GROUP3.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP3_H_
#define DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP3_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 FLASHIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP3_IER_R_EPWM1_BIT ((uint16_t) 0U)

#define FLASH_GROUP3_IER_EPWM1_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_EPWM1_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_EPWM1_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_EPWM1_MASK (FLASH_GROUP3_IER_EPWM1_MASK<< FLASH_GROUP3_IER_R_EPWM1_BIT)
#define FLASH_GROUP3_IER_R_EPWM1_DIS (FLASH_GROUP3_IER_EPWM1_DIS << FLASH_GROUP3_IER_R_EPWM1_BIT)
#define FLASH_GROUP3_IER_R_EPWM1_ENA (FLASH_GROUP3_IER_EPWM1_ENA << FLASH_GROUP3_IER_R_EPWM1_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_EPWM2_BIT ((uint16_t) 1U)

#define FLASH_GROUP3_IER_EPWM2_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_EPWM2_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_EPWM2_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_EPWM2_MASK (FLASH_GROUP3_IER_EPWM2_MASK<< FLASH_GROUP3_IER_R_EPWM2_BIT)
#define FLASH_GROUP3_IER_R_EPWM2_DIS (FLASH_GROUP3_IER_EPWM2_DIS << FLASH_GROUP3_IER_R_EPWM2_BIT)
#define FLASH_GROUP3_IER_R_EPWM2_ENA (FLASH_GROUP3_IER_EPWM2_ENA << FLASH_GROUP3_IER_R_EPWM2_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_EPWM3_BIT ((uint16_t) 2U)

#define FLASH_GROUP3_IER_EPWM3_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_EPWM3_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_EPWM3_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_EPWM3_MASK (FLASH_GROUP3_IER_EPWM3_MASK<< FLASH_GROUP3_IER_R_EPWM3_BIT)
#define FLASH_GROUP3_IER_R_EPWM3_DIS (FLASH_GROUP3_IER_EPWM3_DIS << FLASH_GROUP3_IER_R_EPWM3_BIT)
#define FLASH_GROUP3_IER_R_EPWM3_ENA (FLASH_GROUP3_IER_EPWM3_ENA << FLASH_GROUP3_IER_R_EPWM3_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_EPWM4_BIT ((uint16_t) 3U)

#define FLASH_GROUP3_IER_EPWM4_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_EPWM4_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_EPWM4_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_EPWM4_MASK (FLASH_GROUP3_IER_EPWM4_MASK<< FLASH_GROUP3_IER_R_EPWM4_BIT)
#define FLASH_GROUP3_IER_R_EPWM4_DIS (FLASH_GROUP3_IER_EPWM4_DIS << FLASH_GROUP3_IER_R_EPWM4_BIT)
#define FLASH_GROUP3_IER_R_EPWM4_ENA (FLASH_GROUP3_IER_EPWM4_ENA << FLASH_GROUP3_IER_R_EPWM4_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_RESERVED6_BIT ((uint16_t) 4U)

#define FLASH_GROUP3_IER_RESERVED6_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_RESERVED6_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_RESERVED6_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_RESERVED6_MASK (FLASH_GROUP3_IER_RESERVED6_MASK<< FLASH_GROUP3_IER_R_RESERVED6_BIT)
#define FLASH_GROUP3_IER_R_RESERVED6_DIS (FLASH_GROUP3_IER_RESERVED6_DIS << FLASH_GROUP3_IER_R_RESERVED6_BIT)
#define FLASH_GROUP3_IER_R_RESERVED6_ENA (FLASH_GROUP3_IER_RESERVED6_ENA << FLASH_GROUP3_IER_R_RESERVED6_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_RESERVED7_BIT ((uint16_t) 5U)

#define FLASH_GROUP3_IER_RESERVED7_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_RESERVED7_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_RESERVED7_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_RESERVED7_MASK (FLASH_GROUP3_IER_RESERVED7_MASK<< FLASH_GROUP3_IER_R_RESERVED7_BIT)
#define FLASH_GROUP3_IER_R_RESERVED7_DIS (FLASH_GROUP3_IER_RESERVED7_DIS << FLASH_GROUP3_IER_R_RESERVED7_BIT)
#define FLASH_GROUP3_IER_R_RESERVED7_ENA (FLASH_GROUP3_IER_RESERVED7_ENA << FLASH_GROUP3_IER_R_RESERVED7_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_RESERVED8_BIT ((uint16_t) 6U)

#define FLASH_GROUP3_IER_RESERVED8_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_RESERVED8_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_RESERVED8_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_RESERVED8_MASK (FLASH_GROUP3_IER_RESERVED8_MASK<< FLASH_GROUP3_IER_R_RESERVED8_BIT)
#define FLASH_GROUP3_IER_R_RESERVED8_DIS (FLASH_GROUP3_IER_RESERVED8_DIS << FLASH_GROUP3_IER_R_RESERVED8_BIT)
#define FLASH_GROUP3_IER_R_RESERVED8_ENA (FLASH_GROUP3_IER_RESERVED8_ENA << FLASH_GROUP3_IER_R_RESERVED8_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IER_R_RESERVED9_BIT ((uint16_t) 7U)

#define FLASH_GROUP3_IER_RESERVED9_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IER_RESERVED9_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IER_RESERVED9_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IER_R_RESERVED9_MASK (FLASH_GROUP3_IER_RESERVED9_MASK<< FLASH_GROUP3_IER_R_RESERVED9_BIT)
#define FLASH_GROUP3_IER_R_RESERVED9_DIS (FLASH_GROUP3_IER_RESERVED9_DIS << FLASH_GROUP3_IER_R_RESERVED9_BIT)
#define FLASH_GROUP3_IER_R_RESERVED9_ENA (FLASH_GROUP3_IER_RESERVED9_ENA << FLASH_GROUP3_IER_R_RESERVED9_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 FLASHIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP3_IFR_R_EPWM1_BIT ((uint16_t) 0U)

#define FLASH_GROUP3_IFR_EPWM1_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_EPWM1_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_EPWM1_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_EPWM1_MASK (FLASH_GROUP3_IFR_EPWM1_MASK<< FLASH_GROUP3_IFR_R_EPWM1_BIT)
#define FLASH_GROUP3_IFR_R_EPWM1_DIS (FLASH_GROUP3_IFR_EPWM1_DIS << FLASH_GROUP3_IFR_R_EPWM1_BIT)
#define FLASH_GROUP3_IFR_R_EPWM1_ENA (FLASH_GROUP3_IFR_EPWM1_ENA << FLASH_GROUP3_IFR_R_EPWM1_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_EPWM2_BIT ((uint16_t) 1U)

#define FLASH_GROUP3_IFR_EPWM2_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_EPWM2_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_EPWM2_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_EPWM2_MASK (FLASH_GROUP3_IFR_EPWM2_MASK<< FLASH_GROUP3_IFR_R_EPWM2_BIT)
#define FLASH_GROUP3_IFR_R_EPWM2_DIS (FLASH_GROUP3_IFR_EPWM2_DIS << FLASH_GROUP3_IFR_R_EPWM2_BIT)
#define FLASH_GROUP3_IFR_R_EPWM2_ENA (FLASH_GROUP3_IFR_EPWM2_ENA << FLASH_GROUP3_IFR_R_EPWM2_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_EPWM3_BIT ((uint16_t) 2U)

#define FLASH_GROUP3_IFR_EPWM3_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_EPWM3_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_EPWM3_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_EPWM3_MASK (FLASH_GROUP3_IFR_EPWM3_MASK<< FLASH_GROUP3_IFR_R_EPWM3_BIT)
#define FLASH_GROUP3_IFR_R_EPWM3_DIS (FLASH_GROUP3_IFR_EPWM3_DIS << FLASH_GROUP3_IFR_R_EPWM3_BIT)
#define FLASH_GROUP3_IFR_R_EPWM3_ENA (FLASH_GROUP3_IFR_EPWM3_ENA << FLASH_GROUP3_IFR_R_EPWM3_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_EPWM4_BIT ((uint16_t) 3U)

#define FLASH_GROUP3_IFR_EPWM4_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_EPWM4_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_EPWM4_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_EPWM4_MASK (FLASH_GROUP3_IFR_EPWM4_MASK<< FLASH_GROUP3_IFR_R_EPWM4_BIT)
#define FLASH_GROUP3_IFR_R_EPWM4_DIS (FLASH_GROUP3_IFR_EPWM4_DIS << FLASH_GROUP3_IFR_R_EPWM4_BIT)
#define FLASH_GROUP3_IFR_R_EPWM4_ENA (FLASH_GROUP3_IFR_EPWM4_ENA << FLASH_GROUP3_IFR_R_EPWM4_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_RESERVED6_BIT ((uint16_t) 4U)

#define FLASH_GROUP3_IFR_RESERVED6_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_RESERVED6_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_RESERVED6_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_RESERVED6_MASK (FLASH_GROUP3_IFR_RESERVED6_MASK<< FLASH_GROUP3_IFR_R_RESERVED6_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED6_DIS (FLASH_GROUP3_IFR_RESERVED6_DIS << FLASH_GROUP3_IFR_R_RESERVED6_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED6_ENA (FLASH_GROUP3_IFR_RESERVED6_ENA << FLASH_GROUP3_IFR_R_RESERVED6_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_RESERVED7_BIT ((uint16_t) 5U)

#define FLASH_GROUP3_IFR_RESERVED7_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_RESERVED7_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_RESERVED7_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_RESERVED7_MASK (FLASH_GROUP3_IFR_RESERVED7_MASK<< FLASH_GROUP3_IFR_R_RESERVED7_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED7_DIS (FLASH_GROUP3_IFR_RESERVED7_DIS << FLASH_GROUP3_IFR_R_RESERVED7_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED7_ENA (FLASH_GROUP3_IFR_RESERVED7_ENA << FLASH_GROUP3_IFR_R_RESERVED7_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_RESERVED8_BIT ((uint16_t) 6U)

#define FLASH_GROUP3_IFR_RESERVED8_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_RESERVED8_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_RESERVED8_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_RESERVED8_MASK (FLASH_GROUP3_IFR_RESERVED8_MASK<< FLASH_GROUP3_IFR_R_RESERVED8_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED8_DIS (FLASH_GROUP3_IFR_RESERVED8_DIS << FLASH_GROUP3_IFR_R_RESERVED8_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED8_ENA (FLASH_GROUP3_IFR_RESERVED8_ENA << FLASH_GROUP3_IFR_R_RESERVED8_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP3_IFR_R_RESERVED9_BIT ((uint16_t) 7U)

#define FLASH_GROUP3_IFR_RESERVED9_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP3_IFR_RESERVED9_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP3_IFR_RESERVED9_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP3_IFR_R_RESERVED9_MASK (FLASH_GROUP3_IFR_RESERVED9_MASK<< FLASH_GROUP3_IFR_R_RESERVED9_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED9_DIS (FLASH_GROUP3_IFR_RESERVED9_DIS << FLASH_GROUP3_IFR_R_RESERVED9_BIT)
#define FLASH_GROUP3_IFR_R_RESERVED9_ENA (FLASH_GROUP3_IFR_RESERVED9_ENA << FLASH_GROUP3_IFR_R_RESERVED9_BIT)
/*-----------*/

#endif /* DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP3_H_ */
