/**
 *
 * @file FLASH_RegisterDefines_GROUP8.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP8_H_
#define DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP8_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 FLASHIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP8_IER_R_I2C1A_BIT ((uint16_t) 0U)

#define FLASH_GROUP8_IER_I2C1A_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_I2C1A_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_I2C1A_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_I2C1A_MASK (FLASH_GROUP8_IER_I2C1A_MASK<< FLASH_GROUP8_IER_R_I2C1A_BIT)
#define FLASH_GROUP8_IER_R_I2C1A_DIS (FLASH_GROUP8_IER_I2C1A_DIS << FLASH_GROUP8_IER_R_I2C1A_BIT)
#define FLASH_GROUP8_IER_R_I2C1A_ENA (FLASH_GROUP8_IER_I2C1A_ENA << FLASH_GROUP8_IER_R_I2C1A_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_I2C2A_BIT ((uint16_t) 1U)

#define FLASH_GROUP8_IER_I2C2A_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_I2C2A_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_I2C2A_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_I2C2A_MASK (FLASH_GROUP8_IER_I2C2A_MASK<< FLASH_GROUP8_IER_R_I2C2A_BIT)
#define FLASH_GROUP8_IER_R_I2C2A_DIS (FLASH_GROUP8_IER_I2C2A_DIS << FLASH_GROUP8_IER_R_I2C2A_BIT)
#define FLASH_GROUP8_IER_R_I2C2A_ENA (FLASH_GROUP8_IER_I2C2A_ENA << FLASH_GROUP8_IER_R_I2C2A_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED37_BIT ((uint16_t) 2U)

#define FLASH_GROUP8_IER_RESERVED37_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED37_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED37_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED37_MASK (FLASH_GROUP8_IER_RESERVED37_MASK<< FLASH_GROUP8_IER_R_RESERVED37_BIT)
#define FLASH_GROUP8_IER_R_RESERVED37_DIS (FLASH_GROUP8_IER_RESERVED37_DIS << FLASH_GROUP8_IER_R_RESERVED37_BIT)
#define FLASH_GROUP8_IER_R_RESERVED37_ENA (FLASH_GROUP8_IER_RESERVED37_ENA << FLASH_GROUP8_IER_R_RESERVED37_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED38_BIT ((uint16_t) 3U)

#define FLASH_GROUP8_IER_RESERVED38_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED38_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED38_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED38_MASK (FLASH_GROUP8_IER_RESERVED38_MASK<< FLASH_GROUP8_IER_R_RESERVED38_BIT)
#define FLASH_GROUP8_IER_R_RESERVED38_DIS (FLASH_GROUP8_IER_RESERVED38_DIS << FLASH_GROUP8_IER_R_RESERVED38_BIT)
#define FLASH_GROUP8_IER_R_RESERVED38_ENA (FLASH_GROUP8_IER_RESERVED38_ENA << FLASH_GROUP8_IER_R_RESERVED38_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED39_BIT ((uint16_t) 4U)

#define FLASH_GROUP8_IER_RESERVED39_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED39_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED39_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED39_MASK (FLASH_GROUP8_IER_RESERVED39_MASK<< FLASH_GROUP8_IER_R_RESERVED39_BIT)
#define FLASH_GROUP8_IER_R_RESERVED39_DIS (FLASH_GROUP8_IER_RESERVED39_DIS << FLASH_GROUP8_IER_R_RESERVED39_BIT)
#define FLASH_GROUP8_IER_R_RESERVED39_ENA (FLASH_GROUP8_IER_RESERVED39_ENA << FLASH_GROUP8_IER_R_RESERVED39_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED40_BIT ((uint16_t) 5U)

#define FLASH_GROUP8_IER_RESERVED40_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED40_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED40_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED40_MASK (FLASH_GROUP8_IER_RESERVED40_MASK<< FLASH_GROUP8_IER_R_RESERVED40_BIT)
#define FLASH_GROUP8_IER_R_RESERVED40_DIS (FLASH_GROUP8_IER_RESERVED40_DIS << FLASH_GROUP8_IER_R_RESERVED40_BIT)
#define FLASH_GROUP8_IER_R_RESERVED40_ENA (FLASH_GROUP8_IER_RESERVED40_ENA << FLASH_GROUP8_IER_R_RESERVED40_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED41_BIT ((uint16_t) 6U)

#define FLASH_GROUP8_IER_RESERVED41_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED41_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED41_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED41_MASK (FLASH_GROUP8_IER_RESERVED41_MASK<< FLASH_GROUP8_IER_R_RESERVED41_BIT)
#define FLASH_GROUP8_IER_R_RESERVED41_DIS (FLASH_GROUP8_IER_RESERVED41_DIS << FLASH_GROUP8_IER_R_RESERVED41_BIT)
#define FLASH_GROUP8_IER_R_RESERVED41_ENA (FLASH_GROUP8_IER_RESERVED41_ENA << FLASH_GROUP8_IER_R_RESERVED41_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IER_R_RESERVED42_BIT ((uint16_t) 7U)

#define FLASH_GROUP8_IER_RESERVED42_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IER_RESERVED42_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IER_RESERVED42_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IER_R_RESERVED42_MASK (FLASH_GROUP8_IER_RESERVED42_MASK<< FLASH_GROUP8_IER_R_RESERVED42_BIT)
#define FLASH_GROUP8_IER_R_RESERVED42_DIS (FLASH_GROUP8_IER_RESERVED42_DIS << FLASH_GROUP8_IER_R_RESERVED42_BIT)
#define FLASH_GROUP8_IER_R_RESERVED42_ENA (FLASH_GROUP8_IER_RESERVED42_ENA << FLASH_GROUP8_IER_R_RESERVED42_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 FLASHIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define FLASH_GROUP8_IFR_R_I2C1A_BIT ((uint16_t) 0U)

#define FLASH_GROUP8_IFR_I2C1A_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_I2C1A_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_I2C1A_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_I2C1A_MASK (FLASH_GROUP8_IFR_I2C1A_MASK<< FLASH_GROUP8_IFR_R_I2C1A_BIT)
#define FLASH_GROUP8_IFR_R_I2C1A_DIS (FLASH_GROUP8_IFR_I2C1A_DIS << FLASH_GROUP8_IFR_R_I2C1A_BIT)
#define FLASH_GROUP8_IFR_R_I2C1A_ENA (FLASH_GROUP8_IFR_I2C1A_ENA << FLASH_GROUP8_IFR_R_I2C1A_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_I2C2A_BIT ((uint16_t) 1U)

#define FLASH_GROUP8_IFR_I2C2A_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_I2C2A_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_I2C2A_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_I2C2A_MASK (FLASH_GROUP8_IFR_I2C2A_MASK<< FLASH_GROUP8_IFR_R_I2C2A_BIT)
#define FLASH_GROUP8_IFR_R_I2C2A_DIS (FLASH_GROUP8_IFR_I2C2A_DIS << FLASH_GROUP8_IFR_R_I2C2A_BIT)
#define FLASH_GROUP8_IFR_R_I2C2A_ENA (FLASH_GROUP8_IFR_I2C2A_ENA << FLASH_GROUP8_IFR_R_I2C2A_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED37_BIT ((uint16_t) 2U)

#define FLASH_GROUP8_IFR_RESERVED37_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED37_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED37_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED37_MASK (FLASH_GROUP8_IFR_RESERVED37_MASK<< FLASH_GROUP8_IFR_R_RESERVED37_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED37_DIS (FLASH_GROUP8_IFR_RESERVED37_DIS << FLASH_GROUP8_IFR_R_RESERVED37_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED37_ENA (FLASH_GROUP8_IFR_RESERVED37_ENA << FLASH_GROUP8_IFR_R_RESERVED37_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED38_BIT ((uint16_t) 3U)

#define FLASH_GROUP8_IFR_RESERVED38_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED38_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED38_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED38_MASK (FLASH_GROUP8_IFR_RESERVED38_MASK<< FLASH_GROUP8_IFR_R_RESERVED38_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED38_DIS (FLASH_GROUP8_IFR_RESERVED38_DIS << FLASH_GROUP8_IFR_R_RESERVED38_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED38_ENA (FLASH_GROUP8_IFR_RESERVED38_ENA << FLASH_GROUP8_IFR_R_RESERVED38_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED39_BIT ((uint16_t) 4U)

#define FLASH_GROUP8_IFR_RESERVED39_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED39_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED39_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED39_MASK (FLASH_GROUP8_IFR_RESERVED39_MASK<< FLASH_GROUP8_IFR_R_RESERVED39_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED39_DIS (FLASH_GROUP8_IFR_RESERVED39_DIS << FLASH_GROUP8_IFR_R_RESERVED39_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED39_ENA (FLASH_GROUP8_IFR_RESERVED39_ENA << FLASH_GROUP8_IFR_R_RESERVED39_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED40_BIT ((uint16_t) 5U)

#define FLASH_GROUP8_IFR_RESERVED40_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED40_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED40_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED40_MASK (FLASH_GROUP8_IFR_RESERVED40_MASK<< FLASH_GROUP8_IFR_R_RESERVED40_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED40_DIS (FLASH_GROUP8_IFR_RESERVED40_DIS << FLASH_GROUP8_IFR_R_RESERVED40_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED40_ENA (FLASH_GROUP8_IFR_RESERVED40_ENA << FLASH_GROUP8_IFR_R_RESERVED40_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED41_BIT ((uint16_t) 6U)

#define FLASH_GROUP8_IFR_RESERVED41_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED41_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED41_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED41_MASK (FLASH_GROUP8_IFR_RESERVED41_MASK<< FLASH_GROUP8_IFR_R_RESERVED41_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED41_DIS (FLASH_GROUP8_IFR_RESERVED41_DIS << FLASH_GROUP8_IFR_R_RESERVED41_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED41_ENA (FLASH_GROUP8_IFR_RESERVED41_ENA << FLASH_GROUP8_IFR_R_RESERVED41_BIT)
/*-----------*/

/*-----------*/
#define FLASH_GROUP8_IFR_R_RESERVED42_BIT ((uint16_t) 7U)

#define FLASH_GROUP8_IFR_RESERVED42_MASK ((uint16_t) 0x01U)
#define FLASH_GROUP8_IFR_RESERVED42_DIS ((uint16_t) 0x00U)
#define FLASH_GROUP8_IFR_RESERVED42_ENA ((uint16_t) 0x01U)

#define FLASH_GROUP8_IFR_R_RESERVED42_MASK (FLASH_GROUP8_IFR_RESERVED42_MASK<< FLASH_GROUP8_IFR_R_RESERVED42_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED42_DIS (FLASH_GROUP8_IFR_RESERVED42_DIS << FLASH_GROUP8_IFR_R_RESERVED42_BIT)
#define FLASH_GROUP8_IFR_R_RESERVED42_ENA (FLASH_GROUP8_IFR_RESERVED42_ENA << FLASH_GROUP8_IFR_R_RESERVED42_BIT)
/*-----------*/

#endif /* DRIVERLIB_FLASH_PERIPHERAL_REGISTERDEFINES_XHEADER_FLASH_REGISTERDEFINES_GROUP8_H_ */
