/**
 *
 * @file SYSCTL_RegisterDefines_GROUP6.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP6_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP6_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 SYSCTLIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP6_IER_R_SPIA_RX_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP6_IER_SPIA_RX_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_SPIA_RX_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_SPIA_RX_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_SPIA_RX_MASK (SYSCTL_GROUP6_IER_SPIA_RX_MASK<< SYSCTL_GROUP6_IER_R_SPIA_RX_BIT)
#define SYSCTL_GROUP6_IER_R_SPIA_RX_DIS (SYSCTL_GROUP6_IER_SPIA_RX_DIS << SYSCTL_GROUP6_IER_R_SPIA_RX_BIT)
#define SYSCTL_GROUP6_IER_R_SPIA_RX_ENA (SYSCTL_GROUP6_IER_SPIA_RX_ENA << SYSCTL_GROUP6_IER_R_SPIA_RX_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_SPIA_TX_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP6_IER_SPIA_TX_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_SPIA_TX_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_SPIA_TX_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_SPIA_TX_MASK (SYSCTL_GROUP6_IER_SPIA_TX_MASK<< SYSCTL_GROUP6_IER_R_SPIA_TX_BIT)
#define SYSCTL_GROUP6_IER_R_SPIA_TX_DIS (SYSCTL_GROUP6_IER_SPIA_TX_DIS << SYSCTL_GROUP6_IER_R_SPIA_TX_BIT)
#define SYSCTL_GROUP6_IER_R_SPIA_TX_ENA (SYSCTL_GROUP6_IER_SPIA_TX_ENA << SYSCTL_GROUP6_IER_R_SPIA_TX_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED24_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP6_IER_RESERVED24_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED24_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED24_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED24_MASK (SYSCTL_GROUP6_IER_RESERVED24_MASK<< SYSCTL_GROUP6_IER_R_RESERVED24_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED24_DIS (SYSCTL_GROUP6_IER_RESERVED24_DIS << SYSCTL_GROUP6_IER_R_RESERVED24_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED24_ENA (SYSCTL_GROUP6_IER_RESERVED24_ENA << SYSCTL_GROUP6_IER_R_RESERVED24_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED25_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP6_IER_RESERVED25_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED25_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED25_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED25_MASK (SYSCTL_GROUP6_IER_RESERVED25_MASK<< SYSCTL_GROUP6_IER_R_RESERVED25_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED25_DIS (SYSCTL_GROUP6_IER_RESERVED25_DIS << SYSCTL_GROUP6_IER_R_RESERVED25_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED25_ENA (SYSCTL_GROUP6_IER_RESERVED25_ENA << SYSCTL_GROUP6_IER_R_RESERVED25_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED26_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP6_IER_RESERVED26_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED26_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED26_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED26_MASK (SYSCTL_GROUP6_IER_RESERVED26_MASK<< SYSCTL_GROUP6_IER_R_RESERVED26_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED26_DIS (SYSCTL_GROUP6_IER_RESERVED26_DIS << SYSCTL_GROUP6_IER_R_RESERVED26_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED26_ENA (SYSCTL_GROUP6_IER_RESERVED26_ENA << SYSCTL_GROUP6_IER_R_RESERVED26_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED27_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP6_IER_RESERVED27_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED27_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED27_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED27_MASK (SYSCTL_GROUP6_IER_RESERVED27_MASK<< SYSCTL_GROUP6_IER_R_RESERVED27_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED27_DIS (SYSCTL_GROUP6_IER_RESERVED27_DIS << SYSCTL_GROUP6_IER_R_RESERVED27_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED27_ENA (SYSCTL_GROUP6_IER_RESERVED27_ENA << SYSCTL_GROUP6_IER_R_RESERVED27_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED28_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP6_IER_RESERVED28_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED28_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED28_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED28_MASK (SYSCTL_GROUP6_IER_RESERVED28_MASK<< SYSCTL_GROUP6_IER_R_RESERVED28_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED28_DIS (SYSCTL_GROUP6_IER_RESERVED28_DIS << SYSCTL_GROUP6_IER_R_RESERVED28_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED28_ENA (SYSCTL_GROUP6_IER_RESERVED28_ENA << SYSCTL_GROUP6_IER_R_RESERVED28_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IER_R_RESERVED29_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP6_IER_RESERVED29_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IER_RESERVED29_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IER_RESERVED29_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IER_R_RESERVED29_MASK (SYSCTL_GROUP6_IER_RESERVED29_MASK<< SYSCTL_GROUP6_IER_R_RESERVED29_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED29_DIS (SYSCTL_GROUP6_IER_RESERVED29_DIS << SYSCTL_GROUP6_IER_R_RESERVED29_BIT)
#define SYSCTL_GROUP6_IER_R_RESERVED29_ENA (SYSCTL_GROUP6_IER_RESERVED29_ENA << SYSCTL_GROUP6_IER_R_RESERVED29_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 SYSCTLIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP6_IFR_R_SPIA_RX_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP6_IFR_SPIA_RX_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_SPIA_RX_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_SPIA_RX_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_SPIA_RX_MASK (SYSCTL_GROUP6_IFR_SPIA_RX_MASK<< SYSCTL_GROUP6_IFR_R_SPIA_RX_BIT)
#define SYSCTL_GROUP6_IFR_R_SPIA_RX_DIS (SYSCTL_GROUP6_IFR_SPIA_RX_DIS << SYSCTL_GROUP6_IFR_R_SPIA_RX_BIT)
#define SYSCTL_GROUP6_IFR_R_SPIA_RX_ENA (SYSCTL_GROUP6_IFR_SPIA_RX_ENA << SYSCTL_GROUP6_IFR_R_SPIA_RX_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_SPIA_TX_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP6_IFR_SPIA_TX_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_SPIA_TX_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_SPIA_TX_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_SPIA_TX_MASK (SYSCTL_GROUP6_IFR_SPIA_TX_MASK<< SYSCTL_GROUP6_IFR_R_SPIA_TX_BIT)
#define SYSCTL_GROUP6_IFR_R_SPIA_TX_DIS (SYSCTL_GROUP6_IFR_SPIA_TX_DIS << SYSCTL_GROUP6_IFR_R_SPIA_TX_BIT)
#define SYSCTL_GROUP6_IFR_R_SPIA_TX_ENA (SYSCTL_GROUP6_IFR_SPIA_TX_ENA << SYSCTL_GROUP6_IFR_R_SPIA_TX_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED24_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP6_IFR_RESERVED24_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED24_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED24_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED24_MASK (SYSCTL_GROUP6_IFR_RESERVED24_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED24_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED24_DIS (SYSCTL_GROUP6_IFR_RESERVED24_DIS << SYSCTL_GROUP6_IFR_R_RESERVED24_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED24_ENA (SYSCTL_GROUP6_IFR_RESERVED24_ENA << SYSCTL_GROUP6_IFR_R_RESERVED24_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED25_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP6_IFR_RESERVED25_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED25_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED25_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED25_MASK (SYSCTL_GROUP6_IFR_RESERVED25_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED25_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED25_DIS (SYSCTL_GROUP6_IFR_RESERVED25_DIS << SYSCTL_GROUP6_IFR_R_RESERVED25_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED25_ENA (SYSCTL_GROUP6_IFR_RESERVED25_ENA << SYSCTL_GROUP6_IFR_R_RESERVED25_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED26_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP6_IFR_RESERVED26_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED26_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED26_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED26_MASK (SYSCTL_GROUP6_IFR_RESERVED26_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED26_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED26_DIS (SYSCTL_GROUP6_IFR_RESERVED26_DIS << SYSCTL_GROUP6_IFR_R_RESERVED26_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED26_ENA (SYSCTL_GROUP6_IFR_RESERVED26_ENA << SYSCTL_GROUP6_IFR_R_RESERVED26_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED27_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP6_IFR_RESERVED27_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED27_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED27_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED27_MASK (SYSCTL_GROUP6_IFR_RESERVED27_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED27_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED27_DIS (SYSCTL_GROUP6_IFR_RESERVED27_DIS << SYSCTL_GROUP6_IFR_R_RESERVED27_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED27_ENA (SYSCTL_GROUP6_IFR_RESERVED27_ENA << SYSCTL_GROUP6_IFR_R_RESERVED27_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED28_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP6_IFR_RESERVED28_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED28_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED28_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED28_MASK (SYSCTL_GROUP6_IFR_RESERVED28_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED28_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED28_DIS (SYSCTL_GROUP6_IFR_RESERVED28_DIS << SYSCTL_GROUP6_IFR_R_RESERVED28_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED28_ENA (SYSCTL_GROUP6_IFR_RESERVED28_ENA << SYSCTL_GROUP6_IFR_R_RESERVED28_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP6_IFR_R_RESERVED29_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP6_IFR_RESERVED29_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP6_IFR_RESERVED29_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP6_IFR_RESERVED29_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP6_IFR_R_RESERVED29_MASK (SYSCTL_GROUP6_IFR_RESERVED29_MASK<< SYSCTL_GROUP6_IFR_R_RESERVED29_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED29_DIS (SYSCTL_GROUP6_IFR_RESERVED29_DIS << SYSCTL_GROUP6_IFR_R_RESERVED29_BIT)
#define SYSCTL_GROUP6_IFR_R_RESERVED29_ENA (SYSCTL_GROUP6_IFR_RESERVED29_ENA << SYSCTL_GROUP6_IFR_R_RESERVED29_BIT)
/*-----------*/

#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP6_H_ */
