/**
 *
 * @file SYSCTL_RegisterDefines_GROUP1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP1_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP1_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 SYSCTLIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP1_IER_R_ADC1_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP1_IER_ADC1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_ADC1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_ADC1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_ADC1_MASK (SYSCTL_GROUP1_IER_ADC1_MASK<< SYSCTL_GROUP1_IER_R_ADC1_BIT)
#define SYSCTL_GROUP1_IER_R_ADC1_DIS (SYSCTL_GROUP1_IER_ADC1_DIS << SYSCTL_GROUP1_IER_R_ADC1_BIT)
#define SYSCTL_GROUP1_IER_R_ADC1_ENA (SYSCTL_GROUP1_IER_ADC1_ENA << SYSCTL_GROUP1_IER_R_ADC1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_ADC2_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP1_IER_ADC2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_ADC2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_ADC2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_ADC2_MASK (SYSCTL_GROUP1_IER_ADC2_MASK<< SYSCTL_GROUP1_IER_R_ADC2_BIT)
#define SYSCTL_GROUP1_IER_R_ADC2_DIS (SYSCTL_GROUP1_IER_ADC2_DIS << SYSCTL_GROUP1_IER_R_ADC2_BIT)
#define SYSCTL_GROUP1_IER_R_ADC2_ENA (SYSCTL_GROUP1_IER_ADC2_ENA << SYSCTL_GROUP1_IER_R_ADC2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_RESERVED1_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP1_IER_RESERVED1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_RESERVED1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_RESERVED1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_RESERVED1_MASK (SYSCTL_GROUP1_IER_RESERVED1_MASK<< SYSCTL_GROUP1_IER_R_RESERVED1_BIT)
#define SYSCTL_GROUP1_IER_R_RESERVED1_DIS (SYSCTL_GROUP1_IER_RESERVED1_DIS << SYSCTL_GROUP1_IER_R_RESERVED1_BIT)
#define SYSCTL_GROUP1_IER_R_RESERVED1_ENA (SYSCTL_GROUP1_IER_RESERVED1_ENA << SYSCTL_GROUP1_IER_R_RESERVED1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_X1_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP1_IER_X1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_X1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_X1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_X1_MASK (SYSCTL_GROUP1_IER_X1_MASK<< SYSCTL_GROUP1_IER_R_X1_BIT)
#define SYSCTL_GROUP1_IER_R_X1_DIS (SYSCTL_GROUP1_IER_X1_DIS << SYSCTL_GROUP1_IER_R_X1_BIT)
#define SYSCTL_GROUP1_IER_R_X1_ENA (SYSCTL_GROUP1_IER_X1_ENA << SYSCTL_GROUP1_IER_R_X1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_X2_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP1_IER_X2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_X2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_X2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_X2_MASK (SYSCTL_GROUP1_IER_X2_MASK<< SYSCTL_GROUP1_IER_R_X2_BIT)
#define SYSCTL_GROUP1_IER_R_X2_DIS (SYSCTL_GROUP1_IER_X2_DIS << SYSCTL_GROUP1_IER_R_X2_BIT)
#define SYSCTL_GROUP1_IER_R_X2_ENA (SYSCTL_GROUP1_IER_X2_ENA << SYSCTL_GROUP1_IER_R_X2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_ADC9_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP1_IER_ADC9_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_ADC9_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_ADC9_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_ADC9_MASK (SYSCTL_GROUP1_IER_ADC9_MASK<< SYSCTL_GROUP1_IER_R_ADC9_BIT)
#define SYSCTL_GROUP1_IER_R_ADC9_DIS (SYSCTL_GROUP1_IER_ADC9_DIS << SYSCTL_GROUP1_IER_R_ADC9_BIT)
#define SYSCTL_GROUP1_IER_R_ADC9_ENA (SYSCTL_GROUP1_IER_ADC9_ENA << SYSCTL_GROUP1_IER_R_ADC9_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_T0_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP1_IER_T0_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_T0_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_T0_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_T0_MASK (SYSCTL_GROUP1_IER_T0_MASK<< SYSCTL_GROUP1_IER_R_T0_BIT)
#define SYSCTL_GROUP1_IER_R_T0_DIS (SYSCTL_GROUP1_IER_T0_DIS << SYSCTL_GROUP1_IER_R_T0_BIT)
#define SYSCTL_GROUP1_IER_R_T0_ENA (SYSCTL_GROUP1_IER_T0_ENA << SYSCTL_GROUP1_IER_R_T0_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IER_R_WAKE_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP1_IER_WAKE_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IER_WAKE_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IER_WAKE_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IER_R_WAKE_MASK (SYSCTL_GROUP1_IER_WAKE_MASK<< SYSCTL_GROUP1_IER_R_WAKE_BIT)
#define SYSCTL_GROUP1_IER_R_WAKE_DIS (SYSCTL_GROUP1_IER_WAKE_DIS << SYSCTL_GROUP1_IER_R_WAKE_BIT)
#define SYSCTL_GROUP1_IER_R_WAKE_ENA (SYSCTL_GROUP1_IER_WAKE_ENA << SYSCTL_GROUP1_IER_R_WAKE_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 SYSCTLIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP1_IFR_R_ADC1_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP1_IFR_ADC1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_ADC1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_ADC1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_ADC1_MASK (SYSCTL_GROUP1_IFR_ADC1_MASK<< SYSCTL_GROUP1_IFR_R_ADC1_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC1_DIS (SYSCTL_GROUP1_IFR_ADC1_DIS << SYSCTL_GROUP1_IFR_R_ADC1_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC1_ENA (SYSCTL_GROUP1_IFR_ADC1_ENA << SYSCTL_GROUP1_IFR_R_ADC1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_ADC2_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP1_IFR_ADC2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_ADC2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_ADC2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_ADC2_MASK (SYSCTL_GROUP1_IFR_ADC2_MASK<< SYSCTL_GROUP1_IFR_R_ADC2_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC2_DIS (SYSCTL_GROUP1_IFR_ADC2_DIS << SYSCTL_GROUP1_IFR_R_ADC2_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC2_ENA (SYSCTL_GROUP1_IFR_ADC2_ENA << SYSCTL_GROUP1_IFR_R_ADC2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_RESERVED1_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP1_IFR_RESERVED1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_RESERVED1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_RESERVED1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_RESERVED1_MASK (SYSCTL_GROUP1_IFR_RESERVED1_MASK<< SYSCTL_GROUP1_IFR_R_RESERVED1_BIT)
#define SYSCTL_GROUP1_IFR_R_RESERVED1_DIS (SYSCTL_GROUP1_IFR_RESERVED1_DIS << SYSCTL_GROUP1_IFR_R_RESERVED1_BIT)
#define SYSCTL_GROUP1_IFR_R_RESERVED1_ENA (SYSCTL_GROUP1_IFR_RESERVED1_ENA << SYSCTL_GROUP1_IFR_R_RESERVED1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_X1_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP1_IFR_X1_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_X1_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_X1_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_X1_MASK (SYSCTL_GROUP1_IFR_X1_MASK<< SYSCTL_GROUP1_IFR_R_X1_BIT)
#define SYSCTL_GROUP1_IFR_R_X1_DIS (SYSCTL_GROUP1_IFR_X1_DIS << SYSCTL_GROUP1_IFR_R_X1_BIT)
#define SYSCTL_GROUP1_IFR_R_X1_ENA (SYSCTL_GROUP1_IFR_X1_ENA << SYSCTL_GROUP1_IFR_R_X1_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_X2_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP1_IFR_X2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_X2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_X2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_X2_MASK (SYSCTL_GROUP1_IFR_X2_MASK<< SYSCTL_GROUP1_IFR_R_X2_BIT)
#define SYSCTL_GROUP1_IFR_R_X2_DIS (SYSCTL_GROUP1_IFR_X2_DIS << SYSCTL_GROUP1_IFR_R_X2_BIT)
#define SYSCTL_GROUP1_IFR_R_X2_ENA (SYSCTL_GROUP1_IFR_X2_ENA << SYSCTL_GROUP1_IFR_R_X2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_ADC9_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP1_IFR_ADC9_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_ADC9_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_ADC9_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_ADC9_MASK (SYSCTL_GROUP1_IFR_ADC9_MASK<< SYSCTL_GROUP1_IFR_R_ADC9_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC9_DIS (SYSCTL_GROUP1_IFR_ADC9_DIS << SYSCTL_GROUP1_IFR_R_ADC9_BIT)
#define SYSCTL_GROUP1_IFR_R_ADC9_ENA (SYSCTL_GROUP1_IFR_ADC9_ENA << SYSCTL_GROUP1_IFR_R_ADC9_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_T0_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP1_IFR_T0_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_T0_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_T0_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_T0_MASK (SYSCTL_GROUP1_IFR_T0_MASK<< SYSCTL_GROUP1_IFR_R_T0_BIT)
#define SYSCTL_GROUP1_IFR_R_T0_DIS (SYSCTL_GROUP1_IFR_T0_DIS << SYSCTL_GROUP1_IFR_R_T0_BIT)
#define SYSCTL_GROUP1_IFR_R_T0_ENA (SYSCTL_GROUP1_IFR_T0_ENA << SYSCTL_GROUP1_IFR_R_T0_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP1_IFR_R_WAKE_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP1_IFR_WAKE_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP1_IFR_WAKE_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP1_IFR_WAKE_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP1_IFR_R_WAKE_MASK (SYSCTL_GROUP1_IFR_WAKE_MASK<< SYSCTL_GROUP1_IFR_R_WAKE_BIT)
#define SYSCTL_GROUP1_IFR_R_WAKE_DIS (SYSCTL_GROUP1_IFR_WAKE_DIS << SYSCTL_GROUP1_IFR_R_WAKE_BIT)
#define SYSCTL_GROUP1_IFR_R_WAKE_ENA (SYSCTL_GROUP1_IFR_WAKE_ENA << SYSCTL_GROUP1_IFR_R_WAKE_BIT)
/*-----------*/

#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP1_H_ */
