/**
 *
 * @file SYSCTL_RegisterDefines_GROUP7.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 13 jul. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 13 jul. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP7_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP7_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 SYSCTLIER *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP7_IER_R_SW2_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP7_IER_SW2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_SW2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_SW2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_SW2_MASK (SYSCTL_GROUP7_IER_SW2_MASK<< SYSCTL_GROUP7_IER_R_SW2_BIT)
#define SYSCTL_GROUP7_IER_R_SW2_DIS (SYSCTL_GROUP7_IER_SW2_DIS << SYSCTL_GROUP7_IER_R_SW2_BIT)
#define SYSCTL_GROUP7_IER_R_SW2_ENA (SYSCTL_GROUP7_IER_SW2_ENA << SYSCTL_GROUP7_IER_R_SW2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED30_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP7_IER_RESERVED30_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED30_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED30_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED30_MASK (SYSCTL_GROUP7_IER_RESERVED30_MASK<< SYSCTL_GROUP7_IER_R_RESERVED30_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED30_DIS (SYSCTL_GROUP7_IER_RESERVED30_DIS << SYSCTL_GROUP7_IER_R_RESERVED30_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED30_ENA (SYSCTL_GROUP7_IER_RESERVED30_ENA << SYSCTL_GROUP7_IER_R_RESERVED30_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED31_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP7_IER_RESERVED31_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED31_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED31_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED31_MASK (SYSCTL_GROUP7_IER_RESERVED31_MASK<< SYSCTL_GROUP7_IER_R_RESERVED31_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED31_DIS (SYSCTL_GROUP7_IER_RESERVED31_DIS << SYSCTL_GROUP7_IER_R_RESERVED31_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED31_ENA (SYSCTL_GROUP7_IER_RESERVED31_ENA << SYSCTL_GROUP7_IER_R_RESERVED31_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED32_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP7_IER_RESERVED32_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED32_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED32_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED32_MASK (SYSCTL_GROUP7_IER_RESERVED32_MASK<< SYSCTL_GROUP7_IER_R_RESERVED32_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED32_DIS (SYSCTL_GROUP7_IER_RESERVED32_DIS << SYSCTL_GROUP7_IER_R_RESERVED32_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED32_ENA (SYSCTL_GROUP7_IER_RESERVED32_ENA << SYSCTL_GROUP7_IER_R_RESERVED32_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED33_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP7_IER_RESERVED33_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED33_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED33_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED33_MASK (SYSCTL_GROUP7_IER_RESERVED33_MASK<< SYSCTL_GROUP7_IER_R_RESERVED33_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED33_DIS (SYSCTL_GROUP7_IER_RESERVED33_DIS << SYSCTL_GROUP7_IER_R_RESERVED33_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED33_ENA (SYSCTL_GROUP7_IER_RESERVED33_ENA << SYSCTL_GROUP7_IER_R_RESERVED33_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED34_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP7_IER_RESERVED34_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED34_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED34_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED34_MASK (SYSCTL_GROUP7_IER_RESERVED34_MASK<< SYSCTL_GROUP7_IER_R_RESERVED34_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED34_DIS (SYSCTL_GROUP7_IER_RESERVED34_DIS << SYSCTL_GROUP7_IER_R_RESERVED34_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED34_ENA (SYSCTL_GROUP7_IER_RESERVED34_ENA << SYSCTL_GROUP7_IER_R_RESERVED34_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED35_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP7_IER_RESERVED35_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED35_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED35_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED35_MASK (SYSCTL_GROUP7_IER_RESERVED35_MASK<< SYSCTL_GROUP7_IER_R_RESERVED35_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED35_DIS (SYSCTL_GROUP7_IER_RESERVED35_DIS << SYSCTL_GROUP7_IER_R_RESERVED35_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED35_ENA (SYSCTL_GROUP7_IER_RESERVED35_ENA << SYSCTL_GROUP7_IER_R_RESERVED35_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IER_R_RESERVED36_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP7_IER_RESERVED36_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IER_RESERVED36_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IER_RESERVED36_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IER_R_RESERVED36_MASK (SYSCTL_GROUP7_IER_RESERVED36_MASK<< SYSCTL_GROUP7_IER_R_RESERVED36_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED36_DIS (SYSCTL_GROUP7_IER_RESERVED36_DIS << SYSCTL_GROUP7_IER_R_RESERVED36_BIT)
#define SYSCTL_GROUP7_IER_R_RESERVED36_ENA (SYSCTL_GROUP7_IER_RESERVED36_ENA << SYSCTL_GROUP7_IER_R_RESERVED36_BIT)
/*-----------*/

/******************************************************************************************
 ************************************ 1 SYSCTLIFR *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_GROUP7_IFR_R_SW2_BIT ((uint16_t) 0U)

#define SYSCTL_GROUP7_IFR_SW2_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_SW2_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_SW2_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_SW2_MASK (SYSCTL_GROUP7_IFR_SW2_MASK<< SYSCTL_GROUP7_IFR_R_SW2_BIT)
#define SYSCTL_GROUP7_IFR_R_SW2_DIS (SYSCTL_GROUP7_IFR_SW2_DIS << SYSCTL_GROUP7_IFR_R_SW2_BIT)
#define SYSCTL_GROUP7_IFR_R_SW2_ENA (SYSCTL_GROUP7_IFR_SW2_ENA << SYSCTL_GROUP7_IFR_R_SW2_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED30_BIT ((uint16_t) 1U)

#define SYSCTL_GROUP7_IFR_RESERVED30_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED30_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED30_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED30_MASK (SYSCTL_GROUP7_IFR_RESERVED30_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED30_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED30_DIS (SYSCTL_GROUP7_IFR_RESERVED30_DIS << SYSCTL_GROUP7_IFR_R_RESERVED30_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED30_ENA (SYSCTL_GROUP7_IFR_RESERVED30_ENA << SYSCTL_GROUP7_IFR_R_RESERVED30_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED31_BIT ((uint16_t) 2U)

#define SYSCTL_GROUP7_IFR_RESERVED31_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED31_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED31_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED31_MASK (SYSCTL_GROUP7_IFR_RESERVED31_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED31_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED31_DIS (SYSCTL_GROUP7_IFR_RESERVED31_DIS << SYSCTL_GROUP7_IFR_R_RESERVED31_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED31_ENA (SYSCTL_GROUP7_IFR_RESERVED31_ENA << SYSCTL_GROUP7_IFR_R_RESERVED31_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED32_BIT ((uint16_t) 3U)

#define SYSCTL_GROUP7_IFR_RESERVED32_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED32_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED32_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED32_MASK (SYSCTL_GROUP7_IFR_RESERVED32_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED32_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED32_DIS (SYSCTL_GROUP7_IFR_RESERVED32_DIS << SYSCTL_GROUP7_IFR_R_RESERVED32_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED32_ENA (SYSCTL_GROUP7_IFR_RESERVED32_ENA << SYSCTL_GROUP7_IFR_R_RESERVED32_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED33_BIT ((uint16_t) 4U)

#define SYSCTL_GROUP7_IFR_RESERVED33_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED33_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED33_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED33_MASK (SYSCTL_GROUP7_IFR_RESERVED33_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED33_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED33_DIS (SYSCTL_GROUP7_IFR_RESERVED33_DIS << SYSCTL_GROUP7_IFR_R_RESERVED33_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED33_ENA (SYSCTL_GROUP7_IFR_RESERVED33_ENA << SYSCTL_GROUP7_IFR_R_RESERVED33_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED34_BIT ((uint16_t) 5U)

#define SYSCTL_GROUP7_IFR_RESERVED34_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED34_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED34_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED34_MASK (SYSCTL_GROUP7_IFR_RESERVED34_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED34_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED34_DIS (SYSCTL_GROUP7_IFR_RESERVED34_DIS << SYSCTL_GROUP7_IFR_R_RESERVED34_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED34_ENA (SYSCTL_GROUP7_IFR_RESERVED34_ENA << SYSCTL_GROUP7_IFR_R_RESERVED34_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED35_BIT ((uint16_t) 6U)

#define SYSCTL_GROUP7_IFR_RESERVED35_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED35_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED35_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED35_MASK (SYSCTL_GROUP7_IFR_RESERVED35_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED35_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED35_DIS (SYSCTL_GROUP7_IFR_RESERVED35_DIS << SYSCTL_GROUP7_IFR_R_RESERVED35_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED35_ENA (SYSCTL_GROUP7_IFR_RESERVED35_ENA << SYSCTL_GROUP7_IFR_R_RESERVED35_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_GROUP7_IFR_R_RESERVED36_BIT ((uint16_t) 7U)

#define SYSCTL_GROUP7_IFR_RESERVED36_MASK ((uint16_t) 0x01U)
#define SYSCTL_GROUP7_IFR_RESERVED36_DIS ((uint16_t) 0x00U)
#define SYSCTL_GROUP7_IFR_RESERVED36_ENA ((uint16_t) 0x01U)

#define SYSCTL_GROUP7_IFR_R_RESERVED36_MASK (SYSCTL_GROUP7_IFR_RESERVED36_MASK<< SYSCTL_GROUP7_IFR_R_RESERVED36_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED36_DIS (SYSCTL_GROUP7_IFR_RESERVED36_DIS << SYSCTL_GROUP7_IFR_R_RESERVED36_BIT)
#define SYSCTL_GROUP7_IFR_R_RESERVED36_ENA (SYSCTL_GROUP7_IFR_RESERVED36_ENA << SYSCTL_GROUP7_IFR_R_RESERVED36_BIT)
/*-----------*/

#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_GROUP7_H_ */
