/**
 *
 * @file SYSCTL_RegisterDefines_PCLKCR0.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 4 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 4 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR0_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR0_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 7 PCLKCR0 *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_PCLKCR0_R_HRPWMENCLK_BIT ((uint16_t) 0U)

#define SYSCTL_PCLKCR0_HRPWMENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_HRPWMENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_HRPWMENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_HRPWMENCLK_MASK (SYSCTL_PCLKCR0_HRPWMENCLK_MASK<< SYSCTL_PCLKCR0_R_HRPWMENCLK_BIT)
#define SYSCTL_PCLKCR0_R_HRPWMENCLK_DIS (SYSCTL_PCLKCR0_HRPWMENCLK_DIS << SYSCTL_PCLKCR0_R_HRPWMENCLK_BIT)
#define SYSCTL_PCLKCR0_R_HRPWMENCLK_ENA (SYSCTL_PCLKCR0_HRPWMENCLK_ENA << SYSCTL_PCLKCR0_R_HRPWMENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR0_R_TBCLKSYNC_BIT ((uint16_t) 2U)

#define SYSCTL_PCLKCR0_TBCLKSYNC_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_TBCLKSYNC_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_TBCLKSYNC_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_TBCLKSYNC_MASK (SYSCTL_PCLKCR0_TBCLKSYNC_MASK<< SYSCTL_PCLKCR0_R_TBCLKSYNC_BIT)
#define SYSCTL_PCLKCR0_R_TBCLKSYNC_DIS (SYSCTL_PCLKCR0_TBCLKSYNC_DIS << SYSCTL_PCLKCR0_R_TBCLKSYNC_BIT)
#define SYSCTL_PCLKCR0_R_TBCLKSYNC_ENA (SYSCTL_PCLKCR0_TBCLKSYNC_ENA << SYSCTL_PCLKCR0_R_TBCLKSYNC_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR0_R_ADCENCLK_BIT ((uint16_t) 3U)

#define SYSCTL_PCLKCR0_ADCENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_ADCENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_ADCENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_ADCENCLK_MASK (SYSCTL_PCLKCR0_ADCENCLK_MASK<< SYSCTL_PCLKCR0_R_ADCENCLK_BIT)
#define SYSCTL_PCLKCR0_R_ADCENCLK_DIS (SYSCTL_PCLKCR0_ADCENCLK_DIS << SYSCTL_PCLKCR0_R_ADCENCLK_BIT)
#define SYSCTL_PCLKCR0_R_ADCENCLK_ENA (SYSCTL_PCLKCR0_ADCENCLK_ENA << SYSCTL_PCLKCR0_R_ADCENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR0_R_I2CAENCLK_BIT ((uint16_t) 4U)

#define SYSCTL_PCLKCR0_I2CAENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_I2CAENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_I2CAENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_I2CAENCLK_MASK (SYSCTL_PCLKCR0_I2CAENCLK_MASK<< SYSCTL_PCLKCR0_R_I2CAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_I2CAENCLK_DIS (SYSCTL_PCLKCR0_I2CAENCLK_DIS << SYSCTL_PCLKCR0_R_I2CAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_I2CAENCLK_ENA (SYSCTL_PCLKCR0_I2CAENCLK_ENA << SYSCTL_PCLKCR0_R_I2CAENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR0_R_SPIAENCLK_BIT ((uint16_t) 8U)

#define SYSCTL_PCLKCR0_SPIAENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_SPIAENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_SPIAENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_SPIAENCLK_MASK (SYSCTL_PCLKCR0_SPIAENCLK_MASK<< SYSCTL_PCLKCR0_R_SPIAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_SPIAENCLK_DIS (SYSCTL_PCLKCR0_SPIAENCLK_DIS << SYSCTL_PCLKCR0_R_SPIAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_SPIAENCLK_ENA (SYSCTL_PCLKCR0_SPIAENCLK_ENA << SYSCTL_PCLKCR0_R_SPIAENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR0_R_SCIAENCLK_BIT ((uint16_t) 10U)

#define SYSCTL_PCLKCR0_SCIAENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR0_SCIAENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR0_SCIAENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR0_R_SCIAENCLK_MASK (SYSCTL_PCLKCR0_SCIAENCLK_MASK<< SYSCTL_PCLKCR0_R_SCIAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_SCIAENCLK_DIS (SYSCTL_PCLKCR0_SCIAENCLK_DIS << SYSCTL_PCLKCR0_R_SCIAENCLK_BIT)
#define SYSCTL_PCLKCR0_R_SCIAENCLK_ENA (SYSCTL_PCLKCR0_SCIAENCLK_ENA << SYSCTL_PCLKCR0_R_SCIAENCLK_BIT)
/*-----------*/


#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR0_H_ */
