/**
 *
 * @file SYSCTL_RegisterDefines_CLKCTL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 4 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 4 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_CLKCTL_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_CLKCTL_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 3 CLKCTL *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_CLKCTL_R_OSCCLKSRCSEL_BIT ((uint16_t) 0U)

#define SYSCTL_CLKCTL_OSCCLKSRCSEL_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_OSCCLKSRCSEL_OSC1CLK ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_OSCCLKSRCSEL_OSC2CLK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_OSCCLKSRCSEL_EXTCLK ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_OSCCLKSRCSEL_MASK (SYSCTL_CLKCTL_OSCCLKSRCSEL_MASK<< SYSCTL_CLKCTL_R_OSCCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_OSCCLKSRCSEL_OSC1CLK (SYSCTL_CLKCTL_OSCCLKSRCSEL_OSC1CLK << SYSCTL_CLKCTL_R_OSCCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_OSCCLKSRCSEL_OSC2CLK (SYSCTL_CLKCTL_OSCCLKSRCSEL_OSC2CLK << SYSCTL_CLKCTL_R_OSCCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_OSCCLKSRCSEL_EXTCLK (SYSCTL_CLKCTL_OSCCLKSRCSEL_EXTCLK << SYSCTL_CLKCTL_R_OSCCLKSRCSEL_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_BIT ((uint16_t) 1U)

#define SYSCTL_CLKCTL_OSCCLKSRC2SEL_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_OSCCLKSRC2SEL_EXTCLK ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_OSCCLKSRC2SEL_OSC2CLK ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_MASK (SYSCTL_CLKCTL_OSCCLKSRC2SEL_MASK<< SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_BIT)
#define SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_EXTCLK (SYSCTL_CLKCTL_OSCCLKSRC2SEL_EXTCLK << SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_BIT)
#define SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_OSC2CLK (SYSCTL_CLKCTL_OSCCLKSRC2SEL_OSC2CLK << SYSCTL_CLKCTL_R_OSCCLKSRC2SEL_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_WDCLKSRCSEL_BIT ((uint16_t) 2U)

#define SYSCTL_CLKCTL_WDCLKSRCSEL_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_WDCLKSRCSEL_OSC1CLK ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_WDCLKSRCSEL_OSC2CLK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_WDCLKSRCSEL_EXTCLK ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_WDCLKSRCSEL_MASK (SYSCTL_CLKCTL_WDCLKSRCSEL_MASK<< SYSCTL_CLKCTL_R_WDCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_WDCLKSRCSEL_OSC1CLK (SYSCTL_CLKCTL_WDCLKSRCSEL_OSC1CLK << SYSCTL_CLKCTL_R_WDCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_WDCLKSRCSEL_OSC2CLK (SYSCTL_CLKCTL_WDCLKSRCSEL_OSC2CLK << SYSCTL_CLKCTL_R_WDCLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_WDCLKSRCSEL_EXTCLK (SYSCTL_CLKCTL_WDCLKSRCSEL_EXTCLK << SYSCTL_CLKCTL_R_WDCLKSRCSEL_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT ((uint16_t) 3U)

#define SYSCTL_CLKCTL_TMR2CLKSRCSEL_MASK ((uint16_t) 0x0003U)
#define SYSCTL_CLKCTL_TMR2CLKSRCSEL_SYSCLKOUT ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_TMR2CLKSRCSEL_EXTCLK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_TMR2CLKSRCSEL_OSC1CLK ((uint16_t) 0x0002U)
#define SYSCTL_CLKCTL_TMR2CLKSRCSEL_OSC2CLK ((uint16_t) 0x0003U)

#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_MASK (SYSCTL_CLKCTL_TMR2CLKSRCSEL_MASK<< SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_SYSCLKOUT (SYSCTL_CLKCTL_TMR2CLKSRCSEL_SYSCLKOUT << SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_EXTCLK (SYSCTL_CLKCTL_TMR2CLKSRCSEL_EXTCLK << SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_OSC1CLK (SYSCTL_CLKCTL_TMR2CLKSRCSEL_OSC1CLK << SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_OSC2CLK (SYSCTL_CLKCTL_TMR2CLKSRCSEL_OSC2CLK << SYSCTL_CLKCTL_R_TMR2CLKSRCSEL_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT ((uint16_t) 5U)

#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_MASK ((uint16_t) 0x0007U)
#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV1 ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV2 ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV4 ((uint16_t) 0x0002U)
#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV8 ((uint16_t) 0x0003U)
#define SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV16 ((uint16_t) 0x0004U)

#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_MASK (SYSCTL_CLKCTL_TMR2CLKPRESCALE_MASK<< SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_DIV1 (SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV1 << SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_DIV2 (SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV2 << SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_DIV4 (SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV4 << SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_DIV8 (SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV8 << SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
#define SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_DIV16 (SYSCTL_CLKCTL_TMR2CLKPRESCALE_DIV16 << SYSCTL_CLKCTL_R_TMR2CLKPRESCALE_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_INTOSC1OFF_BIT ((uint16_t) 8U)

#define SYSCTL_CLKCTL_INTOSC1OFF_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_INTOSC1OFF_ON ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_INTOSC1OFF_OFF ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_INTOSC1OFF_MASK (SYSCTL_CLKCTL_INTOSC1OFF_MASK<< SYSCTL_CLKCTL_R_INTOSC1OFF_BIT)
#define SYSCTL_CLKCTL_R_INTOSC1OFF_ON (SYSCTL_CLKCTL_INTOSC1OFF_ON << SYSCTL_CLKCTL_R_INTOSC1OFF_BIT)
#define SYSCTL_CLKCTL_R_INTOSC1OFF_OFF (SYSCTL_CLKCTL_INTOSC1OFF_OFF << SYSCTL_CLKCTL_R_INTOSC1OFF_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_INTOSC1HALTI_BIT ((uint16_t) 9U)

#define SYSCTL_CLKCTL_INTOSC1HALTI_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_INTOSC1HALTI_OFF ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_INTOSC1HALTI_ACTIVE ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_INTOSC1HALTI_MASK (SYSCTL_CLKCTL_INTOSC1HALTI_MASK<< SYSCTL_CLKCTL_R_INTOSC1HALTI_BIT)
#define SYSCTL_CLKCTL_R_INTOSC1HALTI_OFF (SYSCTL_CLKCTL_INTOSC1HALTI_OFF << SYSCTL_CLKCTL_R_INTOSC1HALTI_BIT)
#define SYSCTL_CLKCTL_R_INTOSC1HALTI_ACTIVE (SYSCTL_CLKCTL_INTOSC1HALTI_ACTIVE << SYSCTL_CLKCTL_R_INTOSC1HALTI_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_INTOSC2OFF_BIT ((uint16_t) 10U)

#define SYSCTL_CLKCTL_INTOSC2OFF_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_INTOSC2OFF_ON ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_INTOSC2OFF_OFF ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_INTOSC2OFF_MASK (SYSCTL_CLKCTL_INTOSC2OFF_MASK<< SYSCTL_CLKCTL_R_INTOSC2OFF_BIT)
#define SYSCTL_CLKCTL_R_INTOSC2OFF_ON (SYSCTL_CLKCTL_INTOSC2OFF_ON << SYSCTL_CLKCTL_R_INTOSC2OFF_BIT)
#define SYSCTL_CLKCTL_R_INTOSC2OFF_OFF (SYSCTL_CLKCTL_INTOSC2OFF_OFF << SYSCTL_CLKCTL_R_INTOSC2OFF_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_INTOSC2HALTI_BIT ((uint16_t) 11U)

#define SYSCTL_CLKCTL_INTOSC2HALTI_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_INTOSC2HALTI_OFF ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_INTOSC2HALTI_ACTIVE ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_INTOSC2HALTI_MASK (SYSCTL_CLKCTL_INTOSC2HALTI_MASK<< SYSCTL_CLKCTL_R_INTOSC2HALTI_BIT)
#define SYSCTL_CLKCTL_R_INTOSC2HALTI_OFF (SYSCTL_CLKCTL_INTOSC2HALTI_OFF << SYSCTL_CLKCTL_R_INTOSC2HALTI_BIT)
#define SYSCTL_CLKCTL_R_INTOSC2HALTI_ACTIVE (SYSCTL_CLKCTL_INTOSC2HALTI_ACTIVE << SYSCTL_CLKCTL_R_INTOSC2HALTI_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_WDHALTI_BIT ((uint16_t) 12U)

#define SYSCTL_CLKCTL_WDHALTI_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_WDHALTI_OFF ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_WDHALTI_ACTIVE ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_WDHALTI_MASK (SYSCTL_CLKCTL_WDHALTI_MASK<< SYSCTL_CLKCTL_R_WDHALTI_BIT)
#define SYSCTL_CLKCTL_R_WDHALTI_OFF (SYSCTL_CLKCTL_WDHALTI_OFF << SYSCTL_CLKCTL_R_WDHALTI_BIT)
#define SYSCTL_CLKCTL_R_WDHALTI_ACTIVE (SYSCTL_CLKCTL_WDHALTI_ACTIVE << SYSCTL_CLKCTL_R_WDHALTI_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_XCLKINOFF_BIT ((uint16_t) 13U)

#define SYSCTL_CLKCTL_XCLKINOFF_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_XCLKINOFF_ON ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_XCLKINOFF_OFF ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_XCLKINOFF_MASK (SYSCTL_CLKCTL_XCLKINOFF_MASK<< SYSCTL_CLKCTL_R_XCLKINOFF_BIT)
#define SYSCTL_CLKCTL_R_XCLKINOFF_ON (SYSCTL_CLKCTL_XCLKINOFF_ON << SYSCTL_CLKCTL_R_XCLKINOFF_BIT)
#define SYSCTL_CLKCTL_R_XCLKINOFF_OFF (SYSCTL_CLKCTL_XCLKINOFF_OFF << SYSCTL_CLKCTL_R_XCLKINOFF_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_XTALOSCOFF_BIT ((uint16_t) 14U)

#define SYSCTL_CLKCTL_XTALOSCOFF_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_XTALOSCOFF_ON ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_XTALOSCOFF_OFF ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_XTALOSCOFF_MASK (SYSCTL_CLKCTL_XTALOSCOFF_MASK<< SYSCTL_CLKCTL_R_XTALOSCOFF_BIT)
#define SYSCTL_CLKCTL_R_XTALOSCOFF_ON (SYSCTL_CLKCTL_XTALOSCOFF_ON << SYSCTL_CLKCTL_R_XTALOSCOFF_BIT)
#define SYSCTL_CLKCTL_R_XTALOSCOFF_OFF (SYSCTL_CLKCTL_XTALOSCOFF_OFF << SYSCTL_CLKCTL_R_XTALOSCOFF_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_CLKCTL_R_NMIRESETSEL_BIT ((uint16_t) 15U)

#define SYSCTL_CLKCTL_NMIRESETSEL_MASK ((uint16_t) 0x0001U)
#define SYSCTL_CLKCTL_NMIRESETSEL_DIRECT ((uint16_t) 0x0000U)
#define SYSCTL_CLKCTL_NMIRESETSEL_DELAYED ((uint16_t) 0x0001U)

#define SYSCTL_CLKCTL_R_NMIRESETSEL_MASK (SYSCTL_CLKCTL_NMIRESETSEL_MASK<< SYSCTL_CLKCTL_R_NMIRESETSEL_BIT)
#define SYSCTL_CLKCTL_R_NMIRESETSEL_DIRECT (SYSCTL_CLKCTL_NMIRESETSEL_DIRECT << SYSCTL_CLKCTL_R_NMIRESETSEL_BIT)
#define SYSCTL_CLKCTL_R_NMIRESETSEL_DELAYED (SYSCTL_CLKCTL_NMIRESETSEL_DELAYED << SYSCTL_CLKCTL_R_NMIRESETSEL_BIT)
/*-----------*/


#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_CLKCTL_H_ */
