/**
 *
 * @file SYSCTL_RegisterDefines_PCLKCR3.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 4 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 4 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR3_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR3_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 10 PCLKCR3 *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_PCLKCR3_R_COMP1ENCLK_BIT ((uint16_t) 0U)

#define SYSCTL_PCLKCR3_COMP1ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_COMP1ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_COMP1ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_COMP1ENCLK_MASK (SYSCTL_PCLKCR3_COMP1ENCLK_MASK<< SYSCTL_PCLKCR3_R_COMP1ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_COMP1ENCLK_DIS (SYSCTL_PCLKCR3_COMP1ENCLK_DIS << SYSCTL_PCLKCR3_R_COMP1ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_COMP1ENCLK_ENA (SYSCTL_PCLKCR3_COMP1ENCLK_ENA << SYSCTL_PCLKCR3_R_COMP1ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR3_R_COMP2ENCLK_BIT ((uint16_t) 1U)

#define SYSCTL_PCLKCR3_COMP2ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_COMP2ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_COMP2ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_COMP2ENCLK_MASK (SYSCTL_PCLKCR3_COMP2ENCLK_MASK<< SYSCTL_PCLKCR3_R_COMP2ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_COMP2ENCLK_DIS (SYSCTL_PCLKCR3_COMP2ENCLK_DIS << SYSCTL_PCLKCR3_R_COMP2ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_COMP2ENCLK_ENA (SYSCTL_PCLKCR3_COMP2ENCLK_ENA << SYSCTL_PCLKCR3_R_COMP2ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_BIT ((uint16_t) 8U)

#define SYSCTL_PCLKCR3_CPUTIMER0ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_CPUTIMER0ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_CPUTIMER0ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_MASK (SYSCTL_PCLKCR3_CPUTIMER0ENCLK_MASK<< SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_DIS (SYSCTL_PCLKCR3_CPUTIMER0ENCLK_DIS << SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_ENA (SYSCTL_PCLKCR3_CPUTIMER0ENCLK_ENA << SYSCTL_PCLKCR3_R_CPUTIMER0ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_BIT ((uint16_t) 9U)

#define SYSCTL_PCLKCR3_CPUTIMER1ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_CPUTIMER1ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_CPUTIMER1ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_MASK (SYSCTL_PCLKCR3_CPUTIMER1ENCLK_MASK<< SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_DIS (SYSCTL_PCLKCR3_CPUTIMER1ENCLK_DIS << SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_ENA (SYSCTL_PCLKCR3_CPUTIMER1ENCLK_ENA << SYSCTL_PCLKCR3_R_CPUTIMER1ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_BIT ((uint16_t) 10U)

#define SYSCTL_PCLKCR3_CPUTIMER2ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_CPUTIMER2ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_CPUTIMER2ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_MASK (SYSCTL_PCLKCR3_CPUTIMER2ENCLK_MASK<< SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_DIS (SYSCTL_PCLKCR3_CPUTIMER2ENCLK_DIS << SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_BIT)
#define SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_ENA (SYSCTL_PCLKCR3_CPUTIMER2ENCLK_ENA << SYSCTL_PCLKCR3_R_CPUTIMER2ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR3_R_GPIOINENCLK_BIT ((uint16_t) 13U)

#define SYSCTL_PCLKCR3_GPIOINENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR3_GPIOINENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR3_GPIOINENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR3_R_GPIOINENCLK_MASK (SYSCTL_PCLKCR3_GPIOINENCLK_MASK<< SYSCTL_PCLKCR3_R_GPIOINENCLK_BIT)
#define SYSCTL_PCLKCR3_R_GPIOINENCLK_DIS (SYSCTL_PCLKCR3_GPIOINENCLK_DIS << SYSCTL_PCLKCR3_R_GPIOINENCLK_BIT)
#define SYSCTL_PCLKCR3_R_GPIOINENCLK_ENA (SYSCTL_PCLKCR3_GPIOINENCLK_ENA << SYSCTL_PCLKCR3_R_GPIOINENCLK_BIT)
/*-----------*/



#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR3_H_ */
