/**
 *
 * @file SYSCTL_RegisterDefines_PCLKCR1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 4 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 4 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR1_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR1_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 8 PCLKCR1 *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_PCLKCR1_R_EPWM1ENCLK_BIT ((uint16_t) 0U)

#define SYSCTL_PCLKCR1_EPWM1ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR1_EPWM1ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR1_EPWM1ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR1_R_EPWM1ENCLK_MASK (SYSCTL_PCLKCR1_EPWM1ENCLK_MASK<< SYSCTL_PCLKCR1_R_EPWM1ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM1ENCLK_DIS (SYSCTL_PCLKCR1_EPWM1ENCLK_DIS << SYSCTL_PCLKCR1_R_EPWM1ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM1ENCLK_ENA (SYSCTL_PCLKCR1_EPWM1ENCLK_ENA << SYSCTL_PCLKCR1_R_EPWM1ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR1_R_EPWM2ENCLK_BIT ((uint16_t) 1U)

#define SYSCTL_PCLKCR1_EPWM2ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR1_EPWM2ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR1_EPWM2ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR1_R_EPWM2ENCLK_MASK (SYSCTL_PCLKCR1_EPWM2ENCLK_MASK<< SYSCTL_PCLKCR1_R_EPWM2ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM2ENCLK_DIS (SYSCTL_PCLKCR1_EPWM2ENCLK_DIS << SYSCTL_PCLKCR1_R_EPWM2ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM2ENCLK_ENA (SYSCTL_PCLKCR1_EPWM2ENCLK_ENA << SYSCTL_PCLKCR1_R_EPWM2ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR1_R_EPWM3ENCLK_BIT ((uint16_t) 2U)

#define SYSCTL_PCLKCR1_EPWM3ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR1_EPWM3ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR1_EPWM3ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR1_R_EPWM3ENCLK_MASK (SYSCTL_PCLKCR1_EPWM3ENCLK_MASK<< SYSCTL_PCLKCR1_R_EPWM3ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM3ENCLK_DIS (SYSCTL_PCLKCR1_EPWM3ENCLK_DIS << SYSCTL_PCLKCR1_R_EPWM3ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM3ENCLK_ENA (SYSCTL_PCLKCR1_EPWM3ENCLK_ENA << SYSCTL_PCLKCR1_R_EPWM3ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR1_R_EPWM4ENCLK_BIT ((uint16_t) 3U)

#define SYSCTL_PCLKCR1_EPWM4ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR1_EPWM4ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR1_EPWM4ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR1_R_EPWM4ENCLK_MASK (SYSCTL_PCLKCR1_EPWM4ENCLK_MASK<< SYSCTL_PCLKCR1_R_EPWM4ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM4ENCLK_DIS (SYSCTL_PCLKCR1_EPWM4ENCLK_DIS << SYSCTL_PCLKCR1_R_EPWM4ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_EPWM4ENCLK_ENA (SYSCTL_PCLKCR1_EPWM4ENCLK_ENA << SYSCTL_PCLKCR1_R_EPWM4ENCLK_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_PCLKCR1_R_ECAP1ENCLK_BIT ((uint16_t) 8U)

#define SYSCTL_PCLKCR1_ECAP1ENCLK_MASK ((uint16_t) 0x0001U)
#define SYSCTL_PCLKCR1_ECAP1ENCLK_DIS ((uint16_t) 0x0000U)
#define SYSCTL_PCLKCR1_ECAP1ENCLK_ENA ((uint16_t) 0x0001U)

#define SYSCTL_PCLKCR1_R_ECAP1ENCLK_MASK (SYSCTL_PCLKCR1_ECAP1ENCLK_MASK<< SYSCTL_PCLKCR1_R_ECAP1ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_ECAP1ENCLK_DIS (SYSCTL_PCLKCR1_ECAP1ENCLK_DIS << SYSCTL_PCLKCR1_R_ECAP1ENCLK_BIT)
#define SYSCTL_PCLKCR1_R_ECAP1ENCLK_ENA (SYSCTL_PCLKCR1_ECAP1ENCLK_ENA << SYSCTL_PCLKCR1_R_ECAP1ENCLK_BIT)
/*-----------*/

#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_PCLKCR1_H_ */
