/**
 *
 * @file SYSCTL_RegisterDefines_INTOSCnTRIM.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 4 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 4 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_INTOSCNTRIM_H_
#define DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_INTOSCNTRIM_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 5 INTOSCnTRIM *********************************************
 ******************************************************************************************/
/*-----------*/
#define SYSCTL_INTOSCnTRIM_R_COARSETRIM_BIT ((uint16_t) 0U)
#define SYSCTL_INTOSC1TRIM_R_COARSETRIM_BIT SYSCTL_INTOSCnTRIM_R_COARSETRIM_BIT
#define SYSCTL_INTOSC2TRIM_R_COARSETRIM_BIT SYSCTL_INTOSCnTRIM_R_COARSETRIM_BIT

#define SYSCTL_INTOSCnTRIM_COARSETRIM_MASK ((uint16_t) 0x00FFU)
#define SYSCTL_INTOSC1TRIM_COARSETRIM_MASK SYSCTL_INTOSCnTRIM_COARSETRIM_MASK
#define SYSCTL_INTOSC2TRIM_COARSETRIM_MASK SYSCTL_INTOSCnTRIM_COARSETRIM_MASK

#define SYSCTL_INTOSCnTRIM_R_COARSETRIM_MASK (SYSCTL_INTOSCnTRIM_COARSETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSCnTRIM_BIT)
#define SYSCTL_INTOSC1TRIM_R_COARSETRIM_MASK (SYSCTL_INTOSC1TRIM_COARSETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSC1TRIM_BIT)
#define SYSCTL_INTOSC2TRIM_R_COARSETRIM_MASK (SYSCTL_INTOSC2TRIM_COARSETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSC2TRIM_BIT)
/*-----------*/

/*-----------*/
#define SYSCTL_INTOSCnTRIM_R_FINETRIM_BIT ((uint16_t) 9U)
#define SYSCTL_INTOSC1TRIM_R_FINETRIM_BIT SYSCTL_INTOSCnTRIM_R_FINETRIM_BIT
#define SYSCTL_INTOSC2TRIM_R_FINETRIM_BIT SYSCTL_INTOSCnTRIM_R_FINETRIM_BIT

#define SYSCTL_INTOSCnTRIM_FINETRIM_MASK ((uint16_t) 0x003FU)
#define SYSCTL_INTOSC1TRIM_FINETRIM_MASK SYSCTL_INTOSCnTRIM_FINETRIM_MASK
#define SYSCTL_INTOSC2TRIM_FINETRIM_MASK SYSCTL_INTOSCnTRIM_FINETRIM_MASK

#define SYSCTL_INTOSCnTRIM_R_FINETRIM_MASK (SYSCTL_INTOSCnTRIM_FINETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSCnTRIM_BIT)
#define SYSCTL_INTOSC1TRIM_R_FINETRIM_MASK (SYSCTL_INTOSC1TRIM_FINETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSC1TRIM_BIT)
#define SYSCTL_INTOSC2TRIM_R_FINETRIM_MASK (SYSCTL_INTOSC2TRIM_FINETRIM_MASK<< SYSCTL_INTOSCnTRIM_R_INTOSC2TRIM_BIT)
/*-----------*/


#endif /* DRIVERLIB_SYSCTL_PERIPHERAL_REGISTERDEFINES_XHEADER_SYSCTL_REGISTERDEFINES_INTOSCNTRIM_H_ */
