/**
 *
 * @file GPIO_RegisterDefines_PUD.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_PUD_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_PUD_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 7 PUD *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_CONTROL_PUD_R_PIN_BIT    (0UL)

#define GPIO_CONTROL_PUD_PIN_MASK    ((uint32_t) 0xFFFFFFFFUL)
#define GPIO_CONTROL_PUD_PIN_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN_NONE    ((uint32_t) 0xFFFFFFFFUL)

#define GPIO_CONTROL_PUD_R_PIN_MASK    (GPIO_CONTROL_PUD_PIN_MASK<< GPIO_CONTROL_PUD_R_PIN_BIT)
#define GPIO_CONTROL_PUD_R_PIN_PULLUP    (GPIO_CONTROL_PUD_PIN_PULLUP<< GPIO_CONTROL_PUD_R_PIN_BIT)
#define GPIO_CONTROL_PUD_R_PIN_NONE    (GPIO_CONTROL_PUD_PIN_NONE<< GPIO_CONTROL_PUD_R_PIN_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN0_BIT    (0UL)

#define GPIO_CONTROL_PUD_PIN0_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN0_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN0_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN0_MASK    (GPIO_CONTROL_PUD_PIN0_MASK<< GPIO_CONTROL_PUD_R_PIN0_BIT)
#define GPIO_CONTROL_PUD_R_PIN0_PULLUP    (GPIO_CONTROL_PUD_PIN0_PULLUP<< GPIO_CONTROL_PUD_R_PIN0_BIT)
#define GPIO_CONTROL_PUD_R_PIN0_NONE    (GPIO_CONTROL_PUD_PIN0_NONE<< GPIO_CONTROL_PUD_R_PIN0_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN1_BIT    (1UL)

#define GPIO_CONTROL_PUD_PIN1_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN1_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN1_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN1_MASK    (GPIO_CONTROL_PUD_PIN1_MASK<< GPIO_CONTROL_PUD_R_PIN1_BIT)
#define GPIO_CONTROL_PUD_R_PIN1_PULLUP    (GPIO_CONTROL_PUD_PIN1_PULLUP<< GPIO_CONTROL_PUD_R_PIN1_BIT)
#define GPIO_CONTROL_PUD_R_PIN1_NONE    (GPIO_CONTROL_PUD_PIN1_NONE<< GPIO_CONTROL_PUD_R_PIN1_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN2_BIT    (2UL)

#define GPIO_CONTROL_PUD_PIN2_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN2_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN2_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN2_MASK    (GPIO_CONTROL_PUD_PIN2_MASK<< GPIO_CONTROL_PUD_R_PIN2_BIT)
#define GPIO_CONTROL_PUD_R_PIN2_PULLUP    (GPIO_CONTROL_PUD_PIN2_PULLUP<< GPIO_CONTROL_PUD_R_PIN2_BIT)
#define GPIO_CONTROL_PUD_R_PIN2_NONE    (GPIO_CONTROL_PUD_PIN2_NONE<< GPIO_CONTROL_PUD_R_PIN2_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN3_BIT    (3UL)

#define GPIO_CONTROL_PUD_PIN3_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN3_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN3_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN3_MASK    (GPIO_CONTROL_PUD_PIN3_MASK<< GPIO_CONTROL_PUD_R_PIN3_BIT)
#define GPIO_CONTROL_PUD_R_PIN3_PULLUP    (GPIO_CONTROL_PUD_PIN3_PULLUP<< GPIO_CONTROL_PUD_R_PIN3_BIT)
#define GPIO_CONTROL_PUD_R_PIN3_NONE    (GPIO_CONTROL_PUD_PIN3_NONE<< GPIO_CONTROL_PUD_R_PIN3_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN4_BIT    (4UL)

#define GPIO_CONTROL_PUD_PIN4_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN4_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN4_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN4_MASK    (GPIO_CONTROL_PUD_PIN4_MASK<< GPIO_CONTROL_PUD_R_PIN4_BIT)
#define GPIO_CONTROL_PUD_R_PIN4_PULLUP    (GPIO_CONTROL_PUD_PIN4_PULLUP<< GPIO_CONTROL_PUD_R_PIN4_BIT)
#define GPIO_CONTROL_PUD_R_PIN4_NONE    (GPIO_CONTROL_PUD_PIN4_NONE<< GPIO_CONTROL_PUD_R_PIN4_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN5_BIT    (5UL)

#define GPIO_CONTROL_PUD_PIN5_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN5_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN5_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN5_MASK    (GPIO_CONTROL_PUD_PIN5_MASK<< GPIO_CONTROL_PUD_R_PIN5_BIT)
#define GPIO_CONTROL_PUD_R_PIN5_PULLUP    (GPIO_CONTROL_PUD_PIN5_PULLUP<< GPIO_CONTROL_PUD_R_PIN5_BIT)
#define GPIO_CONTROL_PUD_R_PIN5_NONE    (GPIO_CONTROL_PUD_PIN5_NONE<< GPIO_CONTROL_PUD_R_PIN5_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN6_BIT    (6UL)

#define GPIO_CONTROL_PUD_PIN6_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN6_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN6_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN6_MASK    (GPIO_CONTROL_PUD_PIN6_MASK<< GPIO_CONTROL_PUD_R_PIN6_BIT)
#define GPIO_CONTROL_PUD_R_PIN6_PULLUP    (GPIO_CONTROL_PUD_PIN6_PULLUP<< GPIO_CONTROL_PUD_R_PIN6_BIT)
#define GPIO_CONTROL_PUD_R_PIN6_NONE    (GPIO_CONTROL_PUD_PIN6_NONE<< GPIO_CONTROL_PUD_R_PIN6_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN7_BIT    (7UL)

#define GPIO_CONTROL_PUD_PIN7_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN7_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN7_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN7_MASK    (GPIO_CONTROL_PUD_PIN7_MASK<< GPIO_CONTROL_PUD_R_PIN7_BIT)
#define GPIO_CONTROL_PUD_R_PIN7_PULLUP    (GPIO_CONTROL_PUD_PIN7_PULLUP<< GPIO_CONTROL_PUD_R_PIN7_BIT)
#define GPIO_CONTROL_PUD_R_PIN7_NONE    (GPIO_CONTROL_PUD_PIN7_NONE<< GPIO_CONTROL_PUD_R_PIN7_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN8_BIT    (8UL)

#define GPIO_CONTROL_PUD_PIN8_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN8_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN8_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN8_MASK    (GPIO_CONTROL_PUD_PIN8_MASK<< GPIO_CONTROL_PUD_R_PIN8_BIT)
#define GPIO_CONTROL_PUD_R_PIN8_PULLUP    (GPIO_CONTROL_PUD_PIN8_PULLUP<< GPIO_CONTROL_PUD_R_PIN8_BIT)
#define GPIO_CONTROL_PUD_R_PIN8_NONE    (GPIO_CONTROL_PUD_PIN8_NONE<< GPIO_CONTROL_PUD_R_PIN8_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN9_BIT    (9UL)

#define GPIO_CONTROL_PUD_PIN9_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN9_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN9_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN9_MASK    (GPIO_CONTROL_PUD_PIN9_MASK<< GPIO_CONTROL_PUD_R_PIN9_BIT)
#define GPIO_CONTROL_PUD_R_PIN9_PULLUP    (GPIO_CONTROL_PUD_PIN9_PULLUP<< GPIO_CONTROL_PUD_R_PIN9_BIT)
#define GPIO_CONTROL_PUD_R_PIN9_NONE    (GPIO_CONTROL_PUD_PIN9_NONE<< GPIO_CONTROL_PUD_R_PIN9_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN10_BIT    (10UL)

#define GPIO_CONTROL_PUD_PIN10_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN10_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN10_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN10_MASK    (GPIO_CONTROL_PUD_PIN10_MASK<< GPIO_CONTROL_PUD_R_PIN10_BIT)
#define GPIO_CONTROL_PUD_R_PIN10_PULLUP    (GPIO_CONTROL_PUD_PIN10_PULLUP<< GPIO_CONTROL_PUD_R_PIN10_BIT)
#define GPIO_CONTROL_PUD_R_PIN10_NONE    (GPIO_CONTROL_PUD_PIN10_NONE<< GPIO_CONTROL_PUD_R_PIN10_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN11_BIT    (11UL)

#define GPIO_CONTROL_PUD_PIN11_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN11_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN11_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN11_MASK    (GPIO_CONTROL_PUD_PIN11_MASK<< GPIO_CONTROL_PUD_R_PIN11_BIT)
#define GPIO_CONTROL_PUD_R_PIN11_PULLUP    (GPIO_CONTROL_PUD_PIN11_PULLUP<< GPIO_CONTROL_PUD_R_PIN11_BIT)
#define GPIO_CONTROL_PUD_R_PIN11_NONE    (GPIO_CONTROL_PUD_PIN11_NONE<< GPIO_CONTROL_PUD_R_PIN11_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN12_BIT    (12UL)

#define GPIO_CONTROL_PUD_PIN12_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN12_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN12_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN12_MASK    (GPIO_CONTROL_PUD_PIN12_MASK<< GPIO_CONTROL_PUD_R_PIN12_BIT)
#define GPIO_CONTROL_PUD_R_PIN12_PULLUP    (GPIO_CONTROL_PUD_PIN12_PULLUP<< GPIO_CONTROL_PUD_R_PIN12_BIT)
#define GPIO_CONTROL_PUD_R_PIN12_NONE    (GPIO_CONTROL_PUD_PIN12_NONE<< GPIO_CONTROL_PUD_R_PIN12_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN13_BIT    (13UL)

#define GPIO_CONTROL_PUD_PIN13_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN13_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN13_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN13_MASK    (GPIO_CONTROL_PUD_PIN13_MASK<< GPIO_CONTROL_PUD_R_PIN13_BIT)
#define GPIO_CONTROL_PUD_R_PIN13_PULLUP    (GPIO_CONTROL_PUD_PIN13_PULLUP<< GPIO_CONTROL_PUD_R_PIN13_BIT)
#define GPIO_CONTROL_PUD_R_PIN13_NONE    (GPIO_CONTROL_PUD_PIN13_NONE<< GPIO_CONTROL_PUD_R_PIN13_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN14_BIT    (14UL)

#define GPIO_CONTROL_PUD_PIN14_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN14_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN14_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN14_MASK    (GPIO_CONTROL_PUD_PIN14_MASK<< GPIO_CONTROL_PUD_R_PIN14_BIT)
#define GPIO_CONTROL_PUD_R_PIN14_PULLUP    (GPIO_CONTROL_PUD_PIN14_PULLUP<< GPIO_CONTROL_PUD_R_PIN14_BIT)
#define GPIO_CONTROL_PUD_R_PIN14_NONE    (GPIO_CONTROL_PUD_PIN14_NONE<< GPIO_CONTROL_PUD_R_PIN14_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN15_BIT    (15UL)

#define GPIO_CONTROL_PUD_PIN15_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN15_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN15_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN15_MASK    (GPIO_CONTROL_PUD_PIN15_MASK<< GPIO_CONTROL_PUD_R_PIN15_BIT)
#define GPIO_CONTROL_PUD_R_PIN15_PULLUP    (GPIO_CONTROL_PUD_PIN15_PULLUP<< GPIO_CONTROL_PUD_R_PIN15_BIT)
#define GPIO_CONTROL_PUD_R_PIN15_NONE    (GPIO_CONTROL_PUD_PIN15_NONE<< GPIO_CONTROL_PUD_R_PIN15_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN16_BIT    (16UL)

#define GPIO_CONTROL_PUD_PIN16_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN16_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN16_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN16_MASK    (GPIO_CONTROL_PUD_PIN16_MASK<< GPIO_CONTROL_PUD_R_PIN16_BIT)
#define GPIO_CONTROL_PUD_R_PIN16_PULLUP    (GPIO_CONTROL_PUD_PIN16_PULLUP<< GPIO_CONTROL_PUD_R_PIN16_BIT)
#define GPIO_CONTROL_PUD_R_PIN16_NONE    (GPIO_CONTROL_PUD_PIN16_NONE<< GPIO_CONTROL_PUD_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN17_BIT    (17UL)

#define GPIO_CONTROL_PUD_PIN17_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN17_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN17_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN17_MASK    (GPIO_CONTROL_PUD_PIN17_MASK<< GPIO_CONTROL_PUD_R_PIN17_BIT)
#define GPIO_CONTROL_PUD_R_PIN17_PULLUP    (GPIO_CONTROL_PUD_PIN17_PULLUP<< GPIO_CONTROL_PUD_R_PIN17_BIT)
#define GPIO_CONTROL_PUD_R_PIN17_NONE    (GPIO_CONTROL_PUD_PIN17_NONE<< GPIO_CONTROL_PUD_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN18_BIT    (18UL)

#define GPIO_CONTROL_PUD_PIN18_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN18_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN18_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN18_MASK    (GPIO_CONTROL_PUD_PIN18_MASK<< GPIO_CONTROL_PUD_R_PIN18_BIT)
#define GPIO_CONTROL_PUD_R_PIN18_PULLUP    (GPIO_CONTROL_PUD_PIN18_PULLUP<< GPIO_CONTROL_PUD_R_PIN18_BIT)
#define GPIO_CONTROL_PUD_R_PIN18_NONE    (GPIO_CONTROL_PUD_PIN18_NONE<< GPIO_CONTROL_PUD_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN19_BIT    (19UL)

#define GPIO_CONTROL_PUD_PIN19_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN19_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN19_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN19_MASK    (GPIO_CONTROL_PUD_PIN19_MASK<< GPIO_CONTROL_PUD_R_PIN19_BIT)
#define GPIO_CONTROL_PUD_R_PIN19_PULLUP    (GPIO_CONTROL_PUD_PIN19_PULLUP<< GPIO_CONTROL_PUD_R_PIN19_BIT)
#define GPIO_CONTROL_PUD_R_PIN19_NONE    (GPIO_CONTROL_PUD_PIN19_NONE<< GPIO_CONTROL_PUD_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN20_BIT    (20UL)

#define GPIO_CONTROL_PUD_PIN20_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN20_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN20_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN20_MASK    (GPIO_CONTROL_PUD_PIN20_MASK<< GPIO_CONTROL_PUD_R_PIN20_BIT)
#define GPIO_CONTROL_PUD_R_PIN20_PULLUP    (GPIO_CONTROL_PUD_PIN20_PULLUP<< GPIO_CONTROL_PUD_R_PIN20_BIT)
#define GPIO_CONTROL_PUD_R_PIN20_NONE    (GPIO_CONTROL_PUD_PIN20_NONE<< GPIO_CONTROL_PUD_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN21_BIT    (21UL)

#define GPIO_CONTROL_PUD_PIN21_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN21_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN21_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN21_MASK    (GPIO_CONTROL_PUD_PIN21_MASK<< GPIO_CONTROL_PUD_R_PIN21_BIT)
#define GPIO_CONTROL_PUD_R_PIN21_PULLUP    (GPIO_CONTROL_PUD_PIN21_PULLUP<< GPIO_CONTROL_PUD_R_PIN21_BIT)
#define GPIO_CONTROL_PUD_R_PIN21_NONE    (GPIO_CONTROL_PUD_PIN21_NONE<< GPIO_CONTROL_PUD_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN22_BIT    (22UL)

#define GPIO_CONTROL_PUD_PIN22_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN22_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN22_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN22_MASK    (GPIO_CONTROL_PUD_PIN22_MASK<< GPIO_CONTROL_PUD_R_PIN22_BIT)
#define GPIO_CONTROL_PUD_R_PIN22_PULLUP    (GPIO_CONTROL_PUD_PIN22_PULLUP<< GPIO_CONTROL_PUD_R_PIN22_BIT)
#define GPIO_CONTROL_PUD_R_PIN22_NONE    (GPIO_CONTROL_PUD_PIN22_NONE<< GPIO_CONTROL_PUD_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN23_BIT    (23UL)

#define GPIO_CONTROL_PUD_PIN23_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN23_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN23_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN23_MASK    (GPIO_CONTROL_PUD_PIN23_MASK<< GPIO_CONTROL_PUD_R_PIN23_BIT)
#define GPIO_CONTROL_PUD_R_PIN23_PULLUP    (GPIO_CONTROL_PUD_PIN23_PULLUP<< GPIO_CONTROL_PUD_R_PIN23_BIT)
#define GPIO_CONTROL_PUD_R_PIN23_NONE    (GPIO_CONTROL_PUD_PIN23_NONE<< GPIO_CONTROL_PUD_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN24_BIT    (24UL)

#define GPIO_CONTROL_PUD_PIN24_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN24_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN24_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN24_MASK    (GPIO_CONTROL_PUD_PIN24_MASK<< GPIO_CONTROL_PUD_R_PIN24_BIT)
#define GPIO_CONTROL_PUD_R_PIN24_PULLUP    (GPIO_CONTROL_PUD_PIN24_PULLUP<< GPIO_CONTROL_PUD_R_PIN24_BIT)
#define GPIO_CONTROL_PUD_R_PIN24_NONE    (GPIO_CONTROL_PUD_PIN24_NONE<< GPIO_CONTROL_PUD_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN25_BIT    (25UL)

#define GPIO_CONTROL_PUD_PIN25_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN25_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN25_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN25_MASK    (GPIO_CONTROL_PUD_PIN25_MASK<< GPIO_CONTROL_PUD_R_PIN25_BIT)
#define GPIO_CONTROL_PUD_R_PIN25_PULLUP    (GPIO_CONTROL_PUD_PIN25_PULLUP<< GPIO_CONTROL_PUD_R_PIN25_BIT)
#define GPIO_CONTROL_PUD_R_PIN25_NONE    (GPIO_CONTROL_PUD_PIN25_NONE<< GPIO_CONTROL_PUD_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN26_BIT    (26UL)

#define GPIO_CONTROL_PUD_PIN26_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN26_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN26_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN26_MASK    (GPIO_CONTROL_PUD_PIN26_MASK<< GPIO_CONTROL_PUD_R_PIN26_BIT)
#define GPIO_CONTROL_PUD_R_PIN26_PULLUP    (GPIO_CONTROL_PUD_PIN26_PULLUP<< GPIO_CONTROL_PUD_R_PIN26_BIT)
#define GPIO_CONTROL_PUD_R_PIN26_NONE    (GPIO_CONTROL_PUD_PIN26_NONE<< GPIO_CONTROL_PUD_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN27_BIT    (27UL)

#define GPIO_CONTROL_PUD_PIN27_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN27_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN27_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN27_MASK    (GPIO_CONTROL_PUD_PIN27_MASK<< GPIO_CONTROL_PUD_R_PIN27_BIT)
#define GPIO_CONTROL_PUD_R_PIN27_PULLUP    (GPIO_CONTROL_PUD_PIN27_PULLUP<< GPIO_CONTROL_PUD_R_PIN27_BIT)
#define GPIO_CONTROL_PUD_R_PIN27_NONE    (GPIO_CONTROL_PUD_PIN27_NONE<< GPIO_CONTROL_PUD_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN28_BIT    (28UL)

#define GPIO_CONTROL_PUD_PIN28_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN28_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN28_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN28_MASK    (GPIO_CONTROL_PUD_PIN28_MASK<< GPIO_CONTROL_PUD_R_PIN28_BIT)
#define GPIO_CONTROL_PUD_R_PIN28_PULLUP    (GPIO_CONTROL_PUD_PIN28_PULLUP<< GPIO_CONTROL_PUD_R_PIN28_BIT)
#define GPIO_CONTROL_PUD_R_PIN28_NONE    (GPIO_CONTROL_PUD_PIN28_NONE<< GPIO_CONTROL_PUD_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN29_BIT    (29UL)

#define GPIO_CONTROL_PUD_PIN29_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN29_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN29_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN29_MASK    (GPIO_CONTROL_PUD_PIN29_MASK<< GPIO_CONTROL_PUD_R_PIN29_BIT)
#define GPIO_CONTROL_PUD_R_PIN29_PULLUP    (GPIO_CONTROL_PUD_PIN29_PULLUP<< GPIO_CONTROL_PUD_R_PIN29_BIT)
#define GPIO_CONTROL_PUD_R_PIN29_NONE    (GPIO_CONTROL_PUD_PIN29_NONE<< GPIO_CONTROL_PUD_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN30_BIT    (30UL)

#define GPIO_CONTROL_PUD_PIN30_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN30_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN30_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN30_MASK    (GPIO_CONTROL_PUD_PIN30_MASK<< GPIO_CONTROL_PUD_R_PIN30_BIT)
#define GPIO_CONTROL_PUD_R_PIN30_PULLUP    (GPIO_CONTROL_PUD_PIN30_PULLUP<< GPIO_CONTROL_PUD_R_PIN30_BIT)
#define GPIO_CONTROL_PUD_R_PIN30_NONE    (GPIO_CONTROL_PUD_PIN30_NONE<< GPIO_CONTROL_PUD_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_PUD_R_PIN31_BIT    (31UL)

#define GPIO_CONTROL_PUD_PIN31_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_PUD_PIN31_PULLUP    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_PUD_PIN31_NONE    ((uint32_t) 0x00000001UL)

#define GPIO_CONTROL_PUD_R_PIN31_MASK    (GPIO_CONTROL_PUD_PIN31_MASK<< GPIO_CONTROL_PUD_R_PIN31_BIT)
#define GPIO_CONTROL_PUD_R_PIN31_PULLUP    (GPIO_CONTROL_PUD_PIN31_PULLUP<< GPIO_CONTROL_PUD_R_PIN31_BIT)
#define GPIO_CONTROL_PUD_R_PIN31_NONE    (GPIO_CONTROL_PUD_PIN31_NONE<< GPIO_CONTROL_PUD_R_PIN31_BIT)
/*----------*/

#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_PUD_H_ */
