/**
 *
 * @file GPIO_RegisterDefines_QSEL1.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL1_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL1_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 2 QSEL_LOW *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT    (0UL)

#define GPIO_CONTROL_QSEL_LOW_PIN0_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN0_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN0_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN0_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN0_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN0_MASK    (GPIO_CONTROL_QSEL_LOW_PIN0_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN0_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN0_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN0_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN0_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN0_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN0_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN0_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN0_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN0_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT    (2UL)

#define GPIO_CONTROL_QSEL_LOW_PIN1_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN1_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN1_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN1_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN1_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN1_MASK    (GPIO_CONTROL_QSEL_LOW_PIN1_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN1_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN1_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN1_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN1_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN1_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN1_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN1_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN1_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN1_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT    (4UL)

#define GPIO_CONTROL_QSEL_LOW_PIN2_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN2_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN2_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN2_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN2_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN2_MASK    (GPIO_CONTROL_QSEL_LOW_PIN2_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN2_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN2_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN2_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN2_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN2_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN2_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN2_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN2_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN2_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT    (6UL)

#define GPIO_CONTROL_QSEL_LOW_PIN3_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN3_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN3_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN3_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN3_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN3_MASK    (GPIO_CONTROL_QSEL_LOW_PIN3_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN3_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN3_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN3_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN3_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN3_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN3_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN3_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN3_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN3_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT    (8UL)

#define GPIO_CONTROL_QSEL_LOW_PIN4_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN4_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN4_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN4_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN4_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN4_MASK    (GPIO_CONTROL_QSEL_LOW_PIN4_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN4_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN4_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN4_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN4_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN4_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN4_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN4_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN4_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN4_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT    (10UL)

#define GPIO_CONTROL_QSEL_LOW_PIN5_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN5_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN5_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN5_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN5_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN5_MASK    (GPIO_CONTROL_QSEL_LOW_PIN5_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN5_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN5_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN5_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN5_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN5_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN5_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN5_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN5_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN5_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT    (12UL)

#define GPIO_CONTROL_QSEL_LOW_PIN6_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN6_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN6_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN6_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN6_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN6_MASK    (GPIO_CONTROL_QSEL_LOW_PIN6_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN6_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN6_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN6_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN6_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN6_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN6_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN6_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN6_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN6_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT    (14UL)

#define GPIO_CONTROL_QSEL_LOW_PIN7_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN7_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN7_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN7_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN7_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN7_MASK    (GPIO_CONTROL_QSEL_LOW_PIN7_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN7_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN7_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN7_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN7_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN7_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN7_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN7_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN7_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN7_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT    (16UL)

#define GPIO_CONTROL_QSEL_LOW_PIN8_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN8_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN8_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN8_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN8_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN8_MASK    (GPIO_CONTROL_QSEL_LOW_PIN8_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN8_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN8_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN8_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN8_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN8_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN8_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN8_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN8_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN8_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT    (18UL)

#define GPIO_CONTROL_QSEL_LOW_PIN9_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN9_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN9_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN9_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN9_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN9_MASK    (GPIO_CONTROL_QSEL_LOW_PIN9_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN9_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN9_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN9_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN9_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN9_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN9_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN9_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN9_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN9_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT    (20UL)

#define GPIO_CONTROL_QSEL_LOW_PIN10_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN10_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN10_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN10_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN10_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN10_MASK    (GPIO_CONTROL_QSEL_LOW_PIN10_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN10_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN10_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN10_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN10_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN10_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN10_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN10_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN10_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN10_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT    (22UL)

#define GPIO_CONTROL_QSEL_LOW_PIN11_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN11_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN11_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN11_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN11_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN11_MASK    (GPIO_CONTROL_QSEL_LOW_PIN11_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN11_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN11_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN11_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN11_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN11_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN11_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN11_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN11_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN11_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT    (24UL)

#define GPIO_CONTROL_QSEL_LOW_PIN12_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN12_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN12_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN12_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN12_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN12_MASK    (GPIO_CONTROL_QSEL_LOW_PIN12_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN12_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN12_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN12_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN12_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN12_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN12_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN12_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN12_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN12_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT    (26UL)

#define GPIO_CONTROL_QSEL_LOW_PIN13_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN13_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN13_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN13_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN13_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN13_MASK    (GPIO_CONTROL_QSEL_LOW_PIN13_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN13_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN13_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN13_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN13_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN13_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN13_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN13_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN13_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN13_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT    (28UL)

#define GPIO_CONTROL_QSEL_LOW_PIN14_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN14_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN14_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN14_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN14_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN14_MASK    (GPIO_CONTROL_QSEL_LOW_PIN14_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN14_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN14_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN14_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN14_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN14_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN14_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN14_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN14_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN14_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT    (30UL)

#define GPIO_CONTROL_QSEL_LOW_PIN15_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_LOW_PIN15_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_LOW_PIN15_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_LOW_PIN15_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_LOW_PIN15_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_LOW_R_PIN15_MASK    (GPIO_CONTROL_QSEL_LOW_PIN15_MASK << GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN15_SYSCLK    (GPIO_CONTROL_QSEL_LOW_PIN15_SYSCLK << GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN15_2SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN15_2SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN15_5SAMPLES    (GPIO_CONTROL_QSEL_LOW_PIN15_5SAMPLES << GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT)
#define GPIO_CONTROL_QSEL_LOW_R_PIN15_ASYNC    (GPIO_CONTROL_QSEL_LOW_PIN15_ASYNC << GPIO_CONTROL_QSEL_LOW_R_PIN15_BIT)
/*----------*/

#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL1_H_ */
