/**
 *
 * @file GPIO_RegisterDefines_TOGGLE.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_TOGGLE_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_TOGGLE_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 6 TOGGLE *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN_BIT    (0UL)

#define GPIO_DATA_TOGGLE_PIN_MASK    ((uint32_t) 0xFFFFFFFFUL)
#define GPIO_DATA_TOGGLE_PIN_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN_TOGGLE    ((uint32_t) 0xFFFFFFFFUL)

#define GPIO_DATA_TOGGLE_R_PIN_MASK    (GPIO_DATA_TOGGLE_PIN_MASK<< GPIO_DATA_TOGGLE_R_PIN_BIT)
#define GPIO_DATA_TOGGLE_R_PIN_NA    (GPIO_DATA_TOGGLE_PIN_NA<< GPIO_DATA_TOGGLE_R_PIN_BIT)
#define GPIO_DATA_TOGGLE_R_PIN_TOGGLE    (GPIO_DATA_TOGGLE_PIN_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN0_BIT    (0UL)

#define GPIO_DATA_TOGGLE_PIN0_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN0_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN0_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN0_MASK    (GPIO_DATA_TOGGLE_PIN0_MASK<< GPIO_DATA_TOGGLE_R_PIN0_BIT)
#define GPIO_DATA_TOGGLE_R_PIN0_NA    (GPIO_DATA_TOGGLE_PIN0_NA<< GPIO_DATA_TOGGLE_R_PIN0_BIT)
#define GPIO_DATA_TOGGLE_R_PIN0_TOGGLE    (GPIO_DATA_TOGGLE_PIN0_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN0_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN1_BIT    (1UL)

#define GPIO_DATA_TOGGLE_PIN1_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN1_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN1_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN1_MASK    (GPIO_DATA_TOGGLE_PIN1_MASK<< GPIO_DATA_TOGGLE_R_PIN1_BIT)
#define GPIO_DATA_TOGGLE_R_PIN1_NA    (GPIO_DATA_TOGGLE_PIN1_NA<< GPIO_DATA_TOGGLE_R_PIN1_BIT)
#define GPIO_DATA_TOGGLE_R_PIN1_TOGGLE    (GPIO_DATA_TOGGLE_PIN1_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN1_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN2_BIT    (2UL)

#define GPIO_DATA_TOGGLE_PIN2_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN2_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN2_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN2_MASK    (GPIO_DATA_TOGGLE_PIN2_MASK<< GPIO_DATA_TOGGLE_R_PIN2_BIT)
#define GPIO_DATA_TOGGLE_R_PIN2_NA    (GPIO_DATA_TOGGLE_PIN2_NA<< GPIO_DATA_TOGGLE_R_PIN2_BIT)
#define GPIO_DATA_TOGGLE_R_PIN2_TOGGLE    (GPIO_DATA_TOGGLE_PIN2_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN2_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN3_BIT    (3UL)

#define GPIO_DATA_TOGGLE_PIN3_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN3_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN3_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN3_MASK    (GPIO_DATA_TOGGLE_PIN3_MASK<< GPIO_DATA_TOGGLE_R_PIN3_BIT)
#define GPIO_DATA_TOGGLE_R_PIN3_NA    (GPIO_DATA_TOGGLE_PIN3_NA<< GPIO_DATA_TOGGLE_R_PIN3_BIT)
#define GPIO_DATA_TOGGLE_R_PIN3_TOGGLE    (GPIO_DATA_TOGGLE_PIN3_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN3_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN4_BIT    (4UL)

#define GPIO_DATA_TOGGLE_PIN4_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN4_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN4_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN4_MASK    (GPIO_DATA_TOGGLE_PIN4_MASK<< GPIO_DATA_TOGGLE_R_PIN4_BIT)
#define GPIO_DATA_TOGGLE_R_PIN4_NA    (GPIO_DATA_TOGGLE_PIN4_NA<< GPIO_DATA_TOGGLE_R_PIN4_BIT)
#define GPIO_DATA_TOGGLE_R_PIN4_TOGGLE    (GPIO_DATA_TOGGLE_PIN4_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN4_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN5_BIT    (5UL)

#define GPIO_DATA_TOGGLE_PIN5_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN5_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN5_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN5_MASK    (GPIO_DATA_TOGGLE_PIN5_MASK<< GPIO_DATA_TOGGLE_R_PIN5_BIT)
#define GPIO_DATA_TOGGLE_R_PIN5_NA    (GPIO_DATA_TOGGLE_PIN5_NA<< GPIO_DATA_TOGGLE_R_PIN5_BIT)
#define GPIO_DATA_TOGGLE_R_PIN5_TOGGLE    (GPIO_DATA_TOGGLE_PIN5_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN5_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN6_BIT    (6UL)

#define GPIO_DATA_TOGGLE_PIN6_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN6_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN6_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN6_MASK    (GPIO_DATA_TOGGLE_PIN6_MASK<< GPIO_DATA_TOGGLE_R_PIN6_BIT)
#define GPIO_DATA_TOGGLE_R_PIN6_NA    (GPIO_DATA_TOGGLE_PIN6_NA<< GPIO_DATA_TOGGLE_R_PIN6_BIT)
#define GPIO_DATA_TOGGLE_R_PIN6_TOGGLE    (GPIO_DATA_TOGGLE_PIN6_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN6_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN7_BIT    (7UL)

#define GPIO_DATA_TOGGLE_PIN7_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN7_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN7_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN7_MASK    (GPIO_DATA_TOGGLE_PIN7_MASK<< GPIO_DATA_TOGGLE_R_PIN7_BIT)
#define GPIO_DATA_TOGGLE_R_PIN7_NA    (GPIO_DATA_TOGGLE_PIN7_NA<< GPIO_DATA_TOGGLE_R_PIN7_BIT)
#define GPIO_DATA_TOGGLE_R_PIN7_TOGGLE    (GPIO_DATA_TOGGLE_PIN7_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN7_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN8_BIT    (8UL)

#define GPIO_DATA_TOGGLE_PIN8_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN8_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN8_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN8_MASK    (GPIO_DATA_TOGGLE_PIN8_MASK<< GPIO_DATA_TOGGLE_R_PIN8_BIT)
#define GPIO_DATA_TOGGLE_R_PIN8_NA    (GPIO_DATA_TOGGLE_PIN8_NA<< GPIO_DATA_TOGGLE_R_PIN8_BIT)
#define GPIO_DATA_TOGGLE_R_PIN8_TOGGLE    (GPIO_DATA_TOGGLE_PIN8_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN8_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN9_BIT    (9UL)

#define GPIO_DATA_TOGGLE_PIN9_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN9_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN9_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN9_MASK    (GPIO_DATA_TOGGLE_PIN9_MASK<< GPIO_DATA_TOGGLE_R_PIN9_BIT)
#define GPIO_DATA_TOGGLE_R_PIN9_NA    (GPIO_DATA_TOGGLE_PIN9_NA<< GPIO_DATA_TOGGLE_R_PIN9_BIT)
#define GPIO_DATA_TOGGLE_R_PIN9_TOGGLE    (GPIO_DATA_TOGGLE_PIN9_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN9_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN10_BIT    (10UL)

#define GPIO_DATA_TOGGLE_PIN10_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN10_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN10_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN10_MASK    (GPIO_DATA_TOGGLE_PIN10_MASK<< GPIO_DATA_TOGGLE_R_PIN10_BIT)
#define GPIO_DATA_TOGGLE_R_PIN10_NA    (GPIO_DATA_TOGGLE_PIN10_NA<< GPIO_DATA_TOGGLE_R_PIN10_BIT)
#define GPIO_DATA_TOGGLE_R_PIN10_TOGGLE    (GPIO_DATA_TOGGLE_PIN10_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN10_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN11_BIT    (11UL)

#define GPIO_DATA_TOGGLE_PIN11_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN11_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN11_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN11_MASK    (GPIO_DATA_TOGGLE_PIN11_MASK<< GPIO_DATA_TOGGLE_R_PIN11_BIT)
#define GPIO_DATA_TOGGLE_R_PIN11_NA    (GPIO_DATA_TOGGLE_PIN11_NA<< GPIO_DATA_TOGGLE_R_PIN11_BIT)
#define GPIO_DATA_TOGGLE_R_PIN11_TOGGLE    (GPIO_DATA_TOGGLE_PIN11_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN11_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN12_BIT    (12UL)

#define GPIO_DATA_TOGGLE_PIN12_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN12_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN12_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN12_MASK    (GPIO_DATA_TOGGLE_PIN12_MASK<< GPIO_DATA_TOGGLE_R_PIN12_BIT)
#define GPIO_DATA_TOGGLE_R_PIN12_NA    (GPIO_DATA_TOGGLE_PIN12_NA<< GPIO_DATA_TOGGLE_R_PIN12_BIT)
#define GPIO_DATA_TOGGLE_R_PIN12_TOGGLE    (GPIO_DATA_TOGGLE_PIN12_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN12_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN13_BIT    (13UL)

#define GPIO_DATA_TOGGLE_PIN13_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN13_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN13_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN13_MASK    (GPIO_DATA_TOGGLE_PIN13_MASK<< GPIO_DATA_TOGGLE_R_PIN13_BIT)
#define GPIO_DATA_TOGGLE_R_PIN13_NA    (GPIO_DATA_TOGGLE_PIN13_NA<< GPIO_DATA_TOGGLE_R_PIN13_BIT)
#define GPIO_DATA_TOGGLE_R_PIN13_TOGGLE    (GPIO_DATA_TOGGLE_PIN13_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN13_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN14_BIT    (14UL)

#define GPIO_DATA_TOGGLE_PIN14_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN14_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN14_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN14_MASK    (GPIO_DATA_TOGGLE_PIN14_MASK<< GPIO_DATA_TOGGLE_R_PIN14_BIT)
#define GPIO_DATA_TOGGLE_R_PIN14_NA    (GPIO_DATA_TOGGLE_PIN14_NA<< GPIO_DATA_TOGGLE_R_PIN14_BIT)
#define GPIO_DATA_TOGGLE_R_PIN14_TOGGLE    (GPIO_DATA_TOGGLE_PIN14_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN14_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN15_BIT    (15UL)

#define GPIO_DATA_TOGGLE_PIN15_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN15_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN15_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN15_MASK    (GPIO_DATA_TOGGLE_PIN15_MASK<< GPIO_DATA_TOGGLE_R_PIN15_BIT)
#define GPIO_DATA_TOGGLE_R_PIN15_NA    (GPIO_DATA_TOGGLE_PIN15_NA<< GPIO_DATA_TOGGLE_R_PIN15_BIT)
#define GPIO_DATA_TOGGLE_R_PIN15_TOGGLE    (GPIO_DATA_TOGGLE_PIN15_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN15_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN16_BIT    (16UL)

#define GPIO_DATA_TOGGLE_PIN16_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN16_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN16_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN16_MASK    (GPIO_DATA_TOGGLE_PIN16_MASK<< GPIO_DATA_TOGGLE_R_PIN16_BIT)
#define GPIO_DATA_TOGGLE_R_PIN16_NA    (GPIO_DATA_TOGGLE_PIN16_NA<< GPIO_DATA_TOGGLE_R_PIN16_BIT)
#define GPIO_DATA_TOGGLE_R_PIN16_TOGGLE    (GPIO_DATA_TOGGLE_PIN16_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN17_BIT    (17UL)

#define GPIO_DATA_TOGGLE_PIN17_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN17_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN17_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN17_MASK    (GPIO_DATA_TOGGLE_PIN17_MASK<< GPIO_DATA_TOGGLE_R_PIN17_BIT)
#define GPIO_DATA_TOGGLE_R_PIN17_NA    (GPIO_DATA_TOGGLE_PIN17_NA<< GPIO_DATA_TOGGLE_R_PIN17_BIT)
#define GPIO_DATA_TOGGLE_R_PIN17_TOGGLE    (GPIO_DATA_TOGGLE_PIN17_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN18_BIT    (18UL)

#define GPIO_DATA_TOGGLE_PIN18_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN18_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN18_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN18_MASK    (GPIO_DATA_TOGGLE_PIN18_MASK<< GPIO_DATA_TOGGLE_R_PIN18_BIT)
#define GPIO_DATA_TOGGLE_R_PIN18_NA    (GPIO_DATA_TOGGLE_PIN18_NA<< GPIO_DATA_TOGGLE_R_PIN18_BIT)
#define GPIO_DATA_TOGGLE_R_PIN18_TOGGLE    (GPIO_DATA_TOGGLE_PIN18_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN19_BIT    (19UL)

#define GPIO_DATA_TOGGLE_PIN19_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN19_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN19_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN19_MASK    (GPIO_DATA_TOGGLE_PIN19_MASK<< GPIO_DATA_TOGGLE_R_PIN19_BIT)
#define GPIO_DATA_TOGGLE_R_PIN19_NA    (GPIO_DATA_TOGGLE_PIN19_NA<< GPIO_DATA_TOGGLE_R_PIN19_BIT)
#define GPIO_DATA_TOGGLE_R_PIN19_TOGGLE    (GPIO_DATA_TOGGLE_PIN19_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN20_BIT    (20UL)

#define GPIO_DATA_TOGGLE_PIN20_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN20_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN20_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN20_MASK    (GPIO_DATA_TOGGLE_PIN20_MASK<< GPIO_DATA_TOGGLE_R_PIN20_BIT)
#define GPIO_DATA_TOGGLE_R_PIN20_NA    (GPIO_DATA_TOGGLE_PIN20_NA<< GPIO_DATA_TOGGLE_R_PIN20_BIT)
#define GPIO_DATA_TOGGLE_R_PIN20_TOGGLE    (GPIO_DATA_TOGGLE_PIN20_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN21_BIT    (21UL)

#define GPIO_DATA_TOGGLE_PIN21_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN21_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN21_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN21_MASK    (GPIO_DATA_TOGGLE_PIN21_MASK<< GPIO_DATA_TOGGLE_R_PIN21_BIT)
#define GPIO_DATA_TOGGLE_R_PIN21_NA    (GPIO_DATA_TOGGLE_PIN21_NA<< GPIO_DATA_TOGGLE_R_PIN21_BIT)
#define GPIO_DATA_TOGGLE_R_PIN21_TOGGLE    (GPIO_DATA_TOGGLE_PIN21_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN22_BIT    (22UL)

#define GPIO_DATA_TOGGLE_PIN22_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN22_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN22_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN22_MASK    (GPIO_DATA_TOGGLE_PIN22_MASK<< GPIO_DATA_TOGGLE_R_PIN22_BIT)
#define GPIO_DATA_TOGGLE_R_PIN22_NA    (GPIO_DATA_TOGGLE_PIN22_NA<< GPIO_DATA_TOGGLE_R_PIN22_BIT)
#define GPIO_DATA_TOGGLE_R_PIN22_TOGGLE    (GPIO_DATA_TOGGLE_PIN22_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN23_BIT    (23UL)

#define GPIO_DATA_TOGGLE_PIN23_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN23_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN23_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN23_MASK    (GPIO_DATA_TOGGLE_PIN23_MASK<< GPIO_DATA_TOGGLE_R_PIN23_BIT)
#define GPIO_DATA_TOGGLE_R_PIN23_NA    (GPIO_DATA_TOGGLE_PIN23_NA<< GPIO_DATA_TOGGLE_R_PIN23_BIT)
#define GPIO_DATA_TOGGLE_R_PIN23_TOGGLE    (GPIO_DATA_TOGGLE_PIN23_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN24_BIT    (24UL)

#define GPIO_DATA_TOGGLE_PIN24_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN24_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN24_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN24_MASK    (GPIO_DATA_TOGGLE_PIN24_MASK<< GPIO_DATA_TOGGLE_R_PIN24_BIT)
#define GPIO_DATA_TOGGLE_R_PIN24_NA    (GPIO_DATA_TOGGLE_PIN24_NA<< GPIO_DATA_TOGGLE_R_PIN24_BIT)
#define GPIO_DATA_TOGGLE_R_PIN24_TOGGLE    (GPIO_DATA_TOGGLE_PIN24_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN25_BIT    (25UL)

#define GPIO_DATA_TOGGLE_PIN25_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN25_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN25_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN25_MASK    (GPIO_DATA_TOGGLE_PIN25_MASK<< GPIO_DATA_TOGGLE_R_PIN25_BIT)
#define GPIO_DATA_TOGGLE_R_PIN25_NA    (GPIO_DATA_TOGGLE_PIN25_NA<< GPIO_DATA_TOGGLE_R_PIN25_BIT)
#define GPIO_DATA_TOGGLE_R_PIN25_TOGGLE    (GPIO_DATA_TOGGLE_PIN25_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN26_BIT    (26UL)

#define GPIO_DATA_TOGGLE_PIN26_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN26_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN26_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN26_MASK    (GPIO_DATA_TOGGLE_PIN26_MASK<< GPIO_DATA_TOGGLE_R_PIN26_BIT)
#define GPIO_DATA_TOGGLE_R_PIN26_NA    (GPIO_DATA_TOGGLE_PIN26_NA<< GPIO_DATA_TOGGLE_R_PIN26_BIT)
#define GPIO_DATA_TOGGLE_R_PIN26_TOGGLE    (GPIO_DATA_TOGGLE_PIN26_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN27_BIT    (27UL)

#define GPIO_DATA_TOGGLE_PIN27_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN27_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN27_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN27_MASK    (GPIO_DATA_TOGGLE_PIN27_MASK<< GPIO_DATA_TOGGLE_R_PIN27_BIT)
#define GPIO_DATA_TOGGLE_R_PIN27_NA    (GPIO_DATA_TOGGLE_PIN27_NA<< GPIO_DATA_TOGGLE_R_PIN27_BIT)
#define GPIO_DATA_TOGGLE_R_PIN27_TOGGLE    (GPIO_DATA_TOGGLE_PIN27_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN28_BIT    (28UL)

#define GPIO_DATA_TOGGLE_PIN28_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN28_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN28_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN28_MASK    (GPIO_DATA_TOGGLE_PIN28_MASK<< GPIO_DATA_TOGGLE_R_PIN28_BIT)
#define GPIO_DATA_TOGGLE_R_PIN28_NA    (GPIO_DATA_TOGGLE_PIN28_NA<< GPIO_DATA_TOGGLE_R_PIN28_BIT)
#define GPIO_DATA_TOGGLE_R_PIN28_TOGGLE    (GPIO_DATA_TOGGLE_PIN28_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN29_BIT    (29UL)

#define GPIO_DATA_TOGGLE_PIN29_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN29_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN29_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN29_MASK    (GPIO_DATA_TOGGLE_PIN29_MASK<< GPIO_DATA_TOGGLE_R_PIN29_BIT)
#define GPIO_DATA_TOGGLE_R_PIN29_NA    (GPIO_DATA_TOGGLE_PIN29_NA<< GPIO_DATA_TOGGLE_R_PIN29_BIT)
#define GPIO_DATA_TOGGLE_R_PIN29_TOGGLE    (GPIO_DATA_TOGGLE_PIN29_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN30_BIT    (30UL)

#define GPIO_DATA_TOGGLE_PIN30_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN30_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN30_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN30_MASK    (GPIO_DATA_TOGGLE_PIN30_MASK<< GPIO_DATA_TOGGLE_R_PIN30_BIT)
#define GPIO_DATA_TOGGLE_R_PIN30_NA    (GPIO_DATA_TOGGLE_PIN30_NA<< GPIO_DATA_TOGGLE_R_PIN30_BIT)
#define GPIO_DATA_TOGGLE_R_PIN30_TOGGLE    (GPIO_DATA_TOGGLE_PIN30_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_TOGGLE_R_PIN31_BIT    (31UL)

#define GPIO_DATA_TOGGLE_PIN31_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_TOGGLE_PIN31_NA    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_TOGGLE_PIN31_TOGGLE    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_TOGGLE_R_PIN31_MASK    (GPIO_DATA_TOGGLE_PIN31_MASK<< GPIO_DATA_TOGGLE_R_PIN31_BIT)
#define GPIO_DATA_TOGGLE_R_PIN31_NA    (GPIO_DATA_TOGGLE_PIN31_NA<< GPIO_DATA_TOGGLE_R_PIN31_BIT)
#define GPIO_DATA_TOGGLE_R_PIN31_TOGGLE    (GPIO_DATA_TOGGLE_PIN31_TOGGLE<< GPIO_DATA_TOGGLE_R_PIN31_BIT)
/*----------*/


#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_TOGGLE_H_ */
