/**
 *
 * @file GPIO_RegisterDefines_XINTnCTR.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNCTR_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNCTR_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 XINTnCTR *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT    (0UL)

#define GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK    ((uint16_t) 0xFFFFUL)

#define GPIO_INTERRUPT_XINTnCTR_R_INTCTR_MASK    (GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK << GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT1CTR_R_INTCTR_BIT    GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT

#define GPIO_INTERRUPT_XINT1CTR_INTCTR_MASK    GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIO_INTERRUPT_XINT1CTR_R_INTCTR_MASK    (GPIO_INTERRUPT_XINT1CTR_INTCTR_MASK << GPIO_INTERRUPT_XINT1CTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT2CTR_R_INTCTR_BIT    GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT

#define GPIO_INTERRUPT_XINT2CTR_INTCTR_MASK    GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIO_INTERRUPT_XINT2CTR_R_INTCTR_MASK    (GPIO_INTERRUPT_XINT2CTR_INTCTR_MASK << GPIO_INTERRUPT_XINT2CTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT3CTR_R_INTCTR_BIT    GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT

#define GPIO_INTERRUPT_XINT3CTR_INTCTR_MASK    GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIO_INTERRUPT_XINT3CTR_R_INTCTR_MASK    (GPIO_INTERRUPT_XINT3CTR_INTCTR_MASK << GPIO_INTERRUPT_XINT3CTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINTnCTR_INTCTR_BIT    GPIO_INTERRUPT_XINTnCTR_R_INTCTR_BIT

#define GPIOA_INTERRUPT_XINTnCTR_INTCTR_MASK    GPIO_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIOA_INTERRUPT_XINTnCTR_R_INTCTR_MASK    (GPIOA_INTERRUPT_XINTnCTR_INTCTR_MASK << GPIOA_INTERRUPT_XINTnCTR_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINT1CTR_R_INTCTR_BIT    GPIOA_INTERRUPT_XINTnCTR_INTCTR_BIT

#define GPIOA_INTERRUPT_XINT1CTR_INTCTR_MASK    GPIOA_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIOA_INTERRUPT_XINT1CTR_R_INTCTR_MASK    (GPIOA_INTERRUPT_XINT1CTR_INTCTR_MASK << GPIOA_INTERRUPT_XINT1CTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINT2CTR_R_INTCTR_BIT    GPIOA_INTERRUPT_XINTnCTR_INTCTR_BIT

#define GPIOA_INTERRUPT_XINT2CTR_INTCTR_MASK    GPIOA_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIOA_INTERRUPT_XINT2CTR_R_INTCTR_MASK    (GPIOA_INTERRUPT_XINT2CTR_INTCTR_MASK << GPIOA_INTERRUPT_XINT2CTR_R_INTCTR_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINT3CTR_R_INTCTR_BIT    GPIOA_INTERRUPT_XINTnCTR_INTCTR_BIT

#define GPIOA_INTERRUPT_XINT3CTR_INTCTR_MASK    GPIOA_INTERRUPT_XINTnCTR_INTCTR_MASK

#define GPIOA_INTERRUPT_XINT3CTR_R_INTCTR_MASK    (GPIOA_INTERRUPT_XINT3CTR_INTCTR_MASK << GPIOA_INTERRUPT_XINT3CTR_R_INTCTR_BIT)
/*----------*/

#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNCTR_H_ */
