/**
 *
 * @file GPIO_RegisterDefines_LPMSEL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_LPMSEL_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_LPMSEL_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 6 LPMSEL *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN_BIT    (0UL)

#define GPIO_INTERRUPT_LPMSEL_PIN_MASK    ((uint32_t) 0xFFFFFFFFUL)
#define GPIO_INTERRUPT_LPMSEL_PIN_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN_ENA    ((uint32_t) 0xFFFFFFFFUL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN_MASK    (GPIO_INTERRUPT_LPMSEL_PIN_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN_DIS    (GPIO_INTERRUPT_LPMSEL_PIN_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN_ENA    (GPIO_INTERRUPT_LPMSEL_PIN_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN0_BIT    (0UL)

#define GPIO_INTERRUPT_LPMSEL_PIN0_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN0_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN0_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN0_MASK    (GPIO_INTERRUPT_LPMSEL_PIN0_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN0_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN0_DIS    (GPIO_INTERRUPT_LPMSEL_PIN0_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN0_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN0_ENA    (GPIO_INTERRUPT_LPMSEL_PIN0_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN0_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN1_BIT    (1UL)

#define GPIO_INTERRUPT_LPMSEL_PIN1_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN1_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN1_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN1_MASK    (GPIO_INTERRUPT_LPMSEL_PIN1_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN1_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN1_DIS    (GPIO_INTERRUPT_LPMSEL_PIN1_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN1_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN1_ENA    (GPIO_INTERRUPT_LPMSEL_PIN1_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN1_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN2_BIT    (2UL)

#define GPIO_INTERRUPT_LPMSEL_PIN2_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN2_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN2_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN2_MASK    (GPIO_INTERRUPT_LPMSEL_PIN2_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN2_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN2_DIS    (GPIO_INTERRUPT_LPMSEL_PIN2_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN2_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN2_ENA    (GPIO_INTERRUPT_LPMSEL_PIN2_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN2_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN3_BIT    (3UL)

#define GPIO_INTERRUPT_LPMSEL_PIN3_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN3_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN3_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN3_MASK    (GPIO_INTERRUPT_LPMSEL_PIN3_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN3_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN3_DIS    (GPIO_INTERRUPT_LPMSEL_PIN3_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN3_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN3_ENA    (GPIO_INTERRUPT_LPMSEL_PIN3_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN3_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN4_BIT    (4UL)

#define GPIO_INTERRUPT_LPMSEL_PIN4_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN4_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN4_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN4_MASK    (GPIO_INTERRUPT_LPMSEL_PIN4_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN4_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN4_DIS    (GPIO_INTERRUPT_LPMSEL_PIN4_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN4_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN4_ENA    (GPIO_INTERRUPT_LPMSEL_PIN4_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN4_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN5_BIT    (5UL)

#define GPIO_INTERRUPT_LPMSEL_PIN5_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN5_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN5_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN5_MASK    (GPIO_INTERRUPT_LPMSEL_PIN5_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN5_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN5_DIS    (GPIO_INTERRUPT_LPMSEL_PIN5_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN5_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN5_ENA    (GPIO_INTERRUPT_LPMSEL_PIN5_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN5_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN6_BIT    (6UL)

#define GPIO_INTERRUPT_LPMSEL_PIN6_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN6_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN6_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN6_MASK    (GPIO_INTERRUPT_LPMSEL_PIN6_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN6_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN6_DIS    (GPIO_INTERRUPT_LPMSEL_PIN6_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN6_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN6_ENA    (GPIO_INTERRUPT_LPMSEL_PIN6_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN6_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN7_BIT    (7UL)

#define GPIO_INTERRUPT_LPMSEL_PIN7_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN7_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN7_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN7_MASK    (GPIO_INTERRUPT_LPMSEL_PIN7_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN7_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN7_DIS    (GPIO_INTERRUPT_LPMSEL_PIN7_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN7_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN7_ENA    (GPIO_INTERRUPT_LPMSEL_PIN7_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN7_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN8_BIT    (8UL)

#define GPIO_INTERRUPT_LPMSEL_PIN8_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN8_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN8_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN8_MASK    (GPIO_INTERRUPT_LPMSEL_PIN8_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN8_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN8_DIS    (GPIO_INTERRUPT_LPMSEL_PIN8_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN8_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN8_ENA    (GPIO_INTERRUPT_LPMSEL_PIN8_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN8_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN9_BIT    (9UL)

#define GPIO_INTERRUPT_LPMSEL_PIN9_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN9_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN9_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN9_MASK    (GPIO_INTERRUPT_LPMSEL_PIN9_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN9_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN9_DIS    (GPIO_INTERRUPT_LPMSEL_PIN9_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN9_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN9_ENA    (GPIO_INTERRUPT_LPMSEL_PIN9_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN9_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN10_BIT    (10UL)

#define GPIO_INTERRUPT_LPMSEL_PIN10_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN10_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN10_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN10_MASK    (GPIO_INTERRUPT_LPMSEL_PIN10_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN10_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN10_DIS    (GPIO_INTERRUPT_LPMSEL_PIN10_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN10_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN10_ENA    (GPIO_INTERRUPT_LPMSEL_PIN10_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN10_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN11_BIT    (11UL)

#define GPIO_INTERRUPT_LPMSEL_PIN11_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN11_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN11_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN11_MASK    (GPIO_INTERRUPT_LPMSEL_PIN11_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN11_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN11_DIS    (GPIO_INTERRUPT_LPMSEL_PIN11_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN11_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN11_ENA    (GPIO_INTERRUPT_LPMSEL_PIN11_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN11_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN12_BIT    (12UL)

#define GPIO_INTERRUPT_LPMSEL_PIN12_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN12_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN12_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN12_MASK    (GPIO_INTERRUPT_LPMSEL_PIN12_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN12_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN12_DIS    (GPIO_INTERRUPT_LPMSEL_PIN12_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN12_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN12_ENA    (GPIO_INTERRUPT_LPMSEL_PIN12_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN12_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN13_BIT    (13UL)

#define GPIO_INTERRUPT_LPMSEL_PIN13_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN13_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN13_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN13_MASK    (GPIO_INTERRUPT_LPMSEL_PIN13_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN13_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN13_DIS    (GPIO_INTERRUPT_LPMSEL_PIN13_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN13_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN13_ENA    (GPIO_INTERRUPT_LPMSEL_PIN13_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN13_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN14_BIT    (14UL)

#define GPIO_INTERRUPT_LPMSEL_PIN14_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN14_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN14_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN14_MASK    (GPIO_INTERRUPT_LPMSEL_PIN14_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN14_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN14_DIS    (GPIO_INTERRUPT_LPMSEL_PIN14_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN14_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN14_ENA    (GPIO_INTERRUPT_LPMSEL_PIN14_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN14_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN15_BIT    (15UL)

#define GPIO_INTERRUPT_LPMSEL_PIN15_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN15_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN15_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN15_MASK    (GPIO_INTERRUPT_LPMSEL_PIN15_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN15_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN15_DIS    (GPIO_INTERRUPT_LPMSEL_PIN15_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN15_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN15_ENA    (GPIO_INTERRUPT_LPMSEL_PIN15_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN15_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN16_BIT    (16UL)

#define GPIO_INTERRUPT_LPMSEL_PIN16_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN16_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN16_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN16_MASK    (GPIO_INTERRUPT_LPMSEL_PIN16_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN16_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN16_DIS    (GPIO_INTERRUPT_LPMSEL_PIN16_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN16_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN16_ENA    (GPIO_INTERRUPT_LPMSEL_PIN16_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN17_BIT    (17UL)

#define GPIO_INTERRUPT_LPMSEL_PIN17_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN17_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN17_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN17_MASK    (GPIO_INTERRUPT_LPMSEL_PIN17_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN17_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN17_DIS    (GPIO_INTERRUPT_LPMSEL_PIN17_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN17_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN17_ENA    (GPIO_INTERRUPT_LPMSEL_PIN17_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN18_BIT    (18UL)

#define GPIO_INTERRUPT_LPMSEL_PIN18_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN18_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN18_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN18_MASK    (GPIO_INTERRUPT_LPMSEL_PIN18_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN18_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN18_DIS    (GPIO_INTERRUPT_LPMSEL_PIN18_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN18_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN18_ENA    (GPIO_INTERRUPT_LPMSEL_PIN18_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN19_BIT    (19UL)

#define GPIO_INTERRUPT_LPMSEL_PIN19_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN19_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN19_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN19_MASK    (GPIO_INTERRUPT_LPMSEL_PIN19_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN19_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN19_DIS    (GPIO_INTERRUPT_LPMSEL_PIN19_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN19_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN19_ENA    (GPIO_INTERRUPT_LPMSEL_PIN19_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN20_BIT    (20UL)

#define GPIO_INTERRUPT_LPMSEL_PIN20_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN20_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN20_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN20_MASK    (GPIO_INTERRUPT_LPMSEL_PIN20_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN20_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN20_DIS    (GPIO_INTERRUPT_LPMSEL_PIN20_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN20_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN20_ENA    (GPIO_INTERRUPT_LPMSEL_PIN20_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN21_BIT    (21UL)

#define GPIO_INTERRUPT_LPMSEL_PIN21_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN21_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN21_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN21_MASK    (GPIO_INTERRUPT_LPMSEL_PIN21_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN21_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN21_DIS    (GPIO_INTERRUPT_LPMSEL_PIN21_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN21_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN21_ENA    (GPIO_INTERRUPT_LPMSEL_PIN21_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN22_BIT    (22UL)

#define GPIO_INTERRUPT_LPMSEL_PIN22_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN22_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN22_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN22_MASK    (GPIO_INTERRUPT_LPMSEL_PIN22_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN22_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN22_DIS    (GPIO_INTERRUPT_LPMSEL_PIN22_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN22_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN22_ENA    (GPIO_INTERRUPT_LPMSEL_PIN22_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN23_BIT    (23UL)

#define GPIO_INTERRUPT_LPMSEL_PIN23_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN23_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN23_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN23_MASK    (GPIO_INTERRUPT_LPMSEL_PIN23_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN23_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN23_DIS    (GPIO_INTERRUPT_LPMSEL_PIN23_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN23_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN23_ENA    (GPIO_INTERRUPT_LPMSEL_PIN23_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN24_BIT    (24UL)

#define GPIO_INTERRUPT_LPMSEL_PIN24_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN24_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN24_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN24_MASK    (GPIO_INTERRUPT_LPMSEL_PIN24_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN24_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN24_DIS    (GPIO_INTERRUPT_LPMSEL_PIN24_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN24_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN24_ENA    (GPIO_INTERRUPT_LPMSEL_PIN24_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN25_BIT    (25UL)

#define GPIO_INTERRUPT_LPMSEL_PIN25_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN25_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN25_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN25_MASK    (GPIO_INTERRUPT_LPMSEL_PIN25_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN25_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN25_DIS    (GPIO_INTERRUPT_LPMSEL_PIN25_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN25_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN25_ENA    (GPIO_INTERRUPT_LPMSEL_PIN25_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN26_BIT    (26UL)

#define GPIO_INTERRUPT_LPMSEL_PIN26_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN26_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN26_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN26_MASK    (GPIO_INTERRUPT_LPMSEL_PIN26_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN26_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN26_DIS    (GPIO_INTERRUPT_LPMSEL_PIN26_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN26_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN26_ENA    (GPIO_INTERRUPT_LPMSEL_PIN26_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN27_BIT    (27UL)

#define GPIO_INTERRUPT_LPMSEL_PIN27_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN27_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN27_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN27_MASK    (GPIO_INTERRUPT_LPMSEL_PIN27_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN27_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN27_DIS    (GPIO_INTERRUPT_LPMSEL_PIN27_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN27_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN27_ENA    (GPIO_INTERRUPT_LPMSEL_PIN27_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN28_BIT    (28UL)

#define GPIO_INTERRUPT_LPMSEL_PIN28_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN28_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN28_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN28_MASK    (GPIO_INTERRUPT_LPMSEL_PIN28_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN28_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN28_DIS    (GPIO_INTERRUPT_LPMSEL_PIN28_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN28_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN28_ENA    (GPIO_INTERRUPT_LPMSEL_PIN28_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN29_BIT    (29UL)

#define GPIO_INTERRUPT_LPMSEL_PIN29_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN29_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN29_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN29_MASK    (GPIO_INTERRUPT_LPMSEL_PIN29_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN29_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN29_DIS    (GPIO_INTERRUPT_LPMSEL_PIN29_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN29_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN29_ENA    (GPIO_INTERRUPT_LPMSEL_PIN29_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN30_BIT    (30UL)

#define GPIO_INTERRUPT_LPMSEL_PIN30_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN30_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN30_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN30_MASK    (GPIO_INTERRUPT_LPMSEL_PIN30_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN30_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN30_DIS    (GPIO_INTERRUPT_LPMSEL_PIN30_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN30_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN30_ENA    (GPIO_INTERRUPT_LPMSEL_PIN30_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_LPMSEL_R_PIN31_BIT    (31UL)

#define GPIO_INTERRUPT_LPMSEL_PIN31_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_INTERRUPT_LPMSEL_PIN31_DIS    ((uint32_t) 0x00000000UL)
#define GPIO_INTERRUPT_LPMSEL_PIN31_ENA    ((uint32_t) 0x00000001UL)

#define GPIO_INTERRUPT_LPMSEL_R_PIN31_MASK    (GPIO_INTERRUPT_LPMSEL_PIN31_MASK<< GPIO_INTERRUPT_LPMSEL_R_PIN31_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN31_DIS    (GPIO_INTERRUPT_LPMSEL_PIN31_DIS<< GPIO_INTERRUPT_LPMSEL_R_PIN31_BIT)
#define GPIO_INTERRUPT_LPMSEL_R_PIN31_ENA    (GPIO_INTERRUPT_LPMSEL_PIN31_ENA<< GPIO_INTERRUPT_LPMSEL_R_PIN31_BIT)
/*----------*/


#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_LPMSEL_H_ */
