/**
 *
 * @file GPIO_RegisterDefines_XINTnSEL.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNSEL_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNSEL_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 1 XINTnSEL *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT    (0UL)

#define GPIO_INTERRUPT_XINTnSEL_SEL_MASK    ((uint16_t) 0x001FUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN0    ((uint16_t) 0x0000UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN1    ((uint16_t) 0x0001UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN2    ((uint16_t) 0x0002UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN3    ((uint16_t) 0x0003UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN4    ((uint16_t) 0x0004UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN5    ((uint16_t) 0x0005UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN6    ((uint16_t) 0x0006UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN7    ((uint16_t) 0x0007UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN8    ((uint16_t) 0x0008UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN9    ((uint16_t) 0x0009UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN10    ((uint16_t) 0x000AUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN11    ((uint16_t) 0x000BUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN12    ((uint16_t) 0x000CUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN13    ((uint16_t) 0x000DUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN14    ((uint16_t) 0x000EUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN15    ((uint16_t) 0x000FUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN16    ((uint16_t) 0x0010UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN17    ((uint16_t) 0x0011UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN18    ((uint16_t) 0x0012UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN19    ((uint16_t) 0x0013UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN20    ((uint16_t) 0x0014UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN21    ((uint16_t) 0x0015UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN22    ((uint16_t) 0x0016UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN23    ((uint16_t) 0x0017UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN24    ((uint16_t) 0x0018UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN25    ((uint16_t) 0x0019UL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN26    ((uint16_t) 0x001AUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN27    ((uint16_t) 0x001BUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN28    ((uint16_t) 0x001CUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN29    ((uint16_t) 0x001DUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN30    ((uint16_t) 0x001EUL)
#define GPIO_INTERRUPT_XINTnSEL_SEL_PIN31    ((uint16_t) 0x001FUL)

#define GPIO_INTERRUPT_XINTnSEL_R_SEL_MASK    (GPIO_INTERRUPT_XINTnSEL_SEL_MASK << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN0    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN0 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN1    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN1 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN2    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN2 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN3    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN3 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN4    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN4 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN5    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN5 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN6    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN6 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN7    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN7 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN8    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN8 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN9    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN9 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN10    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN10 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN11    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN11 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN12    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN12 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN13    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN13 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN14    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN14 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN15    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN15 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN16    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN16 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN17    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN17 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN18    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN18 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN19    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN19 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN20    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN20 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN21    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN21 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN22    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN22 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN23    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN23 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN24    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN24 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN25    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN25 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN26    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN26 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN27    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN27 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN28    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN28 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN29    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN29 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN30    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN30 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINTnSEL_R_SEL_PIN31    (GPIO_INTERRUPT_XINTnSEL_SEL_PIN31 << GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT    (0UL)

#define GPIO_INTERRUPT_XINT1SEL_SEL_MASK    GPIO_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN0    GPIO_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN1    GPIO_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN2    GPIO_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN3    GPIO_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN4    GPIO_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN5    GPIO_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN6    GPIO_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN7    GPIO_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN8    GPIO_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN9    GPIO_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN10    GPIO_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN11    GPIO_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN12    GPIO_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN13    GPIO_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN14    GPIO_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN15    GPIO_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN16    GPIO_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN17    GPIO_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN18    GPIO_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN19    GPIO_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN20    GPIO_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN21    GPIO_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN22    GPIO_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN23    GPIO_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN24    GPIO_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN25    GPIO_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN26    GPIO_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN27    GPIO_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN28    GPIO_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN29    GPIO_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN30    GPIO_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIO_INTERRUPT_XINT1SEL_SEL_PIN31    GPIO_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIO_INTERRUPT_XINT1SEL_R_SEL_MASK    (GPIO_INTERRUPT_XINT1SEL_SEL_MASK << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN0    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN0 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN1    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN1 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN2    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN2 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN3    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN3 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN4    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN4 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN5    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN5 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN6    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN6 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN7    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN7 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN8    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN8 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN9    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN9 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN10    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN10 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN11    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN11 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN12    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN12 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN13    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN13 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN14    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN14 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN15    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN15 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN16    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN16 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN17    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN17 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN18    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN18 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN19    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN19 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN20    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN20 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN21    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN21 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN22    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN22 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN23    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN23 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN24    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN24 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN25    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN25 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN26    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN26 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN27    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN27 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN28    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN28 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN29    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN29 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN30    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN30 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT1SEL_R_SEL_PIN31    (GPIO_INTERRUPT_XINT1SEL_SEL_PIN31 << GPIO_INTERRUPT_XINT1SEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT    (0UL)

#define GPIO_INTERRUPT_XINT2SEL_SEL_MASK    GPIO_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN0    GPIO_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN1    GPIO_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN2    GPIO_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN3    GPIO_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN4    GPIO_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN5    GPIO_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN6    GPIO_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN7    GPIO_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN8    GPIO_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN9    GPIO_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN10    GPIO_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN11    GPIO_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN12    GPIO_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN13    GPIO_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN14    GPIO_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN15    GPIO_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN16    GPIO_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN17    GPIO_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN18    GPIO_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN19    GPIO_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN20    GPIO_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN21    GPIO_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN22    GPIO_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN23    GPIO_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN24    GPIO_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN25    GPIO_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN26    GPIO_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN27    GPIO_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN28    GPIO_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN29    GPIO_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN30    GPIO_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIO_INTERRUPT_XINT2SEL_SEL_PIN31    GPIO_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIO_INTERRUPT_XINT2SEL_R_SEL_MASK    (GPIO_INTERRUPT_XINT2SEL_SEL_MASK << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN0    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN0 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN1    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN1 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN2    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN2 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN3    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN3 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN4    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN4 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN5    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN5 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN6    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN6 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN7    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN7 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN8    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN8 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN9    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN9 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN10    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN10 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN11    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN11 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN12    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN12 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN13    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN13 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN14    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN14 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN15    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN15 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN16    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN16 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN17    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN17 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN18    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN18 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN19    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN19 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN20    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN20 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN21    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN21 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN22    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN22 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN23    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN23 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN24    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN24 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN25    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN25 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN26    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN26 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN27    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN27 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN28    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN28 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN29    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN29 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN30    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN30 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT2SEL_R_SEL_PIN31    (GPIO_INTERRUPT_XINT2SEL_SEL_PIN31 << GPIO_INTERRUPT_XINT2SEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT    (0UL)

#define GPIO_INTERRUPT_XINT3SEL_SEL_MASK    GPIO_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN0    GPIO_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN1    GPIO_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN2    GPIO_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN3    GPIO_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN4    GPIO_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN5    GPIO_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN6    GPIO_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN7    GPIO_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN8    GPIO_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN9    GPIO_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN10    GPIO_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN11    GPIO_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN12    GPIO_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN13    GPIO_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN14    GPIO_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN15    GPIO_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN16    GPIO_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN17    GPIO_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN18    GPIO_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN19    GPIO_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN20    GPIO_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN21    GPIO_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN22    GPIO_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN23    GPIO_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN24    GPIO_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN25    GPIO_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN26    GPIO_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN27    GPIO_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN28    GPIO_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN29    GPIO_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN30    GPIO_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIO_INTERRUPT_XINT3SEL_SEL_PIN31    GPIO_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIO_INTERRUPT_XINT3SEL_R_SEL_MASK    (GPIO_INTERRUPT_XINT3SEL_SEL_MASK << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN0    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN0 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN1    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN1 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN2    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN2 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN3    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN3 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN4    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN4 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN5    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN5 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN6    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN6 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN7    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN7 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN8    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN8 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN9    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN9 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN10    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN10 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN11    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN11 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN12    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN12 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN13    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN13 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN14    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN14 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN15    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN15 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN16    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN16 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN17    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN17 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN18    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN18 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN19    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN19 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN20    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN20 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN21    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN21 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN22    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN22 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN23    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN23 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN24    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN24 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN25    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN25 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN26    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN26 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN27    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN27 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN28    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN28 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN29    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN29 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN30    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN30 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIO_INTERRUPT_XINT3SEL_R_SEL_PIN31    (GPIO_INTERRUPT_XINT3SEL_SEL_PIN31 << GPIO_INTERRUPT_XINT3SEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT    GPIO_INTERRUPT_XINTnSEL_R_SEL_BIT

#define GPIOA_INTERRUPT_XINTnSEL_SEL_MASK    GPIO_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN0    GPIO_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN1    GPIO_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN2    GPIO_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN3    GPIO_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN4    GPIO_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN5    GPIO_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN6    GPIO_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN7    GPIO_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN8    GPIO_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN9    GPIO_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN10    GPIO_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN11    GPIO_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN12    GPIO_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN13    GPIO_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN14    GPIO_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN15    GPIO_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN16    GPIO_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN17    GPIO_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN18    GPIO_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN19    GPIO_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN20    GPIO_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN21    GPIO_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN22    GPIO_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN23    GPIO_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN24    GPIO_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN25    GPIO_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN26    GPIO_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN27    GPIO_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN28    GPIO_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN29    GPIO_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN30    GPIO_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIOA_INTERRUPT_XINTnSEL_SEL_PIN31    GPIO_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_MASK    (GPIOA_INTERRUPT_XINTnSEL_SEL_MASK << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN0    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN0 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN1    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN1 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN2    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN2 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN3    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN3 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN4    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN4 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN5    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN5 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN6    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN6 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN7    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN7 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN8    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN8 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN9    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN9 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN10    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN10 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN11    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN11 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN12    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN12 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN13    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN13 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN14    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN14 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN15    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN15 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN16    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN16 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN17    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN17 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN18    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN18 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN19    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN19 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN20    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN20 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN21    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN21 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN22    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN22 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN23    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN23 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN24    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN24 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN25    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN25 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN26    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN26 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN27    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN27 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN28    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN28 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN29    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN29 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN30    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN30 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINTnSEL_R_SEL_PIN31    (GPIOA_INTERRUPT_XINTnSEL_SEL_PIN31 << GPIOA_INTERRUPT_XINTnSEL_R_SEL_BIT)
/*----------*/


/*----------*/
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT    (0UL)

#define GPIOA_INTERRUPT_XINT1SEL_SEL_MASK    GPIOA_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN0    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN1    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN2    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN3    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN4    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN5    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN6    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN7    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN8    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN9    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN10    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN11    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN12    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN13    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN14    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN15    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN16    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN17    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN18    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN19    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN20    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN21    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN22    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN23    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN24    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN25    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN26    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN27    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN28    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN29    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN30    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIOA_INTERRUPT_XINT1SEL_SEL_PIN31    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_MASK    (GPIOA_INTERRUPT_XINT1SEL_SEL_MASK << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN0    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN0 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN1    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN1 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN2    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN2 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN3    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN3 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN4    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN4 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN5    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN5 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN6    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN6 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN7    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN7 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN8    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN8 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN9    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN9 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN10    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN10 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN11    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN11 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN12    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN12 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN13    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN13 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN14    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN14 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN15    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN15 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN16    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN16 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN17    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN17 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN18    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN18 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN19    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN19 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN20    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN20 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN21    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN21 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN22    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN22 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN23    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN23 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN24    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN24 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN25    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN25 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN26    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN26 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN27    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN27 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN28    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN28 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN29    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN29 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN30    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN30 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT1SEL_R_SEL_PIN31    (GPIOA_INTERRUPT_XINT1SEL_SEL_PIN31 << GPIOA_INTERRUPT_XINT1SEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT    (0UL)

#define GPIOA_INTERRUPT_XINT2SEL_SEL_MASK    GPIOA_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN0    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN1    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN2    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN3    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN4    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN5    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN6    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN7    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN8    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN9    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN10    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN11    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN12    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN13    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN14    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN15    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN16    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN17    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN18    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN19    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN20    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN21    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN22    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN23    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN24    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN25    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN26    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN27    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN28    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN29    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN30    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIOA_INTERRUPT_XINT2SEL_SEL_PIN31    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_MASK    (GPIOA_INTERRUPT_XINT2SEL_SEL_MASK << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN0    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN0 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN1    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN1 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN2    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN2 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN3    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN3 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN4    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN4 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN5    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN5 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN6    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN6 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN7    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN7 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN8    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN8 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN9    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN9 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN10    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN10 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN11    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN11 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN12    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN12 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN13    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN13 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN14    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN14 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN15    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN15 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN16    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN16 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN17    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN17 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN18    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN18 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN19    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN19 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN20    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN20 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN21    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN21 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN22    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN22 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN23    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN23 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN24    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN24 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN25    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN25 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN26    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN26 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN27    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN27 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN28    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN28 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN29    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN29 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN30    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN30 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT2SEL_R_SEL_PIN31    (GPIOA_INTERRUPT_XINT2SEL_SEL_PIN31 << GPIOA_INTERRUPT_XINT2SEL_R_SEL_BIT)
/*----------*/

/*----------*/
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT    (0UL)

#define GPIOA_INTERRUPT_XINT3SEL_SEL_MASK    GPIOA_INTERRUPT_XINTnSEL_SEL_MASK
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN0    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN0
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN1    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN1
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN2    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN2
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN3    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN3
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN4    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN4
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN5    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN5
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN6    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN6
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN7    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN7
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN8    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN8
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN9    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN9
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN10    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN10
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN11    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN11
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN12    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN12
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN13    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN13
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN14    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN14
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN15    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN15
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN16    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN16
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN17    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN17
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN18    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN18
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN19    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN19
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN20    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN20
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN21    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN21
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN22    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN22
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN23    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN23
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN24    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN24
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN25    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN25
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN26    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN26
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN27    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN27
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN28    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN28
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN29    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN29
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN30    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN30
#define GPIOA_INTERRUPT_XINT3SEL_SEL_PIN31    GPIOA_INTERRUPT_XINTnSEL_SEL_PIN31

#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_MASK    (GPIOA_INTERRUPT_XINT3SEL_SEL_MASK << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN0    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN0 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN1    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN1 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN2    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN2 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN3    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN3 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN4    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN4 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN5    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN5 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN6    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN6 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN7    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN7 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN8    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN8 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN9    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN9 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN10    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN10 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN11    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN11 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN12    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN12 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN13    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN13 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN14    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN14 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN15    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN15 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN16    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN16 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN17    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN17 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN18    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN18 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN19    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN19 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN20    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN20 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN21    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN21 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN22    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN22 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN23    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN23 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN24    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN24 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN25    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN25 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN26    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN26 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN27    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN27 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN28    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN28 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN29    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN29 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN30    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN30 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
#define GPIOA_INTERRUPT_XINT3SEL_R_SEL_PIN31    (GPIOA_INTERRUPT_XINT3SEL_SEL_PIN31 << GPIOA_INTERRUPT_XINT3SEL_R_SEL_BIT)
/*----------*/

#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_XINTNSEL_H_ */
