/**
 *
 * @file GPIO_RegisterDefines_QSEL2.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL2_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL2_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 3 QSEL_HIGH *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT    (0UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN16_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN16_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN16_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN16_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN16_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN16_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN16_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN16_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN16_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN16_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN16_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT    (2UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN17_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN17_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN17_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN17_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN17_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN17_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN17_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN17_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN17_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN17_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN17_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT    (4UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN18_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN18_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN18_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN18_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN18_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN18_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN18_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN18_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN18_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN18_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN18_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT    (6UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN19_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN19_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN19_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN19_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN19_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN19_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN19_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN19_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN19_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN19_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN19_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT    (8UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN20_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN20_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN20_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN20_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN20_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN20_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN20_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN20_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN20_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN20_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN20_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT    (10UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN21_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN21_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN21_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN21_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN21_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN21_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN21_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN21_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN21_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN21_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN21_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT    (12UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN22_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN22_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN22_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN22_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN22_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN22_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN22_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN22_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN22_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN22_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN22_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT    (14UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN23_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN23_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN23_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN23_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN23_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN23_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN23_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN23_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN23_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN23_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN23_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT    (16UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN24_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN24_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN24_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN24_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN24_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN24_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN24_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN24_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN24_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN24_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN24_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT    (18UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN25_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN25_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN25_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN25_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN25_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN25_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN25_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN25_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN25_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN25_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN25_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT    (20UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN26_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN26_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN26_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN26_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN26_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN26_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN26_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN26_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN26_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN26_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN26_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT    (22UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN27_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN27_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN27_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN27_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN27_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN27_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN27_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN27_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN27_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN27_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN27_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT    (24UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN28_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN28_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN28_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN28_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN28_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN28_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN28_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN28_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN28_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN28_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN28_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT    (26UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN29_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN29_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN29_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN29_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN29_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN29_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN29_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN29_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN29_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN29_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN29_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT    (28UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN30_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN30_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN30_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN30_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN30_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN30_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN30_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN30_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN30_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN30_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN30_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT    (30UL)

#define GPIO_CONTROL_QSEL_HIGH_PIN31_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN31_SYSCLK    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN31_2SAMPLES    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN31_5SAMPLES    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_QSEL_HIGH_PIN31_ASYNC    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_MASK    (GPIO_CONTROL_QSEL_HIGH_PIN31_MASK << GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_SYSCLK    (GPIO_CONTROL_QSEL_HIGH_PIN31_SYSCLK << GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_2SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN31_2SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_5SAMPLES    (GPIO_CONTROL_QSEL_HIGH_PIN31_5SAMPLES << GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_QSEL_HIGH_R_PIN31_ASYNC    (GPIO_CONTROL_QSEL_HIGH_PIN31_ASYNC << GPIO_CONTROL_QSEL_HIGH_R_PIN31_BIT)
/*----------*/

#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_QSEL2_H_ */
