/**
 *
 * @file GPIO_RegisterDefines_MUX2.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_MUX2_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_MUX2_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 5 MUX_HIGH *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_CONTROL_MUX_HIGH_PIN_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN_PERIPHERAL3    ((uint32_t) 0x00000003UL)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT    (0UL)

#define GPIO_CONTROL_MUX_HIGH_PIN16_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN16_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN16_MASK    (GPIO_CONTROL_MUX_HIGH_PIN16_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN16_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN16_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN16_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN16_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN16_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN16_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT    (2UL)

#define GPIO_CONTROL_MUX_HIGH_PIN17_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN17_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN17_MASK    (GPIO_CONTROL_MUX_HIGH_PIN17_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN17_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN17_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN17_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN17_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN17_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN17_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT    (4UL)

#define GPIO_CONTROL_MUX_HIGH_PIN18_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN18_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN18_MASK    (GPIO_CONTROL_MUX_HIGH_PIN18_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN18_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN18_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN18_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN18_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN18_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN18_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT    (6UL)

#define GPIO_CONTROL_MUX_HIGH_PIN19_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN19_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN19_MASK    (GPIO_CONTROL_MUX_HIGH_PIN19_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN19_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN19_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN19_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN19_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN19_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN19_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT    (8UL)

#define GPIO_CONTROL_MUX_HIGH_PIN20_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN20_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN20_MASK    (GPIO_CONTROL_MUX_HIGH_PIN20_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN20_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN20_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN20_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN20_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN20_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN20_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT    (10UL)

#define GPIO_CONTROL_MUX_HIGH_PIN21_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN21_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN21_MASK    (GPIO_CONTROL_MUX_HIGH_PIN21_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN21_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN21_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN21_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN21_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN21_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN21_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT    (12UL)

#define GPIO_CONTROL_MUX_HIGH_PIN22_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN22_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN22_MASK    (GPIO_CONTROL_MUX_HIGH_PIN22_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN22_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN22_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN22_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN22_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN22_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN22_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT    (14UL)

#define GPIO_CONTROL_MUX_HIGH_PIN23_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN23_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN23_MASK    (GPIO_CONTROL_MUX_HIGH_PIN23_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN23_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN23_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN23_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN23_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN23_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN23_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT    (16UL)

#define GPIO_CONTROL_MUX_HIGH_PIN24_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN24_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN24_MASK    (GPIO_CONTROL_MUX_HIGH_PIN24_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN24_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN24_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN24_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN24_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN24_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN24_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT    (18UL)

#define GPIO_CONTROL_MUX_HIGH_PIN25_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN25_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN25_MASK    (GPIO_CONTROL_MUX_HIGH_PIN25_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN25_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN25_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN25_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN25_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN25_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN25_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT    (20UL)

#define GPIO_CONTROL_MUX_HIGH_PIN26_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN26_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN26_MASK    (GPIO_CONTROL_MUX_HIGH_PIN26_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN26_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN26_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN26_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN26_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN26_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN26_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT    (22UL)

#define GPIO_CONTROL_MUX_HIGH_PIN27_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN27_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN27_MASK    (GPIO_CONTROL_MUX_HIGH_PIN27_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN27_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN27_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN27_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN27_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN27_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN27_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT    (24UL)

#define GPIO_CONTROL_MUX_HIGH_PIN28_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN28_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN28_MASK    (GPIO_CONTROL_MUX_HIGH_PIN28_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN28_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN28_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN28_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN28_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN28_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN28_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT    (26UL)

#define GPIO_CONTROL_MUX_HIGH_PIN29_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN29_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN29_MASK    (GPIO_CONTROL_MUX_HIGH_PIN29_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN29_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN29_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN29_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN29_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN29_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN29_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT    (28UL)

#define GPIO_CONTROL_MUX_HIGH_PIN30_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN30_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN30_MASK    (GPIO_CONTROL_MUX_HIGH_PIN30_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN30_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN30_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN30_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN30_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN30_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN30_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT    (30UL)

#define GPIO_CONTROL_MUX_HIGH_PIN31_MASK    ((uint32_t) 0x00000003UL)
#define GPIO_CONTROL_MUX_HIGH_PIN31_GPIO    ((uint32_t) 0x00000000UL)
#define GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL1    ((uint32_t) 0x00000001UL)
#define GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL2    ((uint32_t) 0x00000002UL)
#define GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL3    ((uint32_t) 0x00000003UL)

#define GPIO_CONTROL_MUX_HIGH_R_PIN31_MASK    (GPIO_CONTROL_MUX_HIGH_PIN31_MASK << GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN31_GPIO    (GPIO_CONTROL_MUX_HIGH_PIN31_GPIO << GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN31_PERIPHERAL1    (GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL1 << GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN31_PERIPHERAL2    (GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL2 << GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT)
#define GPIO_CONTROL_MUX_HIGH_R_PIN31_PERIPHERAL3    (GPIO_CONTROL_MUX_HIGH_PIN31_PERIPHERAL3 << GPIO_CONTROL_MUX_HIGH_R_PIN31_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN16_BIT    (0UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN16_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN16_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN16_SPIA_MOSI    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN16_EPWM_TZ2    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN16_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN16_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN16_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN16_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN16_SPIA_MOSI    (GPIOA_CONTROL_MUX_HIGH_PIN16_SPIA_MOSI << GPIOA_CONTROL_MUX_HIGH_R_PIN16_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN16_EPWM_TZ2    (GPIOA_CONTROL_MUX_HIGH_PIN16_EPWM_TZ2 << GPIOA_CONTROL_MUX_HIGH_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN17_BIT    (2UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN17_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN17_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN17_SPIA_MISO    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN17_EPWM_TZ3    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN17_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN17_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN17_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN17_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN17_SPIA_MISO    (GPIOA_CONTROL_MUX_HIGH_PIN17_SPIA_MISO << GPIOA_CONTROL_MUX_HIGH_R_PIN17_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN17_EPWM_TZ3    (GPIOA_CONTROL_MUX_HIGH_PIN17_EPWM_TZ3 << GPIOA_CONTROL_MUX_HIGH_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT    (4UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN18_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN18_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN18_SPIA_CLK    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN18_SCIA_TX    ((uint32_t) 0x00000002UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN18_XCLKOUT    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN18_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN18_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_SPIA_CLK    (GPIOA_CONTROL_MUX_HIGH_PIN18_SPIA_CLK << GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_SCIA_TX    (GPIOA_CONTROL_MUX_HIGH_PIN18_SCIA_TX << GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN18_XCLKOUT    (GPIOA_CONTROL_MUX_HIGH_PIN18_XCLKOUT << GPIOA_CONTROL_MUX_HIGH_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT    (6UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN19_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN19_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN19_SPIA_STE    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN19_SCIA_RX    ((uint32_t) 0x00000002UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN19_ECAP1    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN19_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN19_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_SPIA_STE    (GPIOA_CONTROL_MUX_HIGH_PIN19_SPIA_STE << GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_SCIA_RX    (GPIOA_CONTROL_MUX_HIGH_PIN19_SCIA_RX << GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN19_ECAP1    (GPIOA_CONTROL_MUX_HIGH_PIN19_ECAP1 << GPIOA_CONTROL_MUX_HIGH_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN20_BIT    (8UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN20_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN20_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN20_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN20_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN20_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN20_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN20_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN21_BIT    (10UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN21_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN21_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN21_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN21_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN21_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN21_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN21_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN22_BIT    (12UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN22_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN22_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN22_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN22_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN22_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN22_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN22_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN23_BIT    (14UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN23_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN23_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN23_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN23_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN23_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN23_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN23_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN24_BIT    (16UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN24_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN24_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN24_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN24_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN24_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN24_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN24_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN25_BIT    (18UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN25_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN25_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN25_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN25_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN25_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN25_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN25_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN26_BIT    (20UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN26_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN26_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN26_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN26_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN26_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN26_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN26_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN27_BIT    (22UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN27_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN27_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN27_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN27_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN27_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN27_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN27_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT    (24UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN28_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN28_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN28_SCIA_RX    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN28_I2CA_SDA    ((uint32_t) 0x00000002UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN28_EPWM_TZ2    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN28_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN28_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_SCIA_RX    (GPIOA_CONTROL_MUX_HIGH_PIN28_SCIA_RX << GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_I2CA_SDA    (GPIOA_CONTROL_MUX_HIGH_PIN28_I2CA_SDA << GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN28_EPWM_TZ2    (GPIOA_CONTROL_MUX_HIGH_PIN28_EPWM_TZ2 << GPIOA_CONTROL_MUX_HIGH_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT    (26UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN29_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN29_GPIO    ((uint32_t) 0x00000000UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN29_SCIA_TX    ((uint32_t) 0x00000001UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN29_I2CA_SCL    ((uint32_t) 0x00000002UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN29_EPWM_TZ3    ((uint32_t) 0x00000003UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN29_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN29_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_SCIA_TX    (GPIOA_CONTROL_MUX_HIGH_PIN29_SCIA_TX << GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_I2CA_SCL    (GPIOA_CONTROL_MUX_HIGH_PIN29_I2CA_SCL << GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN29_EPWM_TZ3    (GPIOA_CONTROL_MUX_HIGH_PIN29_EPWM_TZ3 << GPIOA_CONTROL_MUX_HIGH_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN30_BIT    (28UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN30_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN30_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN30_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN30_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN30_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN30_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN30_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIOA_CONTROL_MUX_HIGH_R_PIN31_BIT    (30UL)

#define GPIOA_CONTROL_MUX_HIGH_PIN31_MASK    ((uint32_t) 0x00000003UL)
#define GPIOA_CONTROL_MUX_HIGH_PIN31_GPIO    ((uint32_t) 0x00000000UL)

#define GPIOA_CONTROL_MUX_HIGH_R_PIN31_MASK    (GPIOA_CONTROL_MUX_HIGH_PIN31_MASK << GPIOA_CONTROL_MUX_HIGH_R_PIN31_BIT)
#define GPIOA_CONTROL_MUX_HIGH_R_PIN31_GPIO    (GPIOA_CONTROL_MUX_HIGH_PIN31_GPIO << GPIOA_CONTROL_MUX_HIGH_R_PIN31_BIT)
/*----------*/



#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_MUX2_H_ */
