/**
 *
 * @file GPIO_RegisterDefines_DAT.h
 * @copyright
 * @verbatim InDeviceMex 2021 @endverbatim
 *
 * @par Responsibility
 * @verbatim InDeviceMex Developers @endverbatim
 *
 * @version
 * @verbatim 1.0 @endverbatim
 *
 * @date
 * @verbatim 18 ago. 2022 @endverbatim
 *
 * @author
 * @verbatim InDeviceMex @endverbatim
 *
 * @par Change History
 * @verbatim
 * Date           Author     Version     Description
 * 18 ago. 2022     InDeviceMex    1.0         initial Version@endverbatim
 */

#ifndef DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_DAT_H_
#define DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_DAT_H_

#include "DriverLib/MCU/xHeader/MCU_Variables.h"

/******************************************************************************************
 ************************************ 6 DAT *********************************************
 ******************************************************************************************/
/*----------*/
#define GPIO_DATA_DAT_R_PIN_BIT    (0UL)

#define GPIO_DATA_DAT_PIN_MASK    ((uint32_t) 0xFFFFFFFFUL)
#define GPIO_DATA_DAT_PIN_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN_HIGH    ((uint32_t) 0xFFFFFFFFUL)

#define GPIO_DATA_DAT_R_PIN_MASK    (GPIO_DATA_DAT_PIN_MASK<< GPIO_DATA_DAT_R_PIN_BIT)
#define GPIO_DATA_DAT_R_PIN_LOW    (GPIO_DATA_DAT_PIN_LOW<< GPIO_DATA_DAT_R_PIN_BIT)
#define GPIO_DATA_DAT_R_PIN_HIGH    (GPIO_DATA_DAT_PIN_HIGH<< GPIO_DATA_DAT_R_PIN_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN0_BIT    (0UL)

#define GPIO_DATA_DAT_PIN0_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN0_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN0_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN0_MASK    (GPIO_DATA_DAT_PIN0_MASK<< GPIO_DATA_DAT_R_PIN0_BIT)
#define GPIO_DATA_DAT_R_PIN0_LOW    (GPIO_DATA_DAT_PIN0_LOW<< GPIO_DATA_DAT_R_PIN0_BIT)
#define GPIO_DATA_DAT_R_PIN0_HIGH    (GPIO_DATA_DAT_PIN0_HIGH<< GPIO_DATA_DAT_R_PIN0_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN1_BIT    (1UL)

#define GPIO_DATA_DAT_PIN1_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN1_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN1_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN1_MASK    (GPIO_DATA_DAT_PIN1_MASK<< GPIO_DATA_DAT_R_PIN1_BIT)
#define GPIO_DATA_DAT_R_PIN1_LOW    (GPIO_DATA_DAT_PIN1_LOW<< GPIO_DATA_DAT_R_PIN1_BIT)
#define GPIO_DATA_DAT_R_PIN1_HIGH    (GPIO_DATA_DAT_PIN1_HIGH<< GPIO_DATA_DAT_R_PIN1_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN2_BIT    (2UL)

#define GPIO_DATA_DAT_PIN2_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN2_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN2_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN2_MASK    (GPIO_DATA_DAT_PIN2_MASK<< GPIO_DATA_DAT_R_PIN2_BIT)
#define GPIO_DATA_DAT_R_PIN2_LOW    (GPIO_DATA_DAT_PIN2_LOW<< GPIO_DATA_DAT_R_PIN2_BIT)
#define GPIO_DATA_DAT_R_PIN2_HIGH    (GPIO_DATA_DAT_PIN2_HIGH<< GPIO_DATA_DAT_R_PIN2_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN3_BIT    (3UL)

#define GPIO_DATA_DAT_PIN3_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN3_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN3_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN3_MASK    (GPIO_DATA_DAT_PIN3_MASK<< GPIO_DATA_DAT_R_PIN3_BIT)
#define GPIO_DATA_DAT_R_PIN3_LOW    (GPIO_DATA_DAT_PIN3_LOW<< GPIO_DATA_DAT_R_PIN3_BIT)
#define GPIO_DATA_DAT_R_PIN3_HIGH    (GPIO_DATA_DAT_PIN3_HIGH<< GPIO_DATA_DAT_R_PIN3_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN4_BIT    (4UL)

#define GPIO_DATA_DAT_PIN4_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN4_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN4_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN4_MASK    (GPIO_DATA_DAT_PIN4_MASK<< GPIO_DATA_DAT_R_PIN4_BIT)
#define GPIO_DATA_DAT_R_PIN4_LOW    (GPIO_DATA_DAT_PIN4_LOW<< GPIO_DATA_DAT_R_PIN4_BIT)
#define GPIO_DATA_DAT_R_PIN4_HIGH    (GPIO_DATA_DAT_PIN4_HIGH<< GPIO_DATA_DAT_R_PIN4_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN5_BIT    (5UL)

#define GPIO_DATA_DAT_PIN5_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN5_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN5_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN5_MASK    (GPIO_DATA_DAT_PIN5_MASK<< GPIO_DATA_DAT_R_PIN5_BIT)
#define GPIO_DATA_DAT_R_PIN5_LOW    (GPIO_DATA_DAT_PIN5_LOW<< GPIO_DATA_DAT_R_PIN5_BIT)
#define GPIO_DATA_DAT_R_PIN5_HIGH    (GPIO_DATA_DAT_PIN5_HIGH<< GPIO_DATA_DAT_R_PIN5_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN6_BIT    (6UL)

#define GPIO_DATA_DAT_PIN6_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN6_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN6_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN6_MASK    (GPIO_DATA_DAT_PIN6_MASK<< GPIO_DATA_DAT_R_PIN6_BIT)
#define GPIO_DATA_DAT_R_PIN6_LOW    (GPIO_DATA_DAT_PIN6_LOW<< GPIO_DATA_DAT_R_PIN6_BIT)
#define GPIO_DATA_DAT_R_PIN6_HIGH    (GPIO_DATA_DAT_PIN6_HIGH<< GPIO_DATA_DAT_R_PIN6_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN7_BIT    (7UL)

#define GPIO_DATA_DAT_PIN7_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN7_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN7_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN7_MASK    (GPIO_DATA_DAT_PIN7_MASK<< GPIO_DATA_DAT_R_PIN7_BIT)
#define GPIO_DATA_DAT_R_PIN7_LOW    (GPIO_DATA_DAT_PIN7_LOW<< GPIO_DATA_DAT_R_PIN7_BIT)
#define GPIO_DATA_DAT_R_PIN7_HIGH    (GPIO_DATA_DAT_PIN7_HIGH<< GPIO_DATA_DAT_R_PIN7_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN8_BIT    (8UL)

#define GPIO_DATA_DAT_PIN8_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN8_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN8_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN8_MASK    (GPIO_DATA_DAT_PIN8_MASK<< GPIO_DATA_DAT_R_PIN8_BIT)
#define GPIO_DATA_DAT_R_PIN8_LOW    (GPIO_DATA_DAT_PIN8_LOW<< GPIO_DATA_DAT_R_PIN8_BIT)
#define GPIO_DATA_DAT_R_PIN8_HIGH    (GPIO_DATA_DAT_PIN8_HIGH<< GPIO_DATA_DAT_R_PIN8_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN9_BIT    (9UL)

#define GPIO_DATA_DAT_PIN9_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN9_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN9_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN9_MASK    (GPIO_DATA_DAT_PIN9_MASK<< GPIO_DATA_DAT_R_PIN9_BIT)
#define GPIO_DATA_DAT_R_PIN9_LOW    (GPIO_DATA_DAT_PIN9_LOW<< GPIO_DATA_DAT_R_PIN9_BIT)
#define GPIO_DATA_DAT_R_PIN9_HIGH    (GPIO_DATA_DAT_PIN9_HIGH<< GPIO_DATA_DAT_R_PIN9_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN10_BIT    (10UL)

#define GPIO_DATA_DAT_PIN10_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN10_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN10_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN10_MASK    (GPIO_DATA_DAT_PIN10_MASK<< GPIO_DATA_DAT_R_PIN10_BIT)
#define GPIO_DATA_DAT_R_PIN10_LOW    (GPIO_DATA_DAT_PIN10_LOW<< GPIO_DATA_DAT_R_PIN10_BIT)
#define GPIO_DATA_DAT_R_PIN10_HIGH    (GPIO_DATA_DAT_PIN10_HIGH<< GPIO_DATA_DAT_R_PIN10_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN11_BIT    (11UL)

#define GPIO_DATA_DAT_PIN11_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN11_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN11_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN11_MASK    (GPIO_DATA_DAT_PIN11_MASK<< GPIO_DATA_DAT_R_PIN11_BIT)
#define GPIO_DATA_DAT_R_PIN11_LOW    (GPIO_DATA_DAT_PIN11_LOW<< GPIO_DATA_DAT_R_PIN11_BIT)
#define GPIO_DATA_DAT_R_PIN11_HIGH    (GPIO_DATA_DAT_PIN11_HIGH<< GPIO_DATA_DAT_R_PIN11_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN12_BIT    (12UL)

#define GPIO_DATA_DAT_PIN12_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN12_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN12_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN12_MASK    (GPIO_DATA_DAT_PIN12_MASK<< GPIO_DATA_DAT_R_PIN12_BIT)
#define GPIO_DATA_DAT_R_PIN12_LOW    (GPIO_DATA_DAT_PIN12_LOW<< GPIO_DATA_DAT_R_PIN12_BIT)
#define GPIO_DATA_DAT_R_PIN12_HIGH    (GPIO_DATA_DAT_PIN12_HIGH<< GPIO_DATA_DAT_R_PIN12_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN13_BIT    (13UL)

#define GPIO_DATA_DAT_PIN13_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN13_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN13_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN13_MASK    (GPIO_DATA_DAT_PIN13_MASK<< GPIO_DATA_DAT_R_PIN13_BIT)
#define GPIO_DATA_DAT_R_PIN13_LOW    (GPIO_DATA_DAT_PIN13_LOW<< GPIO_DATA_DAT_R_PIN13_BIT)
#define GPIO_DATA_DAT_R_PIN13_HIGH    (GPIO_DATA_DAT_PIN13_HIGH<< GPIO_DATA_DAT_R_PIN13_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN14_BIT    (14UL)

#define GPIO_DATA_DAT_PIN14_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN14_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN14_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN14_MASK    (GPIO_DATA_DAT_PIN14_MASK<< GPIO_DATA_DAT_R_PIN14_BIT)
#define GPIO_DATA_DAT_R_PIN14_LOW    (GPIO_DATA_DAT_PIN14_LOW<< GPIO_DATA_DAT_R_PIN14_BIT)
#define GPIO_DATA_DAT_R_PIN14_HIGH    (GPIO_DATA_DAT_PIN14_HIGH<< GPIO_DATA_DAT_R_PIN14_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN15_BIT    (15UL)

#define GPIO_DATA_DAT_PIN15_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN15_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN15_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN15_MASK    (GPIO_DATA_DAT_PIN15_MASK<< GPIO_DATA_DAT_R_PIN15_BIT)
#define GPIO_DATA_DAT_R_PIN15_LOW    (GPIO_DATA_DAT_PIN15_LOW<< GPIO_DATA_DAT_R_PIN15_BIT)
#define GPIO_DATA_DAT_R_PIN15_HIGH    (GPIO_DATA_DAT_PIN15_HIGH<< GPIO_DATA_DAT_R_PIN15_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN16_BIT    (16UL)

#define GPIO_DATA_DAT_PIN16_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN16_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN16_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN16_MASK    (GPIO_DATA_DAT_PIN16_MASK<< GPIO_DATA_DAT_R_PIN16_BIT)
#define GPIO_DATA_DAT_R_PIN16_LOW    (GPIO_DATA_DAT_PIN16_LOW<< GPIO_DATA_DAT_R_PIN16_BIT)
#define GPIO_DATA_DAT_R_PIN16_HIGH    (GPIO_DATA_DAT_PIN16_HIGH<< GPIO_DATA_DAT_R_PIN16_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN17_BIT    (17UL)

#define GPIO_DATA_DAT_PIN17_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN17_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN17_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN17_MASK    (GPIO_DATA_DAT_PIN17_MASK<< GPIO_DATA_DAT_R_PIN17_BIT)
#define GPIO_DATA_DAT_R_PIN17_LOW    (GPIO_DATA_DAT_PIN17_LOW<< GPIO_DATA_DAT_R_PIN17_BIT)
#define GPIO_DATA_DAT_R_PIN17_HIGH    (GPIO_DATA_DAT_PIN17_HIGH<< GPIO_DATA_DAT_R_PIN17_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN18_BIT    (18UL)

#define GPIO_DATA_DAT_PIN18_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN18_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN18_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN18_MASK    (GPIO_DATA_DAT_PIN18_MASK<< GPIO_DATA_DAT_R_PIN18_BIT)
#define GPIO_DATA_DAT_R_PIN18_LOW    (GPIO_DATA_DAT_PIN18_LOW<< GPIO_DATA_DAT_R_PIN18_BIT)
#define GPIO_DATA_DAT_R_PIN18_HIGH    (GPIO_DATA_DAT_PIN18_HIGH<< GPIO_DATA_DAT_R_PIN18_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN19_BIT    (19UL)

#define GPIO_DATA_DAT_PIN19_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN19_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN19_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN19_MASK    (GPIO_DATA_DAT_PIN19_MASK<< GPIO_DATA_DAT_R_PIN19_BIT)
#define GPIO_DATA_DAT_R_PIN19_LOW    (GPIO_DATA_DAT_PIN19_LOW<< GPIO_DATA_DAT_R_PIN19_BIT)
#define GPIO_DATA_DAT_R_PIN19_HIGH    (GPIO_DATA_DAT_PIN19_HIGH<< GPIO_DATA_DAT_R_PIN19_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN20_BIT    (20UL)

#define GPIO_DATA_DAT_PIN20_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN20_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN20_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN20_MASK    (GPIO_DATA_DAT_PIN20_MASK<< GPIO_DATA_DAT_R_PIN20_BIT)
#define GPIO_DATA_DAT_R_PIN20_LOW    (GPIO_DATA_DAT_PIN20_LOW<< GPIO_DATA_DAT_R_PIN20_BIT)
#define GPIO_DATA_DAT_R_PIN20_HIGH    (GPIO_DATA_DAT_PIN20_HIGH<< GPIO_DATA_DAT_R_PIN20_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN21_BIT    (21UL)

#define GPIO_DATA_DAT_PIN21_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN21_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN21_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN21_MASK    (GPIO_DATA_DAT_PIN21_MASK<< GPIO_DATA_DAT_R_PIN21_BIT)
#define GPIO_DATA_DAT_R_PIN21_LOW    (GPIO_DATA_DAT_PIN21_LOW<< GPIO_DATA_DAT_R_PIN21_BIT)
#define GPIO_DATA_DAT_R_PIN21_HIGH    (GPIO_DATA_DAT_PIN21_HIGH<< GPIO_DATA_DAT_R_PIN21_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN22_BIT    (22UL)

#define GPIO_DATA_DAT_PIN22_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN22_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN22_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN22_MASK    (GPIO_DATA_DAT_PIN22_MASK<< GPIO_DATA_DAT_R_PIN22_BIT)
#define GPIO_DATA_DAT_R_PIN22_LOW    (GPIO_DATA_DAT_PIN22_LOW<< GPIO_DATA_DAT_R_PIN22_BIT)
#define GPIO_DATA_DAT_R_PIN22_HIGH    (GPIO_DATA_DAT_PIN22_HIGH<< GPIO_DATA_DAT_R_PIN22_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN23_BIT    (23UL)

#define GPIO_DATA_DAT_PIN23_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN23_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN23_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN23_MASK    (GPIO_DATA_DAT_PIN23_MASK<< GPIO_DATA_DAT_R_PIN23_BIT)
#define GPIO_DATA_DAT_R_PIN23_LOW    (GPIO_DATA_DAT_PIN23_LOW<< GPIO_DATA_DAT_R_PIN23_BIT)
#define GPIO_DATA_DAT_R_PIN23_HIGH    (GPIO_DATA_DAT_PIN23_HIGH<< GPIO_DATA_DAT_R_PIN23_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN24_BIT    (24UL)

#define GPIO_DATA_DAT_PIN24_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN24_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN24_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN24_MASK    (GPIO_DATA_DAT_PIN24_MASK<< GPIO_DATA_DAT_R_PIN24_BIT)
#define GPIO_DATA_DAT_R_PIN24_LOW    (GPIO_DATA_DAT_PIN24_LOW<< GPIO_DATA_DAT_R_PIN24_BIT)
#define GPIO_DATA_DAT_R_PIN24_HIGH    (GPIO_DATA_DAT_PIN24_HIGH<< GPIO_DATA_DAT_R_PIN24_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN25_BIT    (25UL)

#define GPIO_DATA_DAT_PIN25_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN25_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN25_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN25_MASK    (GPIO_DATA_DAT_PIN25_MASK<< GPIO_DATA_DAT_R_PIN25_BIT)
#define GPIO_DATA_DAT_R_PIN25_LOW    (GPIO_DATA_DAT_PIN25_LOW<< GPIO_DATA_DAT_R_PIN25_BIT)
#define GPIO_DATA_DAT_R_PIN25_HIGH    (GPIO_DATA_DAT_PIN25_HIGH<< GPIO_DATA_DAT_R_PIN25_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN26_BIT    (26UL)

#define GPIO_DATA_DAT_PIN26_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN26_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN26_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN26_MASK    (GPIO_DATA_DAT_PIN26_MASK<< GPIO_DATA_DAT_R_PIN26_BIT)
#define GPIO_DATA_DAT_R_PIN26_LOW    (GPIO_DATA_DAT_PIN26_LOW<< GPIO_DATA_DAT_R_PIN26_BIT)
#define GPIO_DATA_DAT_R_PIN26_HIGH    (GPIO_DATA_DAT_PIN26_HIGH<< GPIO_DATA_DAT_R_PIN26_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN27_BIT    (27UL)

#define GPIO_DATA_DAT_PIN27_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN27_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN27_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN27_MASK    (GPIO_DATA_DAT_PIN27_MASK<< GPIO_DATA_DAT_R_PIN27_BIT)
#define GPIO_DATA_DAT_R_PIN27_LOW    (GPIO_DATA_DAT_PIN27_LOW<< GPIO_DATA_DAT_R_PIN27_BIT)
#define GPIO_DATA_DAT_R_PIN27_HIGH    (GPIO_DATA_DAT_PIN27_HIGH<< GPIO_DATA_DAT_R_PIN27_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN28_BIT    (28UL)

#define GPIO_DATA_DAT_PIN28_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN28_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN28_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN28_MASK    (GPIO_DATA_DAT_PIN28_MASK<< GPIO_DATA_DAT_R_PIN28_BIT)
#define GPIO_DATA_DAT_R_PIN28_LOW    (GPIO_DATA_DAT_PIN28_LOW<< GPIO_DATA_DAT_R_PIN28_BIT)
#define GPIO_DATA_DAT_R_PIN28_HIGH    (GPIO_DATA_DAT_PIN28_HIGH<< GPIO_DATA_DAT_R_PIN28_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN29_BIT    (29UL)

#define GPIO_DATA_DAT_PIN29_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN29_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN29_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN29_MASK    (GPIO_DATA_DAT_PIN29_MASK<< GPIO_DATA_DAT_R_PIN29_BIT)
#define GPIO_DATA_DAT_R_PIN29_LOW    (GPIO_DATA_DAT_PIN29_LOW<< GPIO_DATA_DAT_R_PIN29_BIT)
#define GPIO_DATA_DAT_R_PIN29_HIGH    (GPIO_DATA_DAT_PIN29_HIGH<< GPIO_DATA_DAT_R_PIN29_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN30_BIT    (30UL)

#define GPIO_DATA_DAT_PIN30_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN30_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN30_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN30_MASK    (GPIO_DATA_DAT_PIN30_MASK<< GPIO_DATA_DAT_R_PIN30_BIT)
#define GPIO_DATA_DAT_R_PIN30_LOW    (GPIO_DATA_DAT_PIN30_LOW<< GPIO_DATA_DAT_R_PIN30_BIT)
#define GPIO_DATA_DAT_R_PIN30_HIGH    (GPIO_DATA_DAT_PIN30_HIGH<< GPIO_DATA_DAT_R_PIN30_BIT)
/*----------*/

/*----------*/
#define GPIO_DATA_DAT_R_PIN31_BIT    (31UL)

#define GPIO_DATA_DAT_PIN31_MASK    ((uint32_t) 0x00000001UL)
#define GPIO_DATA_DAT_PIN31_LOW    ((uint32_t) 0x00000000UL)
#define GPIO_DATA_DAT_PIN31_HIGH    ((uint32_t) 0x00000001UL)

#define GPIO_DATA_DAT_R_PIN31_MASK    (GPIO_DATA_DAT_PIN31_MASK<< GPIO_DATA_DAT_R_PIN31_BIT)
#define GPIO_DATA_DAT_R_PIN31_LOW    (GPIO_DATA_DAT_PIN31_LOW<< GPIO_DATA_DAT_R_PIN31_BIT)
#define GPIO_DATA_DAT_R_PIN31_HIGH    (GPIO_DATA_DAT_PIN31_HIGH<< GPIO_DATA_DAT_R_PIN31_BIT)
/*----------*/




#endif /* DRIVERLIB_GPIO_PERIPHERAL_REGISTERDEFINES_XHEADER_GPIO_REGISTERDEFINES_DAT_H_ */
